### PR TITLE
fix(coderd): improve workspace tests

### PR DESCRIPTION
**Pull request by defelmnq**
With [a recent PR](https://github.com/coder/coder/pull/14923) we introduced [new tests](https://github.com/coder/coder/pull/14923/files#diff-81081239b93aaa61eb8d180a5f9870fda8f0ab5cb4c6727d9d1636aa933e597b) that - while running in parallel to the existing ones - are failing.

This PR is a quick proposal to fix it - tested in local and in the CI to unblock the situation. We can ignore it to work on a longer term solution if preferred.

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
stamp 👍

**Review by johnstcn — APPROVED** [review]
Is there a follow-up PR to investigate re-enabling parallelism for these tests?

**Comment by defelmnq** [comment]
https://github.com/coder/coder/issues/15083

Just created the follow-up issue to keep it in mind.

**Comment by BrunoQuaresma** [comment]
I have fixed that by moving the workspace creation inside of each test 🤔 https://github.com/coder/coder/pull/15077

**Pull request merged**
