### PR TITLE
feat: Add user menu

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Closes #743

### CODE REVIEW

**Review by greyscaled — COMMENTED** [review]
Can we storybook the user dropdown?

**Review by greyscaled — CHANGES_REQUESTED** [review]
Can you merge latest main into this branch so that we get the Chromatic workflow to run

**Review by presleyp — CHANGES_REQUESTED** [review]
Great test! Same comment on this one - can you pull out the labels into a `Language` constant and then, you can also use that constant in your tests to make them less brittle in what they target. Feel free not to in any cases where you think we should test that the language is actually what we expect it to be.

**Review by presleyp — APPROVED** [review]
Found a tiny thing but basically good to go!

**Review by greyscaled — APPROVED** [review]
It's safe to ignore the chromatic error here - it's because in #910 the secret token was deleted. You can either merge latest main, and CI will rerun, or just merge.

**Pull request merged**
