### PR TITLE
feat: promote single-tailnet out of experimental

### PR DESCRIPTION
**Pull request by spikecurtis**
Single tailnet is no longer experimental

### CODE REVIEW

**Comment by spikecurtis** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #11366** <a href="https://app.graphite.dev/github/pr/coder/coder/11366?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/11366?utm_source=stack-comment).

**Comment by bpmct** [comment]
Silly question, but single tailnet is different than tailnet v2, right?

**Review by coadler — APPROVED** [review]
🛥️

**Comment by spikecurtis** [comment]
> Silly question, but single tailnet is different than tailnet v2, right?

Yeah, single tailnet is a performance optimization to get better memory utilization when Coderd proxies connections to workspaces.

Tailnet v2 is an upgrade to the coordination protocol to allow for things like explicit disconnects, & API versioning.

**Pull request merged**
