### PR TITLE
chore: remove i18next

### LINKED ISSUE #9597: Remove i18n

### PR DESCRIPTION
**Pull request by aslilac**
Closes #9597 

Get out of here!! >:(

This also fixes *dozens* of issues that I found along the way, of missing or incorrect language

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
Oh my God, you did it!

**Review by BrunoQuaresma — APPROVED** [review]
Testing passing and stories are ok, lets go!

**Comment by aslilac** [comment]
> Oh my God, you did it!

today was really a grind lmao, glad to have it over with

**Comment by aslilac** [comment]
couple minor visual things to work out, I'll finish this up on monday

**Pull request merged**
