### PR TITLE
feat: add api-rate-limit flag

### PR DESCRIPTION
**Pull request by deansheather**
We already had a setting for it in coderd.Options but no flag on `coder server`. This is affecting us in loadtests (even though we're setting the bypass variable for some reason).

### CODE REVIEW

**Review by coadler — APPROVED** [review]

**Review by kylecarbs — COMMENTED** [review]
Should we fix the bypass header instead? Seems like it's kinda janky to have both...

**Comment by coadler** [comment]
Either way I think this should be configurable.

**Comment by deansheather** [comment]
Bypass is tested so this may be failures caused by agents having the same IP address instead, we're not really sure where the failures are coming from.

**Comment by kylecarbs** [comment]
Ahh, so agents are failing to connect?

**Comment by deansheather** [comment]
I'm not really sure what the source of the problem was but we are using the bypass header and the bypass header is tested, so I can't think of any other source of the ratelimits than the agent... This is blocking us from going above 500 workspace builds simultaneously in loadtests

**Pull request merged**
