### PR TITLE
feat: add organizations filter to audit table

### PR DESCRIPTION
**Pull request by code-asher**
It also removes tracking the org ID from some diffs, since it never changes, for consistency.

The filters take up a good amount of space.  At some point maybe they need to be collapsible or go under the search input or something.

Some thoughts I had:

**EDIT**: will revisit these thoughts after the new mocks, for now we can leave the org info where it is.

- Should the organization be linked as it currently is?  Seems useful but also the blue feels noisy.
- Instead of having it on the right, could add "in organization $org" to the left side text.  For example "created template docker in organization $org" or even "created template docker in $org"
- I put `Org: ` because `Organization: ` felt long and unbalanced, but now it looks sorta unprofessional.
- Maybe org should go first before ip/browser/os.

Part 2 of https://github.com/coder/coder/issues/13913

audit log

audit log with org filter

### CODE REVIEW

**Comment by code-asher** [comment]
Example of that second idea:

org inline

**Comment by code-asher** [comment]
Some more mocks are coming so the way we show the org on the page might change, so for now I think the questions I was asking can be ignored.

**Comment by code-asher** [comment]
Looks like we are not actually going to have an organization filter dropdown which is a big part of this PR so I am going to extract the parts we still need and open a new PR.

**Comment by code-asher** [comment]
Uhh nevermind, this is still applicable.

**Review by jaaydenh — APPROVED** [review]
Overall looks good. When we come back to remove the experiment, I think it would be a good idea to remove setting the explicit width that is added here.

**Comment by code-asher** [comment]
> When we come back to remove the experiment, I think it would be a good idea to remove setting the explicit width that is added here.

Good point!  I will make a note.

**Pull request merged**
