### PR TITLE
feat: Allow only workspace owner connections

### PR DESCRIPTION
**Pull request by bensejas**
# Draft

This is a draft and I need some feedback. I suspect the best way to do this might be via permissions and RBCA but I need some guidance here. 

## Context

Currently, the owner role has the ability to connect to all workspaces. This is not ideal from a security perspective because it increases exposure as a compromised admin account has access to workspaces and can perform malicious actions.

## Intent

We want to only allow the workspace owner to have the ability to connect to their workspace.

## Changes

* Adding a server option `CODER_WORKSPACE_OWNER_CONNECTION_ONLY` to only allow workspace owners connection to their workspaces

## TODO

* Write tests
* Remove agent apps from the UI when non-owner views workspace (e.g. Terminal Link, SSH button)
* Handle connection errors when attempting to SSH

### CODE REVIEW

**Comment by bensejas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kylecarbs** [comment]
@bensejas love the contribution!

Seems reasonable to me... we actually have an RBAC permission that controls workspace connectivity, so this should actually be *super* easy to pipe through.

@Emyrk can you provide some thoughts on how we do this? We're also happy to take this over, since it might be a bit involved.

**Comment by Emyrk** [comment]
> @Emyrk do you have time to take this over and implement it? The config flag seems reasonable from my perspective.

I can implement this yes. Just want to know what the end goal is. The way it is currently implemented does more than just reduce the owner role. It prevents any other access by any other means we might invent later. (Eg workspace proxies maybe)

**Comment by bensejas** [comment]
>We're also happy to take this over

Fantastic 🎉 Thank you!

**Comment by Emyrk** [comment]
I am going to implement this is Golang. To do this in rbac would be to allow us to reduce the scope of `*` or actually expand it in the roles. We are currently lazy:

https://github.com/coder/coder/blob/0347231bb8b4b04c150a90a6a0a542a827a27ecc/coderd/rbac/roles.go#L80-L80

I will do in Go, and maybe we can revisit doing this in RBAC/rego

**Pull request closed without merging**
