### PR TITLE
chore: rename FakeCoordinator for export

### PR DESCRIPTION
**Pull request by spikecurtis**
Part of a stack that fixes graceful disconnect from the CLI to tailnet.  I reuse FakeCoordinator in a test for graceful disconnects.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* `main`
  * **#11991** <a href="https://app.graphite.dev/github/pr/coder/coder/11991?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **#11992** <a href="https://app.graphite.dev/github/pr/coder/coder/11992?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **#11993** <a href="https://app.graphite.dev/github/pr/coder/coder/11993?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spikecurtis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by johnstcn — COMMENTED** [review]
Leaving the exported methods `ServeAgent`, `Close`, `ServeMultiAgent` etc. as just panicking is likely to cause an unwelcome surprise to a later unwary user.

I'd feel better if we passed in a `*testing.T` into `FakeCoordinator` and call `t.Fail()` if these methods are called, as that will at least give some more useful indication of where to look. Panicking right now in tests does not produce a useful stacktrace.

**Comment by spikecurtis** [comment]
Here's what I get when we hit a panic:

```
=== RUN   TestConfigMaps_setBlockEndpoints_different
=== PAUSE TestConfigMaps_setBlockEndpoints_different
=== CONT  TestConfigMaps_setBlockEndpoints_different
panic: do I get a stacktrace?

goroutine 118 [running]:
github.com/coder/coder/v2/tailnet/tailnettest.(*FakeCoordinator).ServeClient(0x1400062c2b0?, {0x1?, 0x1?}, {0x10, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, ...}, ...)
	/Users/spike/repos/coder/tailnet/tailnettest/tailnettest.go:267 +0x2c
github.com/coder/coder/v2/tailnet.(*ClientService).ServeClient(0x140007a2070, {0x101c86320, 0x14000616420}, {0x101791764, 0x3}, {0x101c8d440, 0x14000140300}, {0x10, 0x0, 0x0, ...}, ...)
	/Users/spike/repos/coder/tailnet/service.go:92 +0x3c4
github.com/coder/coder/v2/tailnet_test.TestClientService_ServeClient_V1.func1()
	/Users/spike/repos/coder/tailnet/service_test.go:122 +0x60
created by github.com/coder/coder/v2/tailnet_test.TestClientService_ServeClient_V1
	/Users/spike/repos/coder/tailnet/service_test.go:121 +0x444
```

vs `t.Fatal`

```
=== RUN   TestClientService_ServeClient_V1
=== PAUSE TestClientService_ServeClient_V1
=== CONT  TestClientService_ServeClient_V1
    tailnettest.go:268: do I get a stacktrace?
    service_test.go:127: timeout
--- FAIL: TestClientService_ServeClient_V1 (10.00s)
```

vs `t.Error` --- since we "shouldn't" use `Fatal` as these are basically always called from a goroutine.

```
=== RUN   TestClientService_ServeClient_V1
=== PAUSE TestClientService_ServeClient_V1
=== CONT  TestClientService_ServeClient_V1
    tailnettest.go:268: do I get a stacktrace?
    service_test.go:123: ServeClient returned; err=test error
--- FAIL: TestClientService_ServeClient_V1 (0.00s)
```

so, anyway, the _only_ way to get a stacktrace is panic.

**Review by johnstcn — APPROVED** [review]

**Comment by spikecurtis** [comment]
### Merge activity

* **Feb 5, 4:33 AM EST**: @spikecurtis started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/coder/coder/11991).

**Pull request merged**
