### PR TITLE
feat: add rich parameters

### PR DESCRIPTION
**Pull request by kylecarbs**
This adds support for a new `coder_parameter` type in Terraform which supports immutable, editable, and visually appealing parameters.

Examples:

image
image

Exposing the variable syntax in Terraform will become deprecated, and users will be forced to adopt the `coder_parameter` data source. Here's an example of the syntax:

```tf
data "coder_parameter" "example" {
  name = "Example"
  type = "string"
  option {
    name  = "First Option"
    value = "first"
  }
  option {
    name  = "Second Option"
    value = "second"
  }
}
```

Todo:
- [ ] Update the `create` CLI to work with the new parameters.
- [ ] Show a "deprecated" message in the UI with instructions to switch to new parameters.
- [ ] Convert example templates to use the new parameter type.
- [ ] Edit the "workspace create" UI to be prettier!

### CODE REVIEW

**Comment by kylecarbs** [comment]
This PR has risen from the depths 👀

**Comment by dcarrion87** [comment]
Noooooo! I hope this is still a thing?

**Comment by OnlyCS** [comment]
@bpmct

**Comment by kylecarbs** [comment]
This is still a thing! Holiday stale bot!

**Comment by mtojek** [comment]
> @mtojek — you're taking this now, right?

Yes, once I'm done with the task I'm working on at the moment - https://github.com/coder/coder/issues/3522.

I haven't started this one, just skimmed through the PR to understand the scope. We have a call about it tomorrow.

**Comment by dcarrion87** [comment]
Bump for reopen.

**Comment by kylecarbs** [comment]
@dcarrion87 this is being implemented in chunks now! Follow #5574 instead.

**Pull request closed without merging**
