### PR TITLE
fix(examples): use more precise example kubernetes template labels

### PR DESCRIPTION
**Pull request by geniass**
The current example template doesn't have the selector labels to correct identify the pods created by the workspace kubernetes deployment. 

I.e. when multiple workspaces are created from a template, the deployment resources incorrectly try to manage pods from the other workspace's deployment.

This fix also changes persistent resource names to use immutable IDs instead of names as per the docs: https://coder.com/docs/templates/resource-persistence

### CODE REVIEW

**Comment by geniass** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by geniass** [comment]
recheck

**Comment by geniass** [comment]
recheck

**Review by johnstcn — COMMENTED** [review]
I agree with the overall intent, but Kubernetes PVCs have a length limit of 63 characters. The `workspace_instance` local will be 73 characters long as it consists of 2 UUIDs joined by a hyphen. 

How about we instead use `data.coder_workspace.me.id` to act as a stable identifier?

**Comment by geniass** [comment]
> I agree with the overall intent, but Kubernetes PVCs have a length limit of 63 characters. The `workspace_instance` local will be 73 characters long as it consists of 2 UUIDs joined by a hyphen.
> 
> How about we instead use `data.coder_workspace.me.id` to act as a stable identifier?

Good catch, I think `data.coder_workspace.me.id` is good for the PVC name. Do you think there's any reason to keep `workspace_instance` for the labels or should I just make everything use the workspace ID?

**Comment by johnstcn** [comment]
> Good catch, I think `data.coder_workspace.me.id` is good for the PVC name. Do you think there's any reason to keep `workspace_instance` for the labels or should I just make everything use the workspace ID?

I think you'll run into the same issue if you try to use that `workspace_instance` local as a label value:

> A label key and value must begin with a letter or number, and may contain letters, numbers, hyphens, dots, and underscores, up to 63 characters each.

https://kubernetes.io/docs/reference/kubectl/generated/kubectl_label/

**Comment by geniass** [comment]
Sorry I didn't realise labels had the same restriction. I've changed everything to just use the workspace ID.

**Comment by matifali** [comment]
@geniass, it looks like CLA is still not signed by you. This can happen if your GitHub email and your commuter email are different.

**Comment by geniass** [comment]
recheck

**Review by johnstcn — APPROVED** [review]
👍 Smoke-tested on my personal deployment (v2.14.1)

**Pull request merged**
