### PR TITLE
fix: show dormant and suspended users in groups

### LINKED ISSUE #10267: bug: If a user is dormant, the Group UI will not show them in the list view.
Version: [`v2.3.0+04e6783`](https://github.com/coder/coder/commit/04e67836a500d668c0bd3c8eb825c799a893dbb0)

If a user is dormant, the Group UI will not show them in the list view.

This can lead to conditions like an admin thinks they added a user to a group, but they do not show in the list. They try adding the user again, and it says a duplicate user is already in the group.

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves #10267

I am also showing suspended users because I am not sure why we wouldn't want to. Let me know if this is a misstep and I'll revert it.
Screenshot 2023-10-18 at 3 05 22 PM

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
I think could be interesting to add a column "status" as we have on the users' page.

**Comment by sreya** [comment]
I'm of the opinion that we should do the opposite: we shouldn't allow adding dormant or suspended users to groups. Thoughts?

**Comment by BrunoQuaresma** [comment]
@sreya I think it is ok but we still have to deal with the case where users can be added to the group and be set as dormant or suspended after.

**Comment by Kira-Pilot** [comment]
@sreya @BrunoQuaresma If we didn't allow adding them to groups, we'd have to figure out what to do with users who have been previously added to groups and then become dormant or suspended, which, IMO, may unnecessarily complicate things. Do we have a good reason to not want them added? I can add a status column to make their inactive status more apparent as per Bruno's suggestion if that makes their presence more tolerable.

**Comment by sreya** [comment]
Yeah I guess I was thinking we just wouldn't return suspended or dormant users. Dormant users don't count against the license count so it's almost like they don't "exist". But I'm fine with Bruno's suggestion of labeling them if they aren't active.

**Comment by Kira-Pilot** [comment]
@sreya sounds good. I could even see someone wanting to make a group of all dormant users for licensing purposes.

**Review by BrunoQuaresma — APPROVED** [review]
FE changes look good to me!

**Pull request merged**
