### PR TITLE
feat: add "updated" search param to workspaces

### LINKED ISSUE #11325: feat: Show workspaces using out-of-date template versions
A customer who operates Coder deployments would like an option in the Workspaces dashboard to show workspaces using out-of-date template versions.

The use case is the Operator makes an urgent template update, and wants to know who in their developer fleet has not already updated.

Related issue: #11326

### PR DESCRIPTION
**Pull request by Emyrk**
fixes https://github.com/coder/coder/issues/11325

Can now search for updated workspaces in the search query

### CODE REVIEW

**Review by sreya — COMMENTED** [review]
I'm not sure I understand why the parameter is named differently at all parts of the stack. The frontend is named `outdated` -- which makes the most sense to me for the name. But the backend name is `updated` and then the database parameter is `update_active`. Why not have them consistent?

**Comment by Emyrk** [comment]
> I'm not sure I understand why the parameter is named differently at all parts of the stack. The frontend is named `outdated` -- which makes the most sense to me for the name. But the backend name is `updated` and then the database parameter is `update_active`. Why not have them consistent?

There is only two names from a code POV.

I am using `UsingActive` on the database because that is physically the database column we are checking. It felt odd to put "updated" there because that word doesn't feel semantically correct.

For the api I used the word `updated` since that is the phrasing of the original ticket. And we use the language "Update" on the workspaces page when a workspace is out-of-date. So the FE tends to use `updated` as the language.

"Outdated" is just the helper text for the quick search query list. I felt this would be more commonly used that searching for all updated workspaces. And the ticket was requesting this as the feature. So that is the one I made as the quick link.

Screenshot from 2024-01-22 14-45-29


If you click it though, the language is "updated".

Screenshot from 2024-01-22 14-46-31

**Review by sreya — APPROVED** [review]
Personally I think `outdated` makes more sense as the query param but ultimately up to you.

**Comment by Emyrk** [comment]
> Personally I think `outdated` makes more sense as the query param but ultimately up to you.

I will use `outdated` as the query param :+1:

**Pull request merged**
