### PR TITLE
fix: error if protocol isn't specified in --access-url

### LINKED ISSUE #4783: access URL defaults to HTTPS when defined without a protocol
when using an access URL without specifying a protocol, (e.g. `--access-url=35.xxx.xxx.206`), the Coder agent will default to dialing the server over HTTPS, causing the connection to hang:

```
⢎⡀ Waiting for connection from  main ...
```

the fix here is to simply update the access URL to be `--access-url=http://35.xxx.xxx.206`. however, to prevent this behavior in the future, the Coder agent should default to HTTP (as `curl` does), or attempt to dial over both HTTP & HTTPS.

### PR DESCRIPTION
**Pull request by f0ssel**
Closes https://github.com/coder/coder/issues/4783

### CODE REVIEW

**Review by kylecarbs — COMMENTED** [review]
This is a breaking change that although is easy to fix, we might wanna make sure our docs don't have any usage without a protocol.

The primary case I've seen is --access-url localhost:8080 or something.

I think it's maybe better if we default to HTTP instead.

**Comment by f0ssel** [comment]
Yeah I personally like the breaking change and requiring it just because it's no extra work to provide that information.

**Comment by f0ssel** [comment]
Specifically, I would rather hard error because any sort of inference we make can lead to situations like this - https://github.com/coder/coder/issues/2874#issuecomment-1198732437

**Comment by kylecarbs** [comment]
Fair enough

**Review by kylecarbs — APPROVED** [review]

**Comment by f0ssel** [comment]
I'll talk with ben and see if we can make this breaking change loud in the changelog

**Review by jsjoeio — APPROVED** [review]
LGTM on the FE ✅

**Comment by bpmct** [comment]
Garrett and I synced. We'll include these breaking changes at the top of the changelog

**Pull request merged**
