### PR TITLE
refactor(site): refactor the workspace settings form

### LINKED ISSUE #12481: Correct and improve workspace scheduling settings around Autostop
The workspace schedule settings page shows confusing and incorrect information around Autostop.

Screenshot 2024-03-08 at 12 24 03 PM

The auto-stop in this screenshot is incorrect as the user setting is overridden by the template policy. We should make the following changes:
- [x] https://github.com/coder/coder/issues/11471:
   Change the value of “time until shutdown” to the template-level setting, if enforced (in this case it is 8 hours)
- [x] Add text below showing that the template enforces this autostop behavior, similar to how we show it from the “template policies” one (below)
- [x] Remove the “disabled” pill. This is small, and many users will think that “Disabled” means there is no auto stop for their workspace, not that they can’t modify it. 

Screenshot 2024-03-08 at 12 25 07 PM

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Before:
image

After:
Screenshot 2024-05-07 at 10 27 18

Closes https://github.com/coder/coder/issues/12481

### CODE REVIEW

**Review by Kira-Pilot — APPROVED** [review]
🤠

**Comment by stirby** [comment]
@BrunoQuaresma sorry to change the scope here, but can we apply the exact same change to Autostart?

**Comment by BrunoQuaresma** [comment]
@stirby I already did it 😉

**Review by stirby — APPROVED** [review]
I should have looked at the files first! Awesome work.

**Pull request merged**
