### PR TITLE
fix: transform underscores to hyphens for github login

### LINKED ISSUE #13339: Question: Is there a way to change forced username format in Coder OSS
Hello,

We are trying to integrate Coder OSS with Github EMU and the usernames format there contains "_"(underscore). 
Coder is not allowing to have usernames with such symbol and hence throwing an error: "Username must start with a-Z or 0-9 and can contain a-Z, 0-9 or -" for new users, that are trying to sign-up, using Github OAuth app. 

Appreciate if someone can help or point out to guidance on how to either change that rule or use some other field as a username or crop the existing emu handle to remove anything after "_"?

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #13339.

### CODE REVIEW

**Review by mafredri — APPROVED** [review]
Scary to think what might happen if there is `some_user` and `some-user` 😬.

**Comment by kylecarbs** [comment]
I'd like to think that's the edge-case of an edge-case, but maybe not...

**Comment by johnstcn** [comment]
> I'd like to think that's the edge-case of an edge-case, but maybe not...

Yeah, I think it would be a good call to have a test case for this so the behaviour is at least 'documented' as such.

**Comment by Emyrk** [comment]
> Scary to think what might happen if there is `some_user` and `some-user` 😬.

At least their uid on the GH side would be different. Which is what we use for account link lookup iirc

**Review by johnstcn — APPROVED** [review]

**Pull request merged**
