### PR TITLE
feat(site): warn user if they leave the editor without publishing

### LINKED ISSUE #12360: Feature: Warn users they will lose unpublished template changes
## Problem

When making changes to your templates, you need to run Build and then Publish, if you navigate way before clicking publish you will lose your work in progress.

## Suggestion

At least if the "Publish" button is enabled (which is true when there are changes and build was successful), when a user tries to close the browser tab or navigate away, there should be a warning message.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
https://github.com/coder/coder/assets/3165839/469bc1ba-d8c4-45bb-8fb5-602e541b02a9

Close #12360

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
I'm not sure if there is a way to test this behavior 😞 but I'm open to learn it in case you know

**Comment by BrunoQuaresma** [comment]
Unfortunately, Chrome and other browsers does not allow the script to change the warning message.

**Review by code-asher — COMMENTED** [review]
Nice change!

Yeah I thinking testing will be difficult.  Maybe Playwright can do it, it has a way to interact with dialogs.

Can we make it work for the back buttons too?  The one in the page and the browser back button.  I am not entirely sure how though, maybe we have to somehow hook into React navigation?

Some of the tests are failing.  It looks like they are trying to click on the build button but it is disabled, so it is probably the addition of `&& dirty` that is breaking them, I guess it is not getting set to `true` when the tests make their changes.

**Comment by BrunoQuaresma** [comment]
@code-asher 100% I'm going to work on the suggestions.

**Comment by BrunoQuaresma** [comment]
@code-asher I'm considering not adding e2e tests to this flow since it is a "nice to have" feature. Wdyt?

**Review by code-asher — APPROVED** [review]
Awesome!!  Works wonderfully.

**Pull request merged**
