### PR TITLE
feat(cli): Add `restart` subcommand

### LINKED ISSUE #2464: Add `coder restart` command
When the agent loses connection, users may see the message:

```
The workspace agent lost connection! Wait for it to reconnect or run: coder rebuild
```

This command doesn't exist, and requires `coder stop` followed by `coder start` at the moment.

Should this be added and called `rebuild` or something else? See #1376 about renaming start/stop.

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #2464

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
It'd be nice if this were implemented in the backend as a job type long-term... maybe we open an issue for it.

**Comment by mafredri** [comment]
> It'd be nice if this were implemented in the backend as a job type long-term... maybe we open an issue for it.

Oh yeah, why didn't I think of that, that's an awesome idea and makes perfect sense!

**Comment by mafredri** [comment]
@kylecarbs https://github.com/coder/coder/issues/5800

**Comment by kylecarbs** [comment]
Woot woot

**Pull request merged**
