### PR TITLE
fix: add postgres triggers to remove deleted users from user_links

### PR DESCRIPTION
**Pull request by Emyrk**
# What this does

- Removes ability to `un-delete` a user. We never exposed this outside the db layer, doing this to make that decision something that takes more thought than just changing an api param. 
- User_links should not longer exist for deleted users.

### CODE REVIEW

**Comment by Emyrk** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/coder/coder/12117?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* `main`
  * **#12111** <a href="https://app.graphite.dev/github/pr/coder/coder/12111?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **#12112** <a href="https://app.graphite.dev/github/pr/coder/coder/12112?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **#12117** <a href="https://app.graphite.dev/github/pr/coder/coder/12117?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Emyrk and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by kylecarbs** [comment]
Why are we removing the ability to undelete a user?

**Comment by Emyrk** [comment]
> Why are we removing the ability to undelete a user?

We never exposed this via the CLI or the API. It only exists in the DB query.

However, un-deleting a user is more work than just the query that I removed. It can now collide with existing users, their `user_links` were not correct, and now deleted. 

Essentially undeleting a user can cause issues (if it can succeed at all), so we never supported it. And we should remove the query that will very likely fail in prod.

**Comment by kylecarbs** [comment]
I know we never supported it, but it feels odd to keep the soft delete and a _real_ delete. Can we change it to completely do one or the other?

**Comment by Emyrk** [comment]
> I know we never supported it, but it feels odd to keep the soft delete and a _real_ delete. Can we change it to completely do one or the other?

We do not support hard deletes at all on most resources. For auditing purposes, we need to keep these objects around.

**Comment by kylecarbs** [comment]
@Emyrk I'm confused why we _should_ then on users. It seems like a fork in the road. It seems better to either leave this and not permit undeleting a user (e.g. actually blocking it), or making it work instead of allowing it for a single resource type.

**Comment by Emyrk** [comment]
I do not totally follow.

The product feature set is unchanged. We previously only supported soft deleting users from the API. I just made the DB query reflect this, so now **you cannot un-delete users** even from a DB query. So just trying to prevent developer error.

The `user_links` cleanup is because a deleted user should not be able to authenticate into Coder anymore. This becomes problematic if this is allowed because then a single github user can have multiple accounts linked to it. Maybe this is ok? Just felt strange from a data POV, so I implemented this to clean it up in the same way we do api keys.

**Review by kylecarbs — COMMENTED** [review]
Even though it is idiomatic with our data structure, I'm a bit nervous about having a term "soft delete" in one resource, even though I know we have it in others.

We've coined the term `deleted` as a soft-delete already. And since we called it `UpdateDeleted` I feel like it's a bit more confusing to call this `SoftDelete` now.

A few questions:

1. Can we just fix this in the Go code? Do we need to have the triggers added? It seems harder to test, and more spread complexity.
2. Is it alright if we continue to use `UpdateDeleted` instead of `SoftDelete`? Does my rationale make sense in this context?

**Comment by Emyrk** [comment]
> 2. Is it alright if we continue to use `UpdateDeleted` instead of `SoftDelete`? Does my rationale make sense in this context?

How about I return the name to `UpdateUserDeletedByID` but always make it do `deleted = true`? So there is no argument to ever revert the deleted state?

**Comment by kylecarbs** [comment]
That sounds good to me!

**Review by kylecarbs — APPROVED** [review]

**Pull request merged**
