### PR TITLE
feat: Update UI for error dialog and snackbar

### LINKED ISSUE #1832: UI: Confirmation Dialogs and Snackbar Notifs have an alarming red
## 👥 

suspend

- The red is _too red_
- The cancel action and main action are both _too red_ especially against an already _too red_ background
- The button spacing and border feels _tacky_

very-red

consider spacing the buttons apart so users don't click the wrong one, e.g:
Screen Shot 2022-05-27 at 12 44 54 PM

### PR DESCRIPTION
**Pull request by AbhineetJain**
This PR updates the alarmingly red UI for error dialog and snackbars.

## Subtasks

- [x] update the UI for error type dialog box
- [x] update the UI for error type snackbar

Fixes #1832 

## Screenshot

image

image

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
Can we make these buttons have the same height than the form buttons?

**Comment by BrunoQuaresma** [comment]
Also, adding some extra padding in the wrapper to looks closer to the Figma file.

**Comment by AbhineetJain** [comment]
> Can we make these buttons have the same height than the form buttons?

Sure, let me do that.

**Comment by AbhineetJain** [comment]
> Also, adding some extra padding in the wrapper to looks closer to the Figma file.

I realized I'll need changes in multiple places to update the other dialogs as well. Let me try those changes.

**Comment by AbhineetJain** [comment]
@BrunoQuaresma I updated the extra padding for `ConfirmDialog`, but the `ResetPasswordDialog` is differently styled. Should we update the formatting for that too?

**Review by greyscaled — APPROVED** [review]
Certainly looks like an improvement to me! @BrunoQuaresma's been doing a lot of re-design work lately (and is a fantastic designer :art:), I'm delegating review towards him.

Nice job y'all!

**Comment by Kira-Pilot** [comment]
Wow! Looking way better. I'll also defer to Bruno, but nice job!

**Review by BrunoQuaresma — APPROVED** [review]
LGTM! I think we should make the same for the Confirmation dialog and success alert as well but using the green color. @AbhineetJain what do you think? We probably can do it in another ticket or diff PR. Good job!

**Comment by AbhineetJain** [comment]
@BrunoQuaresma Sounds good, thank you! I'll create an issue for that, let's discuss it more there.

**Pull request merged**
