### PR TITLE
fix: Page header width in the workspace page

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix bug introduced on https://github.com/coder/coder/pull/2097

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
@Kira-Pilot what do you think about the way this calculates the page header width?

**Comment by BrunoQuaresma** [comment]
@Kira-Pilot what do you think about the way this calculates the page header width?

**Review by kylecarbs — APPROVED** [review]
LGTM

**Review by Kira-Pilot — APPROVED** [review]
I think this looks good! Eventually I would love to move away from hardcoded widths entirely (that 300px is my crime, i know) but I feel like that is a change to be handled later down the road.

**Pull request merged**
