### PR TITLE
feat: update licensing pills to reflect new premium tier

### LINKED ISSUE #14657: UI: update licensing pills to reflect new premium tier
## Summary
We are introducing a new licensing tier - "Premium" - and should update our licensing badges in the UI so that they appropriately communicate a feature's licensing level to the user.

## Background
We indicate licensing for specific features with pills, e.g. in the screenshot below, appearance configuration is an enterprise feature which is currently accessible to the user:
Screenshot 2024-09-12 at 4 12 50 PM

Alongside the `enterprise` pill we see an `entitled` pill which indicates whether or not a user has a valid license to use that feature as some (but not all) features may be administratively enabled or disabled at the deployment level. If a feature is both entitled and enabled, then it is used on the deployment.

After we GA orgs, we don't want to expose Enterprise as an available plan to OSS users as Premium will be our only paid tier going forward; however, we do need to retain an `enterprise` badge for existing Enterprise customers so that they may differentiate between features they have access to and features they don't (Premium features).

## Requirements

- [ ] First, let's remove all `entitled` badges from our UI. While the concept of entitlement are still valid within our product, we will find another way at another time to convey that meaning to users
- [ ] Create a badge component that accepts licensing info and toggle the label in that badge based on the below table:
```
                | enterprise feature | premium feature
premium license | 'premium'          |  'premium'
enterpr license | 'enterprise'       |  'premium'
no      license | 'premium'          |  'premium'
```

- [ ] Ensure the Premium badge state displays the appropriate licensing info tooltip (and documentation link!) on hover, e.g.
Screenshot 2024-09-12 at 4 22 37 PM
- [ ] Ensure there is *no* tooltip or documentation link on `Enterprise` badges as this concept will no longer exist in our documentation

### PR DESCRIPTION
**Pull request by jaaydenh**
resolves #14657

- [x] Remove all entitled badges from the UI
- [x]  Display Enterprise Badge for user with enterprise license for observability and appearance without showing a popover paywall tooltip.
- [x] Display Premium Badge for observability and appearance when the user has a premium license or no license. Display a popover paywall tooltip describing the feature.
- [x] Display a premium Badge for org creation if the user has a premium license and show a popover paywall tooltip.

### CODE REVIEW

**Comment by Parkreiner** [comment]
Extension of #14650

**Comment by aslilac** [comment]
I think some of the pills look a little weird being all by themselves, maybe we could move them onto the header lines when possible?

**Comment by jaaydenh** [comment]
@aslilac @chrifro Christin created a new design here for the beta label, https://www.figma.com/design/1bHJvrhzQNLnDqT3WRgqzn/organizations?node-id=0-1&t=ejGVc9VouNMkvmI5-1

So its looking like it makes more sense to keep the enterprise/premium badge where it is for now instead of moving it next to the new beta label.

**Review by aslilac — APPROVED** [review]
yeah, we can punt on that then

**Pull request merged**
