### PR TITLE
chore: set sessionAffinity to None in helm chart

### PR DESCRIPTION
**Pull request by ammario**

### CODE REVIEW

**Comment by ammario** [comment]
Current dependencies on/for this PR:
* main
  * **PR #9918** <a href="https://app.graphite.dev/github/pr/coder/coder/9918" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coder/coder/9918?utm_source=stack-comment).

**Review by deansheather — APPROVED** [review]

**Comment by ammario** [comment]
@deansheather — curious if you know why it was ClientIP at first? Was there a performance issue we were solving?

**Comment by deansheather** [comment]
> curious if you know why it was ClientIP at first? Was there a performance issue we were solving?

@ammario ClientIP avoids cases where requests to the same app will hit every single coder replica and cause each replica to have to stand up a connection to the workspace for the first time. It gets worse the more replicas you have

**Comment by ammario** [comment]
Ok. I do remember being that a problem in v1. I'll merge this now as I think the getting started experience not erroring on AWS is slightly more important.

**Pull request merged**
