### PR TITLE
adding link to install

### PR DESCRIPTION
**Pull request by endingwithali**

### CODE REVIEW

**Review by bpmct — CHANGES_REQUESTED** [review]
@endingwithali I made some changes in #3983 that attempts to address this.

While the install script will install system packages, this document aims to explain the more "manual" route where the user downloads it and installs it with `dpkg -i <coder.deb>`. 

However, these instructions are different for each operating system (Fedora is `rpm -i`). 

I suggest we either 
1. close this PR
2. Expand on step 1 says to "download and install" and explain what the specific commands are for each operating system.

What do you think?

**Comment by ghuntley** [comment]
> 2\. Expand on step 1 says to "download and install" and explain what the specific commands are for each operating system.

👍

**Comment by ghuntley** [comment]
> 2\. Expand on step 1 says to "download and install" and explain what the specific commands are for each operating system.

👍

**Comment by ghuntley** [comment]
Looks like this PR was superseded via https://github.com/coder/coder/pull/3983/files

**Pull request closed without merging**
