### PR TITLE
docs: align CODER_HTTP_ADDRESS with document

### PR DESCRIPTION
**Pull request by JounQin**
related #6228

https://github.com/coder/coder/blob/cfe35f54b4a3aa7fcb4d3ade8185d5d01b5d4add/docs/admin/configure.md?plain=1#L142

Actually these two environment variables are really confusing to me.

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
CODER_ADDRESS is deprecated anyways!

**Comment by JounQin** [comment]
https://github.com/search?q=repo%3Acoder%2Fcoder%20CODER_ADDRESS&type=code

@kylecarbs There seems are many legacy `CODER_ADDRESS` used, should we update them at the same time?

**Comment by JounQin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kylecarbs** [comment]
@JounQin seems reasonable to me!

**Comment by kylecarbs** [comment]
@JounQin oops, this auto-merged. Toss up another PR and I'll approve!

**Pull request merged**
