### PR TITLE
chore: update index

### LINKED ISSUE #2269: "Comparison" link on blog is broken
image

can we make this auto generated?

### PR DESCRIPTION
**Pull request by khorne3**
updates index.md, since about.md has been merged with README.md; updates a broken link

fixes https://github.com/coder/coder/issues/2269

### CODE REVIEW

**Review by jsjoeio — APPROVED** [review]
Thanks for fixing these!

**Comment by ammario** [comment]
This seems like dead code?

**Comment by jsjoeio** [comment]
> How is the index exposed to the user?

The `/docs/README.md` is rendered here: https://coder.com/docs/coder-oss/latest

**Comment by ammario** [comment]
@jsjoeio I updated that to point at the About page so there's no table of contents.

**Comment by khorne3** [comment]
Sorry for the delay -- I doubled-checked and used to be used for the homepage. I'll close this after making sure I don't need to update similar links elsewhere

**Pull request closed without merging**
