### PR TITLE
refactor: Remove login banner

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Solves https://github.com/coder/coder/issues/5232

Screen Shot 2022-12-01 at 16 40 40

### CODE REVIEW

**Review by code-asher — APPROVED** [review]
Looks good!  One thought I had was that we could leave out the Coder logo; to me it feels a little redundant since it is in the upper left corner as well.

**Comment by BrunoQuaresma** [comment]
@code-asher I think it is not. The Coder logo is only at the top of the message 🤔 I took a look at the Storybook to confirm. I'm not sure if I'm understanding it correctly.

**Comment by BrunoQuaresma** [comment]
@code-asher  Merging but I can send a PR right after with a fix if that is needed.

**Comment by code-asher** [comment]
Oh yup you are right!  I was looking at the Chromatic diff and thought it showed in two places but that was just the diff highlight showing it was gone.  :facepalm: My bad!

**Pull request merged**
