### PR TITLE
chore: update pqtype in go.mod

### PR DESCRIPTION
**Pull request by matifali**
`pqtype` has moved to https://github.com/sqlc-dev/pqtype from http://github.com/tabbed/pqtype.

See: https://github.com/coder/coder/network/updates/693763692 for details
image

### CODE REVIEW

**Comment by matifali** [comment]
Using the temporary workaround from https://github.com/kyleconroy/sqlc/issues/2417 until https://github.com/kyleconroy/sqlc/pull/2418 is available in the next sqlc release.

**Comment by matifali** [comment]
The workaround doesn't seem to work for us.

**Comment by andrewmbenton** [comment]
Hey just letting you all know that we released v1.19.1 about an hour ago which should resolve this issue. https://github.com/kyleconroy/sqlc/releases/tag/v1.19.1

**Comment by matifali** [comment]
closing in favor of #8511

**Pull request closed without merging**
