### PR TITLE
fix(site): reload page after setup is done

### LINKED ISSUE #6080: A refresh the coder server is needed after creating the first user to see Enterprise features
When you set up a new Coder deployment, you have to refresh the page to see the enterprise features.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Close https://github.com/coder/coder/issues/6080

### CODE REVIEW

**Review by buenos-nachos — APPROVED** [review]
Seems like a reasonable change!

**Comment by aslilac** [comment]
is there not a way for us to refetch/hydrate the state any other way? this feels a bit like a bandaid

**Comment by BrunoQuaresma** [comment]
> is there not a way for us to refetch/hydrate the state any other way? this feels a bit like a bandaid

There is but it is cumbersome IMO. In my mind to get this hydration we would need to:
- Refetch the entitlements data
- Replace the data in the metatag 
- Do these things before redirect

**Comment by BrunoQuaresma** [comment]
@aslilac  I think I found a better way! 👍

**Comment by BrunoQuaresma** [comment]
It does not fix the issue.

**Pull request closed without merging**
