### PR TITLE
chore: use correct anchor link on `scale.md`

### PR DESCRIPTION
**Pull request by dannykopping**
The correct anchor is https://coder.com/docs/v2/latest/admin/scale#scale-testing-utility

### CODE REVIEW

**Comment by dannykopping** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by matifali — APPROVED** [review]

**Review by mtojek — COMMENTED** [review]
Hey Danny! I see that linter complains about formatting. Could you please run `make fmt`? Thanks!

**Comment by dannykopping** [comment]
@mtojek done!

**Review by mtojek — APPROVED** [review]
Thank you 👍

**Pull request merged**
