### PR TITLE
ci: fix release notes compare link

### PR DESCRIPTION
**Pull request by bpmct**
Didn't really want to break anything but let me know if there's a better way to do this.

### CODE REVIEW

**Comment by mafredri** [comment]
@bpmct Nice catch! Looks like this is actually a bug in `release.yaml`. We should do e.g. `version="v$(./scripts/version.sh)"` instead of `version="$(./scripts/version.sh)"`.

**Review by mafredri — APPROVED** [review]
Pushed an alternate fix 👍🏻

**Comment by mafredri** [comment]
@bpmct went ahead and merged this so it'll be fixed in the next release 👍🏻

**Comment by bpmct** [comment]
Thanks!!

**Pull request merged**
