### PR TITLE
chore(site): make name bold in delete dialog

### PR DESCRIPTION
**Pull request by matifali**
This makes the name bold in delete dialog and makes it readable.
Screenshot 2023-09-24 at 03 30 55

Edit: Tests are passed. thanks @aslilac

### CODE REVIEW

**Comment by aslilac** [comment]
For the test just match on "Are you sure you want to proceed?" instead

**Comment by matifali** [comment]
@aslilac feel free to directly push to this branch and close it. It would be super helpful for me as I am busy with doing coder/modules lately.

**Comment by matifali** [comment]
I updated the test. Thanks for the suggestion.

**Review by BrunoQuaresma — APPROVED** [review]

**Comment by matifali** [comment]
### Merge Activity

* **Oct 2, 1:57 PM**: @matifali merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/9839).

**Pull request merged**
