### PR TITLE
chore: use latest code-server in examples

### PR DESCRIPTION
**Pull request by code-asher**
Instead, leave a comment describing how to pin the version.  This negates the need to continually update the version in this example, which has gotten quite out of date.

### CODE REVIEW

**Review by johnstcn — APPROVED** [review]

**Comment by matifali** [comment]
Nice. We should do it for all examples and doc examples. 👍🏼

**Comment by code-asher** [comment]
Oh wow yeah there are others.  Let me get them all.

**Comment by code-asher** [comment]
I think this is all of them.

**Review by matifali — COMMENTED** [review]
Awesome 😎

**Pull request merged**
