### PR TITLE
ci: migrate to depot.dev runners

### PR DESCRIPTION
**Pull request by matifali**
Saves cost while providing faster ci jobs.

~I may have missed a few buildjet runners.~
We can test it for a few days before canceling buildjet subscription.

### CODE REVIEW

**Review by ammario — APPROVED** [review]

**Review by deansheather — COMMENTED** [review]
Looks good

> I may have missed a few buildjet runners.

This needs to be verified before merge though

**Comment by matifali** [comment]
Holding for now as #13636 is flaking constantly on this PR.

**Comment by matifali** [comment]
Hi @ammario, can you or someone look at why `test-go` and `test-go-pg` are constantly failing only on depot.dev runners? We need to be sure if it's a flake or depot.dev issue. I've already raised this with support.

**Comment by matifali** [comment]
There is no haste to migrate and @johnstcn and @goller are looking into it. 
Meanwhile we can do a partial migration where these two jobs run on existing runners.

**Comment by johnstcn** [comment]
@matifali please rebase on main; I've merged https://github.com/coder/coder/issues/13636.

**Review by deansheather — APPROVED** [review]
LGTM. If we have any signs of issues though and we can't immediately figure out the cause, we can revert the PR to unblock

**Comment by matifali** [comment]
@deansheather I sent you an invite on depot.dev organization too just in case you need more context on these.

**Review by johnstcn — APPROVED** [review]

**Pull request merged**
