### PR TITLE
docs: add template to provision docker image based workspaces on fly.io 

### LINKED ISSUE #6446: Coder with Fly.io
Create an example template that creates workspaces as Fly.io machines + a blog post/tutorial on how to use Coder with Fly
  - Installing Coder dashboard on Fly
  - Importing the fly.io template
  - Creating a workspace
  - Cloning a project / extending the template, if needed

### PR DESCRIPTION
**Pull request by matifali**
This example provides a docker image-based workspace on fly.io using the code-server docker image.
- [x]  Create template
- [x]  Mount `fly_volume`
- [x]  Set a pretty `hostname`
- [x]  Add icons
- [x]  Use rich-params
- [x]  Use managed variables for `fly_org`
- [x]  Use count for `fly_machine`
- [x]  Test template on non fly coder deployment
		if we need a wireguard tunnel (Not needed) Only requirement is to set `FLY_AUTH_TOKEN` env variable on coder deployment.
- [x]  Add Readme

Partially resolves #6446 
This is the template part; provisioning Coder on fly.io will come as a separate blog post or may be in docs somewhere. Opinion is welcomed.

### CODE REVIEW

**Comment by matifali** [comment]
cc: @bpmct

**Comment by matifali** [comment]
Have you tested it?
Can you please test by pushing to a coder deployment.?
@bpmct

**Comment by bpmct** [comment]
@matifali i pushed those changes during testing. I may push more then will approve.

**Review by bpmct — APPROVED** [review]
Approved, just added some metadata. @BrunoQuaresma - what would it take to add this as a starter template?

EDIT: nvm, found it. Is there anything else I need to do?

**Pull request merged**
