### PR TITLE
feat: Add preferences pages

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
- Rename Panel to TabPanel to make it clear it is a "tabbed" panel
- Move Sidebar to TabPanel/TabSidebar since it is only used inside of TabPanel
- Updated sidebar to use NavLink instead of onClick events

Closes #746

### CODE REVIEW

**Review by presleyp — CHANGES_REQUESTED** [review]
Looks good! Can you take all the user-facing strings and put them in `Language` objects? There's an example in the SignInForm I believe.

**Review by greyscaled — CHANGES_REQUESTED** [review]
Can you merge latest main into this branch so that we get the Chromatic workflow to run

**Review by greyscaled — COMMENTED** [review]
Can you merge latest mainline again --> want to have chromatic rerun on this one and it will error if your branch is behind #910

**Review by greyscaled — COMMENTED** [review]
Last set of changes, everything looks great otherwise!

**Review by greyscaled — APPROVED** [review]

**Review by presleyp — APPROVED** [review]

**Pull request merged**
