### PR TITLE
feat: persist az linux vm example

### PR DESCRIPTION
**Pull request by ericpaulsen**
multiple customers have come to me asking to make this template persistent. after supporting them each, i think its best we make this change in the example.

### CODE REVIEW

**Review by matifali — COMMENTED** [review]
This is only making the `coder_agrnt` ephemeral. How does it make the vm persistent?

**Comment by matifali** [comment]
To make VM persistent and shutdown on workspace stop. It should look like something
```diff
resource "azurerm_linux_virtual_machine" "main" {
-  count               = data.coder_workspace.me.transition == "start" ? 1 : 0
```
and some logic to stop the VM using the `az` CLI. IIRC, Azure Terraform provider does not provide a way to stop the VM on demand.

**Comment by ericpaulsen** [comment]
@matifali - since the agent is ephemeral, i think its creating a new VM each time. here's the feedback from a customer:

>I’ve read through https://coder.com/docs/v2/latest/templates/resource-persistence and[ https://github.com/coder/coder/tree/main/examples/templates/azure-linux](https://github.com/coder/coder/tree/main/examples/templates/azure-linux), and[ https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine).
>
> We’re struggling to understand how to have the ‘Stop’ button on the Coder Workspace UI to ‘poweroff’ the VM. I had it working that it removed the VM, however this removes the OSdisk so any customisations the developer has made are lost. Do you have any experience of using Azure VMs as workspaces, and having effective stop/start for the workspace?
> 
> We’d like:
> 
> - Stopping the workspace to stop the costs associated with /running/ the VM
> - Stop and start to persist the OS disk and any attached disks

**Comment by matifali** [comment]
@ericpaulsen Yes. That's what I am saying. We also have a count set on `azurerm_linux_virtual_machine`, which is destroying the VM on each stop.

**Review by matifali — COMMENTED** [review]
now the VM is persistent and never stops. 

@matifali reviewed this PR from Slack with [Graphite](https://app.graphite.dev/github/pr/coder/coder/12618)

**Review by matifali — CHANGES_REQUESTED** [review]
@ericpaulsen The current template state will keep the VM running all the time and destroy it on workspace deletion only. Azure Terraform Provider does not support stopping a VM yet. See https://github.com/hashicorp/terraform-provider-azurerm/issues/22286.

**Pull request closed without merging**
