### PR TITLE
chore(site): upgrade storybook to v8

### LINKED ISSUE #12682: Upgrade Storybook to v8

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Closes https://github.com/coder/coder/issues/12682

### CODE REVIEW

**Review by aslilac — APPROVED** [review]
Yay!!! thank you for this!!

**Review by BrunoQuaresma — COMMENTED** [review]
This is blocked by https://github.com/storybookjs/storybook/issues/26239

**Comment by aslilac** [comment]
we don't use server components tho. it looks like it might be an issue with the react-router plugin we're using to me.

**Comment by aslilac** [comment]
https://github.com/JesusTheHun/storybook-addon-remix-react-router#readme

**Comment by BrunoQuaresma** [comment]
I tried that but didn't work. Let me push my changes,

**Comment by BrunoQuaresma** [comment]
@aslilac it stills failing on Chromatic as well 😢

**Comment by aslilac** [comment]
ok, that's unfortunate. 😅

**Pull request closed without merging**
