### PR TITLE
fix(cli): template pull tests: await template version job before exiting

### PR DESCRIPTION
**Pull request by johnstcn**
Seen here: https://github.com/coder/coder/actions/runs/6022883220/job/16338551690?pr=9421#step:5:354

Ignoring logger errors here as we have assertions on the template data to verify success.

### CODE REVIEW

**Comment by spikecurtis** [comment]
Ignoring logging errors is pretty broad.

Here what's going on is that we're closing down the test before the template version job is finished, and the provisioner is throwing an error.  If we wait for the job to finish, we shouldn't see an error if everything is working.

It's also maybe a little surprising to me that if you push a new template version and then immediately pull before the dry-run is complete, you get the new, possibly-failing version?

**Comment by johnstcn** [comment]
@spikecurtis I admit I went for the 'quick fix' here and not necessarily the correct one. Updated the tests to await template version job.

**Comment by mafredri** [comment]
> It's also maybe a little surprising to me that if you push a new template version and then immediately pull before the dry-run is complete, you get the new, possibly-failing version?

Not sure whether or not that is a bug or if it's part of a separate issue that we, by default, return failed builds. This is also visible in the dashboard where you can use the template editor, have a syntax error -> failed build, and that new version will show up in the list.

**Review by mafredri — APPROVED** [review]
To me this looks like the appropriate fix for these tests. We might want to separately test what happens on failure though, but I think that's a separate issue.

**Pull request merged**
