### PR TITLE
feat: Update CLI to handle managed variables

### PR DESCRIPTION
**Pull request by mtojek**
Related: https://github.com/coder/coder/issues/5980

This PR extends the CLI commands `create` and `push` to let user pass the `variables.yml` file with Terraform variable values.

Extra changes:
1. API `/variables`: redact value and default value for sensitive parameters.
2. Fix: variable is marked as required if `variable.default == nil` not just `variable.default == ""`.

Testing:

```bash
./scripts/coder-dev.sh templates create docker-rich-2 -d mtojek/docker-rich --variables-file values.yml

./scripts/coder-dev.sh templates push docker-2 -d mtojek/docker-rich --variables-file values.yml

./scripts/coder-dev.sh templates push docker-2 -d mtojek/docker-rich --variable aaa=bbb
```
----

- [x] Use `variables` file to pass initial values for the new template
- [x] Pull variable values from the active template, so that user doesn't have to pass them again
- [x] Write unit tests

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
Looks good.

I think users could confuse the help of `variables-file` and `parameters-file`, maybe that's something to look at before merge.

**Comment by mtojek** [comment]
The original form:

> Specify a file path with values for managed variables.

It's hard to figure out a good description as we don't invent anything new. These are just Terraform variables. A couple of ideas:

> Specify a file path with values for Terraform-managed variables.

> Specify a file path with Terraform variable values for the template.

> Specify a file path with template-wide Terraform variables.

Any preference here, @kylecarbs @bpmct? The task will be harder once we replace the Terraform with something else.

**Comment by kylecarbs** [comment]
I like "Specify a file path with values for Terraform-managed variables."!

**Review by bpmct — COMMENTED** [review]
Any plans to support something like `TF_VAR=`, `-var`, or `--set` as well?

In a CI pipeline when a new image is pushed, how could we set that output (`ami-21912383`) as a variable when a Coder template update is also pushed as the next step in the pipeline? Writing to a file and then referencing is a strange workaround.

**Comment by mtojek** [comment]
> Writing to a file and then referencing is a strange workaround.

Yes, it depends. If you have multiple variables, you need to reference then a file would be more convenient. Same with sensitive values, you don't want somebody to sniff them via `ps aux`.

I can add an extra command option (`--variable "name=value"`) to pass more variables, but I wouldn't limit it to `TF_VAR` in case we'd like to support different provisioners. What do you think?

**Comment by bpmct** [comment]
> Anyway, I can add an extra command option (--variable "name=value") to pass more variables, but I wouldn't limit it to TF_VAR in case we'd like to support different provisioners. What do you think?

Sounds fair 👍🏼

**Comment by mtojek** [comment]
Done!

**Pull request merged**
