### PR TITLE
cleanup workspace machine

### PR DESCRIPTION
**Pull request by Kira-Pilot**
We shouldn't send events from actions! This refactor fixes our workspace machine.

### CODE REVIEW

**Comment by presleyp** [comment]
Screen Shot 2022-09-22 at 4 40 42 PM
I don't see a reason to nest `idle` inside `loadedBuilds`. It's just one state. Also, I'm concerned that we have a state called `idle` that has no outgoing arrows. I'm not sure what the best resolution is (do we want to be able to retry? was it intended to lead to the other `idle`?).

**Comment by presleyp** [comment]
Screen Shot 2022-09-22 at 4 55 20 PM
There are two `refreshingTemplate` states, one at the top level, and one inside the `build` submachine. The inner one has no incoming arrows, so I don't think it will ever happen. Not sure if it should happen or just needs to be cleaned up.

**Comment by presleyp** [comment]
Okay I'm a jerk for not telling you this before but, despite the "don't `send` in an action" rule, there is a [`send` action](https://xstate.js.org/docs/guides/actions.html#send-action), which gets around the rule because it's one of those special pure actions that the interpreter knows what to do with. I'm noticing that we're sending `REFRESH_TIMELINE` every time we go into `build.idle`. Putting `send`s inside of services makes it less obvious that they're happening (like, they don't show up on the diagram) and doesn't capture that pattern.

So I'm wondering if we can add an `entry` action to `build.idle` to `send` (this is imported from xstate, like `assign`) `REFRESH_TIMELINE`. I'm also wondering if we really do want to refresh the timeline whether the service succeeds or fails. If we don't want to do it in case of failure, I'm not sure we can make actions conditional the way we can make transitions conditional with guards. So in that case I might just add the `send` action to the end of the action lists for each `onDone`. At least that way we can see in the diagram that they exist.

**Comment by Kira-Pilot** [comment]
> I don't see a reason to nest `idle` inside `loadedBuilds`. It's just one state. Also, I'm concerned that we have a state called `idle` that has no outgoing arrows. I'm not sure what the best resolution is (do we want to be able to retry? was it intended to lead to the other `idle`?).

Sure, I can take `idle` out of `loadedBuilds`.

Regarding the second idle (the one we transition to after error): I think perhaps it would be best to get rid of that and, in the case of an error, transition right back to `loadedBuilds`. This will give the user to ability to retry loading timeline. In the future, if we want to build a more concrete UI around the error case, we can. 

The machine will be simplified like:
Screen Shot 2022-09-23 at 10 29 00 AM

**Comment by Kira-Pilot** [comment]
> If we don't want to do it in case of failure, I'm not sure we can make actions conditional the way we can make transitions conditional with guards. So in that case I might just add the `send` action to the end of the action lists for each `onDone`. At least that way we can see in the diagram that they exist.

I'm a fan of this approach but I'm having a hard time using that `send` action pattern within an invoke:

Screen Shot 2022-09-23 at 11 04 33 AM

**Comment by Kira-Pilot** [comment]
> There are two `refreshingTemplate` states, one at the top level, and one inside the `build` submachine. The inner one has no incoming arrows, so I don't think it will ever happen. Not sure if it should happen or just needs to be cleaned up.

I can clean this up. I got rid of the stale one, and renamed the other one to `getTemplate` since we aren't refreshing.

**Review by presleyp — APPROVED** [review]
I'm out today so I'm unblocking this, you'll make great decisions!

**Pull request merged**
