### PR TITLE
refactor(scripts): use ln -P on non-darwin arch

### LINKED ISSUE #2738: Warn user's when running make build locally
## Problem

I was developing coder locally on my macOS (Intel) and ran into issues with the `make build` script. Specifically, this error:

```shell
--- Creating archive for linux amd64 (/Users/jp/dev/coder/coder/dist/coder_0.7.6-devel+4f3202d9_linux_amd64.tar.gz)
a ./LICENSE
a ./README.md
a ./coder
/Users/jp/dev/coder/coder/dist/coder_0.7.6-devel+4f3202d9_linux_amd64.tar.gz


ln: illegal option -- P
usage: ln [-Ffhinsv] source_file [link_name]
       ln [-Ffhinsv] source_file ... linkname_dir
       link source_file link_name
make: *** [Makefile:34: build] Error 1
```

I believe we use `ln -P` in one place

https://github.com/coder/coder/blob/9bdaec6a2113c4c318f419d674e213d1b116c1b7/scripts/package.sh#L71-L75

## Solution

I see two solutions to fixing this problem.

### Option 1

Only pass `-P` on Linux-based OS's. It seems it's not [needed for macOS](https://ss64.com/osx/ln.html).

### Option 2

In scripts, check for an environment variable like `CI=1` and hard exit script with warning if not set.

### PR DESCRIPTION
**Pull request by jsjoeio**
Fixes https://github.com/coder/coder/issues/2738

### CODE REVIEW

**Review by deansheather — COMMENTED** [review]
I actually don't think we need the `-P` at all on either platform. Could you just remove the `-P` entirely instead?

**Review by deansheather — APPROVED** [review]
if they still work on linux and darwin 👍

**Comment by jsjoeio** [comment]
> if they still work on linux and darwin 👍

Now I'm doubting myself 😂 Let me run `make build` and check.

**Comment by jsjoeio** [comment]
Looks good to me 👍🏼

**Pull request merged**
