### PR TITLE
fix: add copy fallback for insecure contexts

### LINKED ISSUE #1601: Copy to clipboard button in `/cli-auth` doesn't work when running on non-local (rPi) machine over HTTP
## OS Information

- OS: macOS
- Browser (if applicable): Safari
- `coder --version`: Coder v0.0.0-devel+6c11170 Thu May 19 18:04:44 UTC 2022 https://github.com/coder/coder/commit/6c1117094d78192c6f13a2336597cedc188eb028

## Steps to Reproduce

1. Run server on Raspberry Pi (`aarch64`): `coder server --dev --address 0.0.0.0:7080 --access-url http://0.0.0.0:3000`
2. Open `http://pi.my.domain:7080/cli-auth`
3. Login
4. Press Copy-to-clipboard button

## Expected

Copy to clipboard works or shows an error suggesting a manual copy.

## Actual

Token is not copied to clipboard, and no error indicating that it didn't work.

Browser console shows the following error:

```
[Error] Error: copyToClipboard: failed to copy text to clipboard — bundle.13f11ac8daaa8228db0b.js:2:537210
	(anonymous function) (bundle.13f11ac8daaa8228db0b.js:2:537315)
	(anonymous function) (bundle.13f11ac8daaa8228db0b.js:2:536870)
	(anonymous function) (bundle.13f11ac8daaa8228db0b.js:2:537615)
	Promise
	onClick (bundle.13f11ac8daaa8228db0b.js:2:537375)
	$e (bundle.13f11ac8daaa8228db0b.js:2:184959)
	Ke (bundle.13f11ac8daaa8228db0b.js:2:185113)
	(anonymous function) (bundle.13f11ac8daaa8228db0b.js:2:203291)
	Tr (bundle.13f11ac8daaa8228db0b.js:2:203380)
	_r (bundle.13f11ac8daaa8228db0b.js:2:203796)
	(anonymous function) (bundle.13f11ac8daaa8228db0b.js:2:209419)
	je (bundle.13f11ac8daaa8228db0b.js:2:284650)
	(anonymous function) (bundle.13f11ac8daaa8228db0b.js:2:205252)
	Ar (bundle.13f11ac8daaa8228db0b.js:2:205280)
	Qt (bundle.13f11ac8daaa8228db0b.js:2:193358)
	Yt (bundle.13f11ac8daaa8228db0b.js:2:192584)
	Yt
	(anonymous function) (bundle.13f11ac8daaa8228db0b.js:2:308128)
	Ze (bundle.13f11ac8daaa8228db0b.js:2:284391)
	qt (bundle.13f11ac8daaa8228db0b.js:2:192377)
	qt
```

## Screenshot

image

## Notes

There is probably some content security issue involved here, but haven't investigated further.

### PR DESCRIPTION
**Pull request by oxy**
This PR adds a clipboard copy fallback for insecure contexts.

## Subtasks

- [x] added fallback

Fixes #1601

### CODE REVIEW

**Review by greyscaled — APPROVED** [review]
🙌🏻

**Comment by vapurrmaid** [comment]
I'm wondering if @mafredri can help us test :D

**Review by mafredri — COMMENTED** [review]
I tried this out and it doesn't seem to do anything on any of my browsers (Safari, Firefox, Brave). It also doesn't log anything in the console which would indicate `result === true`.

Perhaps `input.hidden = true` can't be selected? What if we use CSS to hide it instead?

PS. Thanks for taking a stab at fixing this @oxy!

**Review by mafredri — APPROVED** [review]
Works now, awesome! 😎

**Pull request merged**
