### PR TITLE
feat: allow configurable username claim field in OIDC

### PR DESCRIPTION
**Pull request by janLo**
Gitlab does not set the preferred_username field.

Therefore, coder generates something from the user's email address, which is not very helpful. This allows the administrator to change the field used for the username (e.g. to "nickname")

### CODE REVIEW

**Comment by janLo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by janLo** [comment]
@whitney-coder as requested I tag you here. This would really help everyone trying to use gitlab as opened connect provider. As they use the nickname claim to publish the username: https://gitlab.com/gitlab-org/gitlab/-/blob/master/config/initializers/doorkeeper_openid_connect.rb#L35

**Comment by whitney-coder** [comment]
@bpmct tagging you here to get your eyes/thoughts on this!

**Review by coadler — APPROVED** [review]
Looks good to me! You'll have to run `make update-golden-files` to update the CLI golden file.

**Comment by janLo** [comment]
Oh that printf slipped through, I'll fix this as soon as I'm on my laptop again. 

I just couldn't get this make target to run that's why I've manually created the change for the golden file.

**Comment by janLo** [comment]
@coadler I've removed the printf. If I try to generate the golden files I get this:

~~~
% make update-golden-files
--- FAIL: TestCommandHelp (0.00s)
    --- FAIL: TestCommandHelp/coder_--help (0.00s)
panic: testing: t.Setenv called after t.Parallel; cannot set environment variables in parallel tests [recovered]
        panic: testing: t.Setenv called after t.Parallel; cannot set environment variables in parallel tests

goroutine 9 [running]:
testing.tRunner.func1.2({0x1cc1fa0, 0x24e0b00})
        /home/losinski/.go_sdk/go1.20rc1/src/testing/testing.go:1525 +0x24e
testing.tRunner.func1()
        /home/losinski/.go_sdk/go1.20rc1/src/testing/testing.go:1528 +0x39f
panic({0x1cc1fa0, 0x24e0b00})
        /home/losinski/.go_sdk/go1.20rc1/src/runtime/panic.go:884 +0x213
testing.(*T).Setenv(0x1d81080?, {0xc0000610b0?, 0xc0000610b0?}, {0x0?, 0x0?})
        /home/losinski/.go_sdk/go1.20rc1/src/testing/testing.go:1415 +0x68
github.com/coder/coder/cli_test.TestCommandHelp.func1(0xc00044c820)
        /home/losinski/devel/coder/cli/root_test.go:92 +0x350
testing.tRunner(0xc00044c820, 0xc000fb2500)
        /home/losinski/.go_sdk/go1.20rc1/src/testing/testing.go:1575 +0x10b
created by testing.(*T).Run
        /home/losinski/.go_sdk/go1.20rc1/src/testing/testing.go:1628 +0x3ea
FAIL    github.com/coder/coder/cli      0.131s
FAIL
make: *** [Makefile:478: cli/testdata/.gen-golden] Fehler 1

~~~

**Comment by janLo** [comment]
@coadler is there anyhing I can do?

**Comment by coadler** [comment]
@janLo do you mind if I push to your branch to fix the CI failures?

**Comment by janLo** [comment]
> @janLo do you mind if I push to your branch to fix the CI failures?

Not at all! Thank you!

**Comment by coadler** [comment]
Thanks! :tada:

**Pull request merged**
