### PR TITLE
chore: upgrade Go version to 1.22.4

### PR DESCRIPTION
**Pull request by johnstcn**
~Note: nix flake is failing to update (maybe due to go 1.22.4 not being in nix pkgs at time of writing?)~ EDIT: fixed, I just don't know how to nix.

### CODE REVIEW

**Comment by matifali** [comment]
Some missing places:
1. https://github.com/coder/coder/blob/56d3ebc03ea8262196f7150d9d9979e82b0ee859/.github/actions/setup-go/action.yaml#L7
2. https://github.com/coder/coder/blob/56d3ebc03ea8262196f7150d9d9979e82b0ee859/.github/workflows/ci.yaml#L262 This was running fmt check with go 1.21, we should perhaps use the common setup-go action and enable caching again. It will make little difference.

**Comment by matifali** [comment]
> Note: nix flake is failing to update (maybe due to go 1.22.4 not being in nix pkgs at time of writing?)

go 1.22.4 should be available. https://github.com/NixOS/nixpkgs/pull/317326

**Comment by johnstcn** [comment]
> > Note: nix flake is failing to update (maybe due to go 1.22.4 not being in nix pkgs at time of writing?)
> 
> go 1.22.4 should be available. [NixOS/nixpkgs#317326](https://github.com/NixOS/nixpkgs/pull/317326)

It still shows up as the older version for me here: https://search.nixos.org/packages?channel=unstable&show=go&from=0&size=50&sort=relevance&type=packages&query=go

I figure it's just a matter of time though.

**Comment by matifali** [comment]
@johnstcn May be we need to run [`nix flake update`](https://nix.dev/manual/nix/2.22/command-ref/new-cli/nix3-flake-update)

**Comment by matifali** [comment]
@johnstcn I ran the `./scripts/update-flake.sh` on an amd64 desktop, and now the hash matches.

**Review by matifali — APPROVED** [review]

**Review by kylecarbs — APPROVED** [review]

**Pull request merged**
