### PR TITLE
feat: add version to footer

### PR DESCRIPTION
**Pull request by code-asher**
version

### CODE REVIEW

**Review by kylecarbs — CHANGES_REQUESTED** [review]
Go side looks good to me. Just a few minor things! 😎

**Review by greyscaled — COMMENTED** [review]
This looks great to me. Had some fairly low-key suggestions around conditionally rendering and using a function to construct the version string; nothing major.

Am going to look out for @presleyp 's review to see if there's any suggestions on the xService or global context 🙌🏻 .

**Review by kylecarbs — APPROVED** [review]
LGTM! Nice change.

**Review by greyscaled — CHANGES_REQUESTED** [review]
Can you merge latest main into this branch so that we get the Chromatic workflow to run

**Review by greyscaled — APPROVED** [review]
Nicely done!

**Review by presleyp — APPROVED** [review]

**Pull request merged**
