### PR TITLE
chore: add ui as dashboard synonym

### PR DESCRIPTION
**Pull request by mreadie**

### CODE REVIEW

**Comment by mreadie** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matifali** [comment]
Hi @mreadie you need to add your commiter email to your GitHub account.

**Comment by mreadie** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mreadie** [comment]
Fixed my committer email and reaccepted the CLA.

**Review by stirby — APPROVED** [review]
Nice

**Review by matifali — APPROVED** [review]

**Pull request merged**
