### PR TITLE
fix!: remove jq from image

### PR DESCRIPTION
**Pull request by ericpaulsen**
this PR removes `jq` from our base image. it also adds a `Dockerfile.ext-jq` file, in case we want to publish secondary images with specific packages.

i'll let y'all decide whether this is necessary. let me know if i missed any steps.

### CODE REVIEW

**Comment by ericpaulsen** [comment]
closing out, as we will discuss internally whether to keep `jq`.

**Comment by bpmct** [comment]
I suggest we remove this since Coder doesn't rely on this specifically.

**Comment by matifali** [comment]
Do we need to provide a new image with `jq` too?

**Comment by bpmct** [comment]
No that's ok. Our users can extend our image to include `jq`.

**Review by deansheather — APPROVED** [review]

**Pull request merged**
