### PR TITLE
fix: Enable CGO for darwin builds

### LINKED ISSUE #4097: Coder not using MacOS name resolution mechanism
When using VPN such as tailscale it updates nameserver without updating resolv.conf.

Most processes resolve just fine but coder seems to have problems.

E.g. When trying to use coder login:

```
coder login https://REDACTED.REDACTED.ts.net
Failed to check server "https://REDACTED.REDACTED.ts.net" for first user, is the URL correct and is coder accessible from your browser? Error - has initial user: do: Get "https://REDACTED.REDACTED.ts.net/api/v2/users/first": dial tcp: lookup REDACTED.REDACTED.ts.net on 8.8.8.8:53: no such host
Run 'coder login --help' for usage.
```

When using other tools. E.g. ping:

```
> ping REDACTED.REDACTED.ts.net

PING REDACTED.REDACTED.ts.net (100.85.22.44): 56 data bytes
64 bytes from 100.85.22.44: icmp_seq=0 ttl=64 time=45.126 ms
64 bytes from 100.85.22.44: icmp_seq=1 ttl=64 time=48.419 ms
```

E.g. curl:

```
> curl https://REDACTED.REDACTED.ts.net

<!doctype html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#17172E"/><meta name="application-name" content="Coder"/><meta property="og:type" content="website"/><meta property="csp-nonce" content=""/><meta property="csrf-token" content="J9Ag5EQDay6wx8VAWewJvzwirdYakOq3x9QdxB+uocyb/OU5inQF8iJ7nVbO7SwAbnBWPeR75o6LMiQCs42mRg=="/><meta id="api-response" data-statuscode="0" data-message=""/><link rel="alternate icon" type="image/png" href="/favicons/favicon.png" data-react-helmet="true"/><link rel="icon" type="image/svg+xml" href="/favicons/favicon.svg" data-react-helmet="true"/><script defer="defer" src="/bundle.809524c30b22690bf571.js"></script><link href="/main.6978d5569b46e6b28654.css" rel="stylesheet"></head><body><div id="root"></div></body>%
```

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #4097.

### CODE REVIEW

**Comment by kylecarbs** [comment]
Realized this won't work because we use a Linux runner!

**Comment by deansheather** [comment]
Yep...

**Comment by dcarrion87** [comment]
@kylecarbs is this one likely to go through or are we better off maintaining this ourselves as a separate binary?

**Comment by kylecarbs** [comment]
@dcarrion87 our current CI setup won't permit this very easily, but we could change to run on macOS runners with relative ease I believe once we build Docker images externally (which we're doing soon).

I'd say maintain it for now in the short-term, but we'll certainly fix this. It's unacceptable that users can't use their tailnets!

**Pull request closed without merging**
