### PR TITLE
docs: add RStudio community template without requiring a subdomain

### PR DESCRIPTION
**Pull request by atnomoverflow**

### CODE REVIEW

**Comment by atnomoverflow** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by atnomoverflow** [comment]
---

I have read the CLA Document and I hereby sign the CLA

---

**Comment by atnomoverflow** [comment]
recheck

**Comment by atnomoverflow** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/coder/cla/blob/main/README.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

> 
> I have read the CLA Document and I hereby sign the CLA
>

**Comment by coadler** [comment]
@atnomoverflow You need to comment just `I have read the CLA Document and I hereby sign the CLA` and nothing else!

**Comment by atnomoverflow** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matifali** [comment]
Hi @atnomoverflow, Thanks for the contribution. The `fmt` test is failing, Is it ok if I format by pushing directly to the branch?

**Review by matifali — APPROVED** [review]

**Pull request merged**
