### PR TITLE
feat: Add update user password endpoint

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Closes #1309

### CODE REVIEW

**Review by f0ssel — CHANGES_REQUESTED** [review]

**Review by f0ssel — COMMENTED** [review]
Do we not have an RBAC gate for admins yet? Kinda worried about shipping this and allow any user to reset any other user's password.

**Review by mafredri — COMMENTED** [review]
Just a few nits, other than that I think the PR looks good. 👍🏻

**Review by presleyp — APPROVED** [review]
The frontend bit looks good to me!

**Review by f0ssel — APPROVED** [review]
Small suggestions but it looks good 👍

**Pull request merged**
