### PR TITLE
docs: show the proper Redirect URI for Gitea

### PR DESCRIPTION
**Pull request by idleite**

### CODE REVIEW

**Comment by Idleite** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Idleite** [comment]
recheck

**Review by kylecarbs — APPROVED** [review]
Thank you!

Could you add a new line before the header?

**Comment by Idleite** [comment]
Like this?

**Comment by matifali** [comment]
@Idleite Please run `make fmt` too.

**Comment by Idleite** [comment]
make fmt

**Pull request merged**
