### PR TITLE
feat: support `order` property of `coder_app` resource

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/8994

This PR adjusts logic to sort `coder_app`s to preserve predefined order. Only custom apps are sorted, VS Code and Terminal stay as is. 

Screenshot 2024-02-12 at 14 00 49

### CODE REVIEW

**Comment by matifali** [comment]
@mtojek How will it affect the [bultin coder_apps](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#display_apps)? Is the order controllable for them?

**Comment by mtojek** [comment]
You can only control custom ones, so it would be:

1. VS Code _buttons..._
2. _Custom apps_ sorted by order
3. _Terminal_.

I can move Terminal to the 2nd position so that custom apps are aside. I'm happy to modify this idea if you have any proposals.

**Comment by matifali** [comment]
Sounds good. I think there is no need to change anything.

**Review by johnstcn — APPROVED** [review]
LGTM

**Pull request merged**
