### PR TITLE
fix: 'coder update' should always start a workspace

### LINKED ISSUE #6336: bug: `coder update <workspace> --always-prompt` does not start the workspace
version `v0.17.4-devel+16363fd1`

running `coder update <workspace> --always-prompt` correctly prompts me to reset my terraform variables and re-initializes terraform.

however, navigating back to the UI shows the workspace still in a `Stopped` state. note that the prior state was an auto-shutoff by Coder:

Screenshot 2023-02-23 at 6 07 27 PM

[this code](https://github.com/coder/coder/blob/282507f0fb2a900f3c0fa651c59de70da3683864/cli/update.go#L71-L72) suggests that the workspace transition leverages the state of the latest build.

### PR DESCRIPTION
**Pull request by Emyrk**
fixes https://github.com/coder/coder/issues/6336

### CODE REVIEW

**Review by mtojek — CHANGES_REQUESTED** [review]
I'm afraid that you've to regenerate .golden files.

**Comment by Emyrk** [comment]
> I'm afraid that you've to regenerate .golden files.

Ahh, so `make gen` does not regen golden files.
I wonder if it should?

**Comment by Emyrk** [comment]
Golden files updated

**Review by mtojek — APPROVED** [review]

**Comment by mafredri** [comment]
> >  I'm afraid that you've to regenerate .golden files.
> 
> Ahh, so make gen does not regen golden files.
> 
> I wonder if it should?
> 
> 
> 
> @mafredri Do you know if this is intentional or is it possible to include this target in `make gen`?

It is intentional, originally it was made part of gen but it was considered that it'd be too easy to `make gen; git add .` without reviewing the changes. I have no strong personal preference but have found it would be a bit more convenient if it was part of gen.

**Comment by Emyrk** [comment]
that is fair. I am ok with it :+1:

**Pull request merged**
