### PR TITLE
feat(site): generates unique workspace names by default

### PR DESCRIPTION
**Pull request by BrunoQuaresma**

### CODE REVIEW

**Review by matifali — APPROVED** [review]
I think its a good addition

**Review by matifali — APPROVED** [review]
@matifali approved this PR from Slack with [Graphite](https://app.graphite.dev/github/pr/coder/coder/11772)

**Review by mtojek — DISMISSED** [review]
It looks like E2E and regular TS tests are failing.

**Comment by BrunoQuaresma** [comment]
Related to https://github.com/coder/coder/issues/11742

**Pull request merged**
