### PR TITLE
feat(site): make workspace batch deletion GA

### PR DESCRIPTION
**Pull request by BrunoQuaresma**

### CODE REVIEW

**Review by bpmct — COMMENTED** [review]
Nice! We're making this an enterprise feature, right? If so, can you also update the enterprise docs: https://coder.com/docs/v2/latest/enterprise and add a basic section on the workspaces page?

**Comment by BrunoQuaresma** [comment]
@bpmct good call!

**Comment by matifali** [comment]
Don't you think we should add other actions star/stop/restart/update before making it GA?
Or we should call it **batch deletion**. 

Another issue is it can't delete failed workspaces and that is currently not possible from the dashboard.

**Comment by bpmct** [comment]
(just testing the deploy PR haha, not actually reviewing the functionality)

**Review by aslilac — APPROVED** [review]

**Review by matifali — APPROVED** [review]
I am ok with this. I have one feedback that you are free to disregard. 
Can we hide the check boxes by default?
Similar to how Gmail does this?
Showing empty check boxes all the time is taking extra space.

**Comment by BrunoQuaresma** [comment]
@matifali for me, it is always displayed, otherwise how could the user select the workspace? 🤔 
Screen Shot 2023-08-30 at 10 06 59

**Pull request merged**
