### PR TITLE
Allow changing db schema from public

### LINKED ISSUE #4747: Allow changing db schema from `public`
# Problem

When creating our initial migration to bootstrap the database, we hard-code the schema name to public.

# Solution

Do not set the schema name at all in the initial bootstrap script.
Allow this to be overridden via search_path in the connection string.

https://www.postgresql.org/docs/current/runtime-config-client.html

## Private Link

V1 PR: https://github.com/coder/v1/pull/13216
v1 Issue: https://github.com/coder/v1/issues/13040

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/4747

This PR removes hard-coded references to the `public` schema, which prevents users from predefining their own schemas. As the application depends on the connection string, I suppose that it doesn't need an extra ENV var (like `DB_SEARCH_STRING` in https://github.com/coder/v1/pull/13216) to provide the `search_path`.

### CODE REVIEW

**Comment by mtojek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mtojek** [comment]
recheck

**Comment by mtojek** [comment]
recheck

**Comment by mtojek** [comment]
Hey @mafredri! Could you please take a look at this draft PR to check if I don't miss anything?

**Comment by mafredri** [comment]
There seems to be one more case of `public.` left in `dump.sql`:

```
coderd/database/dump.sql
215:ALTER SEQUENCE licenses_id_seq OWNED BY public.licenses.id;
463:ALTER TABLE ONLY licenses ALTER COLUMN id SET DEFAULT nextval('public.licenses_id_seq'::regclass);
```

But other than that, looks great!

If you want to take a stab at documenting how to use this feature, there's an issue (that got closed by stale bot) to improve the documentation for setting up PostgreSQL: https://github.com/coder/coder/issues/3508

**Comment by mtojek** [comment]
> There seems to be one more case of public. left in dump.sql:

Good catch, @mafredri!

**Review by mafredri — APPROVED** [review]
Nice, looks good to me!

**Review by coadler — APPROVED** [review]
:tada:

**Pull request merged**
