### PR TITLE
feat: add lazygit, remove kubic, use dotfiles in dogfood image

### PR DESCRIPTION
**Pull request by jsjoeio**
## Changes

This adds [lazygit](https://github.com/jesseduffield/lazygit) to the dogfood image.

This also uses the `coder dotfiles` command in the `startup_script`.

### CODE REVIEW

**Review by ghuntley — COMMENTED** [review]
LGTM.

Not sure why dogfood is failing // going to rerun it // installing LG does indeed work.

```
coder@coder-sydney:~$ sudo bash
root@coder-sydney:/home/coder# LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/') && \
>   curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && \
>   tar xf lazygit.tar.gz -C /usr/local/bin lazygit
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5445k  100 5445k    0     0  3033k      0  0:00:01  0:00:01 --:--:--  107M
root@coder-sydney:/home/coder# echo $LAZYGIT_VERSION  
0.36.0
```

**Comment by ghuntley** [comment]
Rebased off `main` and starting CI again.

**Comment by ghuntley** [comment]
Dogfood on main is broken

```
#0 1.916 Get:31 https://apt.postgresql.org/pub/repos/apt focal-pgdg/main amd64 Packages [417 kB]
#0 2.120 Get:32 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2350 kB]
#0 2.288 Get:33 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [972 kB]
#0 2.349 Get:34 https://ppa.launchpadcontent.net/ansible/ansible/ubuntu focal/main amd64 Packages [1086 B]
#0 2.937 Get:35 https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu focal/main amd64 Packages [1943 B]
#0 5.207 Get:36 http://mirror.pit.teraswitch.com/ubuntu focal-updates/universe amd64 Packages [1273 kB]
#0 5.345 Get:37 http://mirror.pit.teraswitch.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
#0 5.347 Get:38 http://mirror.pit.teraswitch.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
#0 5.505 Reading package lists...
#0 6.614 E: The repository 'https://plug-mirror.rcac.purdue.edu/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' does not have a Release file.
```

**Comment by jsjoeio** [comment]
Last commit is based off: https://github.com/coder/v1/pull/13438

**Review by johnstcn — APPROVED** [review]

**Pull request merged**
