### PR TITLE
docs: fix broken templates_init table

### PR DESCRIPTION
**Pull request by andreafalzetti**
Fixing broken markdown

| Before | After |
|--------|-------|
|     Screenshot 2023-08-04 at 19 54 00   |  Screenshot 2023-08-04 at 19 53 43     |

### CODE REVIEW

**Comment by andreafalzetti** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by andreafalzetti** [comment]
recheck

**Comment by andreafalzetti** [comment]
recheck

**Comment by matifali** [comment]
Hi @andreafalzetti this is an autogenerated file and will be overwritten automatically

**Comment by matifali** [comment]
Thank you for bringing this to attention. We will fix this. 
cc: @bpmct

**Pull request closed without merging**
