### PR TITLE
feat(cli): add template filter support to exp scaletest cleanup and traffic

### PR DESCRIPTION
**Pull request by mafredri**
This is change allows using `--tempalte` for both `cleanup` and `workspace-traffic` to target specific workspaces created from that template.

Part of #8556

### CODE REVIEW

**Review by johnstcn — COMMENTED** [review]
Would it not make more sense instead to allow specifying a raw filter query that gets passed to the WorkspaceFilter?

This would still allow you to do e.g. `coder exp scaletest workspace-traffic --filter template:some-template` while also allowing more flexibility around future query needs for roughly the same amount of overall effort.

**Comment by mafredri** [comment]
> Would it not make more sense instead to allow specifying a raw filter query that gets passed to the WorkspaceFilter?
> 
> This would still allow you to do e.g. `coder exp scaletest workspace-traffic --filter template:some-template` while also allowing more flexibility around future query needs for roughly the same amount of overall effort.

I'm open to making the change, but did you have a use-case in mind? As the tool is currently, I don't see a whole lot of benefit.

**Comment by johnstcn** [comment]
> > Would it not make more sense instead to allow specifying a raw filter query that gets passed to the WorkspaceFilter?
> > This would still allow you to do e.g. `coder exp scaletest workspace-traffic --filter template:some-template` while also allowing more flexibility around future query needs for roughly the same amount of overall effort.
> 
> I'm open to making the change, but did you have a use-case in mind? As the tool is currently, I don't see a whole lot of benefit.

Up to you if you don't see a need for it, it just seemed like an easy way to get more flexibility for the same amount of work!

**Review by johnstcn — APPROVED** [review]

**Comment by mafredri** [comment]
> Up to you if you don't see a need for it, it just seemed like an easy way to get more flexibility for the same amount of work!

It was a good suggestion! For now I think it'll be simpler to keep it as-is since it matches the flag given to `create-workspace` and we get validation that a proper template name is given (vs empty result).

**Pull request merged**
