### PR TITLE
feat(examples): add exoscale-linux template

### PR DESCRIPTION
**Pull request by wendevlin**
Exoscale linux starter template, for the coder GUI and [registry.coder.com](https://registry.coder.com/)

### CODE REVIEW

**Comment by masterwendu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by masterwendu** [comment]
recheck

**Comment by bpmct** [comment]
Hey - apologies for the delay in the review here, we were at a company offsite last week!

This contribution is AWESOME. However, we're a bit hesitant to accept this as an official example since we don't have a ton of experience with Exoscale so we may not be able to sufficiently maintain is as a part of our codebase. We have a [community-templates](https://github.com/coder/community-templates) repo which we plan on integrating with https://registry.coder.com and even directly in our product within the next 1-2 months. Would you mind submitting it there instead?

**Comment by masterwendu** [comment]
> Hey - apologies for the delay in the review here, we were at a company offsite last week!
> 
> This contribution is AWESOME. However, we're a bit hesitant to accept this as an official example since we don't have a ton of experience with Exoscale so we may not be able to sufficiently maintain is as a part of our codebase. We have a [community-templates](https://github.com/coder/community-templates) repo which we plan on integrating with https://registry.coder.com and even directly in our product within the next 1-2 months. Would you mind submitting it there instead?

Hi,
ok I understand. Yeah I would submit it there, but the link leads to github 404.

**Comment by matifali** [comment]
Hi @masterwendu, the repo is now available. You can submit the PR there.

**Comment by stirby** [comment]
@kylecarbs @matifali what are our plans to integrate community templates into the registry?

**Comment by matifali** [comment]
This is still planned but needs prioritizing.

**Pull request closed without merging**
