### PR TITLE
fix: test: TestSSH_RemoteForward: wait for startup script

### LINKED ISSUE #10204: test flake: cli TestSSH/RemoteForward
```
    ssh_test.go:422: 2023-10-10 10:59:28.184: cmd: read error: match deadline exceeded: context deadline exceeded (wanted "hello world"; got "==> ⧗ Running workspace agent startup scripts (non-blocking)\r\ncurl localhost:8222\r\nNotice: The startup scripts are still running and your workspace may be incomplete.\r\nFor more information and troubleshooting, see https://coder.com/docs/v2/latest/templates#your-workspace-may-be-incomplete and https://coder.com/docs/coder-oss/latest/templates#troubleshooting-templates\r\n")
    ssh_test.go:422: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/pty/ptytest/ptytest.go:347
        	            				/home/runner/actions-runner/_work/coder/coder/pty/ptytest/ptytest.go:177
        	            				/home/runner/actions-runner/_work/coder/coder/pty/ptytest/ptytest.go:153
        	            				/home/runner/actions-runner/_work/coder/coder/cli/ssh_test.go:422
        	Error:      	read error
        	Test:       	TestSSH/RemoteForward
        	Messages:   	match deadline exceeded: context deadline exceeded (wanted "hello world"; got "==> ⧗ Running workspace agent startup scripts (non-blocking)\r\ncurl localhost:8222\r\nNotice: The startup scripts are still running and your workspace may be incomplete.\r\nFor more information and troubleshooting, see https://coder.com/docs/v2/latest/templates#your-workspace-may-be-incomplete and https://coder.com/docs/coder-oss/latest/templates#troubleshooting-templates\r\n")
```
 
Seen on https://github.com/coder/coder/actions/runs/6468296837/job/17560058112?pr=10164

I think the issue is that the test just peeks a single character as evidence that the SSH session is ready for input

```
		// Wait for the prompt or any output really to indicate the command has
		// started and accepting input on stdin.
		_ = pty.Peek(ctx, 1)

		// Download the test page
		pty.WriteLine("curl localhost:8222")
		pty.ExpectMatch("hello world")
```

but that's not always the case because we are getting notices about startup scripts running.

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/10204

Seen: https://github.com/coder/coder/actions/runs/6468296837/job/17560058112?pr=10164

This test improvement introduces an extra step to wait for the startup script execution, so in theory it reduces the total waiting time.

_I don't have a bulletproof solution, but it should reduce flakiness. In theory, we should wait for the `$` char, but it can be different based on the system environment. In my case, it is `~`. I considered setting it through `PS1`, but I'm afraid that we need to overwrite `.bashrc`._

### CODE REVIEW

**Comment by spikecurtis** [comment]
> In theory, we should wait for the $ char, but it can be different based on the system environment. In my case, it is ~. I considered setting it through PS1, but I'm afraid that we need to overwrite .bashrc.

I ran into the same issue with ReconnectingPTY tests.

https://github.com/coder/coder/pull/9882

If you start `bash --norc` on the remote, you'll get a nice, predictable shell that you can match, even if the user has customized their prompt in `.bashrc`

**Comment by mtojek** [comment]
@spikecurtis In `ReconnectingPTY` you operate on the lower level, and control the process under-the-hood (`bash --norc`). I don't see this opportunity in this case, but maybe my knowledge is insufficient here.

**Comment by spikecurtis** [comment]
Hmm, I'd have expected `coder ssh` to accept a command the way `ssh` does, but apparently not.  Out of scope to fix that right now....

**Review by spikecurtis — APPROVED** [review]
LGTM

**Pull request merged**
