### PR TITLE
feat: allow init script to be used as docker entrypoint

### PR DESCRIPTION
**Pull request by jaulz**
It would be cool to use the init script as a docker entrypoint so we can easily run other commands as well via command property. What do you think?

### CODE REVIEW

**Comment by mafredri** [comment]
Hi @jaulz, I agree that this would be pretty cool, and we appreciate the PR. However, there are a few problems with it:

This change would prevent our agent from running as PID 1 and performing its duties as a process reaper (where applicable). Instead the users "$@" command would become PID 1 and be responsible for reaping, which is not ideal and easily omitted.

The "$@" command could also exit early, resulting in the workspace shutting down prematurely.

**Comment by jaulz** [comment]
@mafredri thanks for your quick feedback! Wouldn't it then help if we make it the other way around? 

````bash
if [ "$@" ]; then
        exec "$@" &
fi

exec ./$BINARY_NAME agent
````

**Comment by mafredri** [comment]
@jaulz In theory, but I'm not sure how it would affect the coder agents reaper duties since the command is started by `/bin/sh` and `coder agent` takes over later.

Do you have any thoughts on this @sreya?

**Comment by jaulz** [comment]
Just one additional thing that should be considered then is that the script shouldn't change the folder.

**Comment by jaulz** [comment]
For anyone running into the same issues I do something like this now and it works so far:
```
entrypoint = ["sh", "-c", replace(replace(coder_agent.postgres.init_script, "127.0.0.1", "host.docker.internal"), "exec ./$BINARY_NAME agent", "cd /usr/local/bin/ \n exec /docker-entrypoint.sh & \n exec $BINARY_DIR/$BINARY_NAME agent \n")]
```

Though, it's not a super nice approach and needs some second thought probably.

**Comment by mafredri** [comment]
@jaulz I'm curious about your use-case. Is there a benefit you achieve in the above scenario vs. using `startup_script` on the `coder_agent` resource?

https://github.com/coder/coder/blob/34d902ebf19ea294db0b906e28c22e89c698b67a/examples/templates/docker/main.tf#L26-L31

**Comment by jaulz** [comment]
You are right, the startup script also helps to solve it, thanks 😊  Thought too much about a Docker way...

**Comment by mafredri** [comment]
> You are right, the startup script also helps to solve it, thanks 😊 Thought too much about a Docker way...

Awesome! And don't worry about it, it's always best when there's only one way to do things, makes things clear, but in this instance the startup script method is more powerful since it can work in all environments.

Since the problem can be solved with the startup script, I'll go ahead and close this. Thanks again for contributing (even though it didn't land)!

**Pull request closed without merging**
