### PR TITLE
feat: edit workspace schedule page

### PR DESCRIPTION
**Pull request by greyscaled**
Resolves: #1455 
Resolves: #1456 

## Summary

Adds a page (accessible from Workspace Schedule section on a workspace) to edit a schedule.

## State Machine

WorkspaceSchedule State Machine

## Impact of Change

General parity with CLI for autostart/autostop: that is you can update your schedule from the UI

## Demo of Change

edit-schedule

### CODE REVIEW

**Review by johnstcn — COMMENTED** [review]
Looking good so far! Comments below.

**Review by kylecarbs — COMMENTED** [review]
Code looks good to me, but skipping a thorough review until in a ready state 😄!

What do you think about Schedule being an option in the Settings pages? It could be helpful to the user for all editable options to be in one spot!

**Review by greyscaled — COMMENTED** [review]
This PR is unfortunately large (though a lot of the code is test code, thankfully).

I am adding **REVIEW** comments to most diffs to add further explanation/context.

I'm happy to do a synchronous review in Discord if it's warranted.

Sorry that this one got large, I like to find smaller pieces, but this is just how things are as CE deadline approaches. Many thanks in advance 💖 .

---

Edit: Also, if you're newer to cron strings, https://crontab.guru/#30_09_*_*_1-5 is the way to go

---

Edit: If you're wondering why we don't use a cron library for some of our manipulation, it's because we have a custom implementation right now and do not want to expand it to full blast just yet.

---

Edit: This PR grew way larger than I had intended. I'm happy to address all comments, but my default response to things like refactors, improvements, nice-to-haves will be "iteration", as in follow-up efforts.

@johnstcn and I already have various follow-up efforts, like changing the `ttl` from nanosecond precision. Some of the messy hours to nanosecond time conversion will get cleaned up then.

See also @ammario and I's awesome comment thread and a consensus here: https://github.com/coder/coder/pull/1701#issuecomment-1137863816 that we want to give the user a diff-like preview in this form while editing it. That may not land in CE (I'll certainly try), as there are other priorities like notifications and extension that must come first.

**Review by johnstcn — APPROVED** [review]
Looking good!

**Review by kylecarbs — APPROVED** [review]
Very thorough comments and tests!

**Review by Kira-Pilot — APPROVED** [review]

**Pull request merged**
