### PR TITLE
feat: RBAC scopes per API key (WIP)

### PR DESCRIPTION
**Pull request by dwahler**
This PR adds a `scope` field to the `api_keys` table, and checks operations against the key's scope as well as the user's roles.

This is currently a pretty hacky/minimal WIP, and mostly exists to test my assumptions about how to fit this change into the existing RBAC machinery. Only `any` and `readonly` scopes are currently implemented.

### CODE REVIEW

**Comment by Emyrk** [comment]
I don't think we need this right now. We should wait until there is a need

**Comment by dwahler** [comment]
Yep, let's revisit this when it becomes a priority on the roadmap.

**Comment by deansheather** [comment]
With David's permission from Slack, I'm reopening this so I can use it for devurl permissions

**Comment by deansheather** [comment]
Actually it's pretty heavily outdated and has loads of conflicts, I might just open a new PR instead and pull David's code in by hand

**Pull request closed without merging**
