### PR TITLE
feat(agent): Add shutdown lifecycle states and shutdown_script support

### LINKED ISSUE #4677: Run script before workspace stop
The Coder agent has a [startup_script](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#startup_script) to run arbitrary actions when it is started.

A `shutdown_script` could be added to run clean-up operations, collect stats, etc. before Coder actually changes the workspace state. A configurable `timeout` could be added to ensure a shutdown still occurs even if the script fails/hangs.

### PR DESCRIPTION
**Pull request by mafredri**
This PR adds support for agent shutdown lifecycle states and `shutdown_script`.

It (currently) relies on terraform provider abilities to gracefully shut down. For instance with the docker provider it can be controlled via:

```tf
resource "docker_container" "workspace" {
  destroy_grace_seconds = 30
  stop_timeout          = 30
  stop_signal           = "SIGINT"
}
```

The agent can handle common signals like `SIGHUP`, `SIGINT`, `SIGTERM`. If need be, more signals could be handled.

Builds upon #5171
Fixes #4677

**Note:**

- In hindsight, I should probably have called the lifecycle states `stopping`, `stop_timeout`, `stop_error`, `stopped`, yay or nay to make this change?

### CODE REVIEW

**Comment by mafredri** [comment]
TODOs (https://github.com/coder/coder/pull/6139/commits/a1222d0e28038ce57e1cd57ecb34fdcdb8ac42ca) have been removed in favor of https://github.com/coder/coder/issues/6180.

**Review by mtojek — APPROVED** [review]
Nice!

LGTM, but I didn't analyze it too deeply as the PR is massive.

**Comment by mtojek** [comment]
Hey @mafredri! Is it something that you will continue to work soon?

**Comment by mafredri** [comment]
> Hey @mafredri! Is it something that you will continue to work soon?

Yup, I'll get this rebased and (try to) merge it today. 👍🏻

**Pull request merged**
