### PR TITLE
feat: Add selected template link at the template select field

### LINKED ISSUE #1864: Display a template link in the Create Workspace form when the user selects the template.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
- Add the selected template link at the template select field
- Made a minor refactoring in the forms to make them look more consistent

Closes #1864 

Before:
Screen Shot 2022-05-31 at 11 57 47

After:
Screen Shot 2022-05-31 at 11 56 57

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
It is also related to #1638

**Review by Kira-Pilot — APPROVED** [review]
Nice! What do you think about left aligning that 'Read more' helper text against the left border of the input?

**Comment by BrunoQuaresma** [comment]
@Kira-Pilot I've been thinking about that and I think it is best and we probably want this for all the text helpers. @vapurrmaid @presleyp @ashmeer7 what do you think?

**Comment by BrunoQuaresma** [comment]
I was wondering why the text helper for the schedule form was aligned to the left without any extra style, and I found we are using the input as "underline" instead of "contained" in the schedule. @vapurrmaid are you ok if I change the Schedule form to use the default(contained) type for inputs?

**Comment by vapurrmaid** [comment]
> @Kira-Pilot I've been thinking about that and I think it is best and we probably want this for all the text helpers. @vapurrmaid @presleyp @ashmeer7 what do you think?

Great suggestions 🙌🏻 !

**Comment by BrunoQuaresma** [comment]
They look good!
Screen Shot 2022-05-31 at 15 18 09

**Pull request merged**
