### PR TITLE
chore: use pnpm workspaces

### PR DESCRIPTION
**Pull request by aslilac**
Been meaning to do this for a long time :^)

### CODE REVIEW

**Comment by aslilac** [comment]
ok, turns out this isn't gonna be the easy slam dunk that I thought it would 🙃

**Comment by BrunoQuaresma** [comment]
Which blockers are you finding?

**Comment by aslilac** [comment]
seems like the lock file didn't merge very cleanly, so a lot of versions are messed up, and it's causing tons of errors :\

**Comment by BrunoQuaresma** [comment]
Maybe related to my fix https://github.com/coder/coder/pull/14134

**Comment by matifali** [comment]
If this transition is successful we can list Coder on this page https://pnpm.io/workspaces#usage-examples. ⭐

**Comment by aslilac** [comment]
I'm struggling to get it to merge the lock files into a single workspace lock file properly. :(

**Pull request closed without merging**
