### PR TITLE
feat: Allow regen-ssh and fetching a single user from the cli

### PR DESCRIPTION
**Pull request by Emyrk**
# Some more CLI user CRUD

```
coder public-key --reset -y
coder users get me
```

### CODE REVIEW

**Review by mafredri — APPROVED** [review]
Looks good!

**Review by ammario — CHANGES_REQUESTED** [review]
--

**Review by ammario — APPROVED** [review]
I'm only reviewing UX, not code. But LGTM.

**Review by f0ssel — APPROVED** [review]
Yup this looks great to me

**Review by johnstcn — APPROVED** [review]

**Review by kylecarbs — APPROVED** [review]
Minor comments on copy, but LGTM

**Pull request merged**
