### PR TITLE
chore: update editorconfig with new tabs default

### PR DESCRIPTION
**Pull request by code-asher**
I explicitly added `tsx` and `ts` since I am not sure if we have other file types that got changed to tabs, lemme know if I missed some.

### CODE REVIEW

**Review by aslilac — COMMENTED** [review]
oh! I didn't notice we had a second one of these inside site/. good catch!

I think it makes more sense to change the default though (since basically every file in this folder should use tabs now) rather than add them as an exception.

Something like...

```ini
[*]
indent_style = tab
indent_size = 2

[node_modules/**]
ignore = true
```

(settings `indent_size` is actually still important for non-obvious reasons)

**Comment by code-asher** [comment]
Makes sense to me!  Good point on `indent_size`, I noticed some odd behavior there only in ts(x) files but thought maybe my editor was just being weird.

**Review by aslilac — APPROVED** [review]
beautiful!

**Comment by code-asher** [comment]
Actually, does `indent_size` take away people's visual tab width preference?  Some reading I was doing suggests it might.  I tried unsetting `indent_size` again and maybe it was just my editor being weird, it seems to work OK.

**Comment by aslilac** [comment]
I would hope not, but it can be important for stuff like yaml files that don't support tab indentation. we can try leaving it unset for now if you'd like, and we can always set it later if it's causing issues.

**Comment by code-asher** [comment]
Sweet, lemme unset it for now then.  I did some brief testing with VS Code and the editorconfig plugin and it did change the visual tab width which seems kinda insane to me but I suppose it is what it is

**Pull request merged**
