### PR TITLE
fix: stop inserting provisioner daemons into the database

### LINKED ISSUE #9015: provisioner_daemons table grows without bounds
We only have SQL queries that add to the table and read from it --- so provisioner daemons are added but never removed.

Reading from the table is only used today to serve an API route to get all the daemons.  It's not clear whether the front end ever uses this information, so it might be that the table has no defined purpose at present...

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #9015 

We can revert this and/or reimplement when we have a use case for storing provisioner daemons in the database.

### CODE REVIEW

**Review by Emyrk — COMMENTED** [review]
~~Does this work with HA too? Multiple coder replicas?~~

Ah I see the issue it is only used by an api endpoint.

**Review by johnstcn — COMMENTED** [review]
This arguably introduces a breaking change into an enterprise feature. What's the path forward for existing consumers of this endpoint?

Even though we only internally use it in unit tests and it's likely not very useful, it's still publicly documented here: https://coder.com/docs/v2/latest/api/enterprise#get-provisioner-daemons

**Review by johnstcn — APPROVED** [review]

**Comment by spikecurtis** [comment]
> This arguably introduces a breaking change into an enterprise feature. What's the path forward for existing consumers of this endpoint?
> 
> Even though we only internally use it in unit tests and it's likely not very useful, it's still publicly documented here: https://coder.com/docs/v2/latest/api/enterprise#get-provisioner-daemons

I've left the endpoint in place, so we don't 404. But, I just don't see what anyone could have reasonably used that endpoint for: it's just a big list of every provisioner daemon that ever connected.

maybe @bpmct has thoughts on whether we need to manage this change more carefully.

**Comment by spikecurtis** [comment]
We need to track active provisioner daemons for #5979 so closing this issue and we'll close #9015 when it's fixed.

**Pull request merged**
