### PR TITLE
chore: Drop resource_id support in rbac system

### PR DESCRIPTION
**Pull request by Emyrk**
# What this does

This drops `resource_id` from the RBAC permissions. This is a loss of a feature from RBAC. The goal is to reduce complexity of the rego policy, and reduce the number of permissions on actors. 

At the present, no `resource_id` permissions are used. So this removes excess functionality that has no real planned use in the current roadmap.

# Why did we have resource_id?

Intended to support:

 - [x] Workspace agent tokens
   - This is handled outside the RBAC permission system
 - [x] Roles as a resource ([solved](https://github.com/coder/coder/blob/stevenmasley/rbac_no_ids/coderd/rbac/builtin.go#L148-L198))
   - Solution needs to be determined. This intended solution was building a graph using permission nodes. Although "clean" from an additional code perspective, visualizing and displaying the output of this was going to be a challenge. It is likely easier to just build static lists of approved assign/remove roles for each role.
   - We can still implement this making each role a unique resource type.
 - [ ] Workspace sharing (ACL lists on object?)
   - Solution was to assign permission nodes to other users to share my workspace?? This solution was technically supported, but a bit convoluted as it requires assigning permissions to another user. It would also be hard to list all users that this workspace is shared with. 

# What do we gain?

By removing `resource_id`, there is only 3 properties of an object we need to know `Authorize?`: `object_type`, `owner_id`, and `org_owner`. This reduction only removes 1 property, but drastically reduces the number of unique objects in the system. This can drastically speedup `Authorize()` calls on large sets and enables future optimizations.

# Can we revert this?

Yes. We can revert this, however I don't recommend we do [Phase 2](https://github.com/coder/coder/issues/3098#issuecomment-1208725060).

I think it is better to have a need arise and implement this back, then have this feature be available and possibly misused because it is "just there".

# What this does not do

This does not reduce RBAC authorization benchmarks.

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
I like the simplification here. Could we add a benchmark so we can see how much this improves the performance?

**Comment by Emyrk** [comment]
> I like the simplification here. Could we add a benchmark so we can see how much this improves the performance?

This won't improve performance at all, but it allows me to use my new rego query that supports partials. I just need to drop this requirement first. I can add benchmarks for the sake of benchmarks though :+1:

**Comment by kylecarbs** [comment]
Ahh, I see. Should we just add that Rego query as part of this then?

**Comment by Emyrk** [comment]
> Ahh, I see. Should we just add that Rego query as part of this then?

I have it like 90% written. I figured I'd drop this functionality, get the tests passing, then I can swap the rego without a sweat because if the tests pass, the implementation behavior is identical. 

Feels "cleaner" to make that a different PR. If I add benchmarks to this, it also gives us a better comparison and we can go back in time in our git history a bit cleaner.

**Comment by kylecarbs** [comment]
Makes sense to me! I approve.

Let's link the PRs in your future one, just so the timeline makes sense.

**Comment by Emyrk** [comment]
(Benchmarks](https://github.com/coder/coder/pull/3426/commits/186bfc104db69a60b80ca33d6b0068599dc119be):

```
cpu: Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
BenchmarkRBACFilter/NoRoles-8              10000            102791 ns/op       37335 B/op            684 allocs/op
BenchmarkRBACFilter/Admin-8                 3606            346762 ns/op      106855 B/op           2157 allocs/op
BenchmarkRBACFilter/OrgAdmin-8              3668            287601 ns/op       91006 B/op           1827 allocs/op
BenchmarkRBACFilter/OrgMember-8             3987            330623 ns/op      101538 B/op           2072 allocs/op
BenchmarkRBACFilter/ManyRoles-8             2564            503679 ns/op      161122 B/op           3245 allocs/op
```

**Review by johnstcn — COMMENTED** [review]
👍

**Pull request merged**
