### PR TITLE
chore: replace chi path function with go 1.22 `r.PathValue`

### PR DESCRIPTION
**Pull request by coadler**
Path values were added to the request struct in go 1.22 https://pkg.go.dev/net/http#Request.PathValue

### CODE REVIEW

**Comment by coadler** [comment]
maybe one day this will assign me runners

**Review by deansheather — APPROVED** [review]

**Review by kylecarbs — APPROVED** [review]
nice

**Comment by coadler** [comment]
i hate github actions

**Comment by matifali** [comment]
I guess this needs rebasing to fix failing tests.

**Pull request closed without merging**
