### PR TITLE
fix: always show upload and scratch in create template gallery

### PR DESCRIPTION
**Pull request by aslilac**
Now that multi-org is out of experimental, we should clean up some of the inconsistencies between the "orgs ui" and the "non-orgs ui". Along these lines, we should show the scratch and upload options in `CreateTemplateGalleryPage` even when the multi-organization experiment isn't enabled. They just live here now. :)

### CODE REVIEW

**Comment by aslilac** [comment]
this will be merged eventually, just waiting for the right time (post multi-org ga)

**Comment by aslilac** [comment]
should be mergable in the next few weeks as we approach the end of the orgs experiment

**Review by buenos-nachos — APPROVED** [review]
Looks good!

**Review by jaaydenh — APPROVED** [review]
LGTM

**Pull request merged**
