### PR TITLE
chore: track usage of built-in example templates

### PR DESCRIPTION
**Pull request by hugodutka**
Addresses https://github.com/coder/nexus/issues/99.

Changes:
- Save the id of the built-in example template used to create a template version in the database
- Include the example id in telemetry

### CODE REVIEW

**Review by Emyrk — COMMENTED** [review]
This just adds the ID column, it does not add `uuid`'s to our built in templates yet right?

Are we going to add `uuid`s to our builtins? Or should it be a string, eg: `github.com/coder/templates/official/aws-linux`

And do we need version control?

`github.com/coder/templates/official/aws-linux@ad4efa53708e60a7094ef9687e7dfda0441aaec7`?

**Comment by hugodutka** [comment]
> This just adds the ID column, it does not add uuid's to our built in templates yet right?

That's correct.

> Are we going to add uuids to our builtins? Or should it be a string, eg: github.com/coder/templates/official/aws-linux

Hmm, I haven't heard anything about that before. Were there any plans?

> And do we need version control?

In telemetry, we can infer the built-in template version from the deployment version. From my perspective we don't need additional version control.

**Comment by Emyrk** [comment]
@hugodutka :+1: 

> Hmm, I haven't heard anything about that before. Were there any plans?

This PR adds a column to track the built in template source by uuid correct? Do built ins have a consistent uuid across all deployments?

**Review by Emyrk — APPROVED** [review]
👍 Got it, that tracks!

**Pull request merged**
