### PR TITLE
feat: append owner_oidc_refresh_token to coder_workspace_owner data source

### PR DESCRIPTION
**Pull request by ffais**
Add OIDC refresh token to coder_workspace_owner data source, useful to renew access token inside the workspace without restarting it.

Related provider PR: https://github.com/coder/terraform-provider-coder/pull/264

### CODE REVIEW

**Comment by kylecarbs** [comment]
Why not use the Coder CLI with external auth to refresh?

**Comment by ffais** [comment]
In our use case the access token is used inside the workspace by a client to communicate with some api. The access token for security reasons has a short expiration time, in some environments less than 30 minutes. Having the refresh token available inside the workspace would allow the client to be able to renew the access token transparently and without user intervention.

**Comment by kylecarbs** [comment]
Can you use [external auth](https://coder.com/docs/admin/external-auth) for this instead? I believe you manually refreshing the OIDC token would revoke the prior token, essentially invalidating a user session.

**Comment by kylecarbs** [comment]
Then you can use the CLI: https://coder.com/docs/admin/external-auth#native-git-authentication-will-auto-refresh-tokens

**Comment by ffais** [comment]
> Can you use [external auth](https://coder.com/docs/admin/external-auth) for this instead? I believe you manually refreshing the OIDC token would revoke the prior token, essentially invalidating a user session.

You are right, in the scenario where opaque access tokens are used, the refresh procedure inside the workspace could create problems. This solution works without any problems only in case JWT tokens are used.

**Pull request closed without merging**
