### PR TITLE
fix(examples/templates/aws-linux): add `hashicorp/cloudinit` provider

### PR DESCRIPTION
**Pull request by phorcys420**

### CODE REVIEW

**Review by matifali — APPROVED** [review]
This should be backported to `release/2.18` too. Can you do that?

Also didn't we replace regions with the module?

**Comment by phorcys420** [comment]
@matifali I thought we did but maybe only in `aws-devcontainer`?

It seems I didn't do it in #15500, i'll PR that soon.
for the backport, do you just want me to make another PR? not sure how that works

**Comment by matifali** [comment]
@phorcys420 Yes a PR to `release/2.18` branch. as currently this template is broken in 2.18.

**Comment by phorcys420** [comment]
@matifali, I can't get required to turn green, do you think you can merge?

**Pull request merged**
