### PR TITLE
feat: add support for custom permissions in Helm chart `rbac.yaml` file

### PR DESCRIPTION
**Pull request by lbi22**
This PR adds support the permission to manage the Kubernetes services inside the coder workspace.

### CODE REVIEW

**Comment by ericpaulsen** [comment]
hi @lbi22 - thank you for your contribution. can you share more context on the use-case?

**Comment by lbi22** [comment]
hello @ericpaulsen, in my team we would like to deploy a DB alongside the workspace and having the possibility to create a service to expose the DB will help in the process.

**Comment by lbi22** [comment]
recheck

**Review by kylecarbs — DISMISSED** [review]

**Comment by kylecarbs** [comment]
@ericpaulsen longer-term we should allow people to just specify custom perms as a property in our Helm instead of these opinionated properties.

Maybe we do that instead of this if it's easy?

**Comment by ericpaulsen** [comment]
> @ericpaulsen longer-term we should allow people to just specify custom perms as a property in our Helm instead of these opinionated properties.
> 
> Maybe we do that instead of this if it's easy?

@kylecarbs yes, I would prefer to do that instead. I can implement.

**Comment by lbi22** [comment]
@ericpaulsen @kylecarbs  if you want, I can add the block without issue.

**Review by ericpaulsen — APPROVED** [review]

**Comment by lbi22** [comment]
What can we do to unblock the situation?

**Pull request merged**
