### PR TITLE
chore: put overrides and renames in pkg context in sqlc.yaml

### PR DESCRIPTION
**Pull request by andrewmbenton**
The referenced bug in sqlc.yaml was fixed in https://github.com/sqlc-dev/sqlc/pull/2001. So this change just moves overrides and renames in sqlc.yaml to their "ideal" location, inside the package/queryset scope.

### CODE REVIEW

**Comment by andrewmbenton** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Emyrk — APPROVED** [review]

**Comment by matifali** [comment]
@Emyrk should we merge this?

**Comment by Emyrk** [comment]
Off thought I did. I'll merge it

**Comment by Emyrk** [comment]
Moved https://github.com/coder/coder/pull/11347

**Pull request closed without merging**
