### PR TITLE
feat(coderd/coderdtest): deprecate coderdtest.CreateFirstUser

### PR DESCRIPTION
**Pull request by johnstcn**
This PR:
- Deprecates `coderdtest.CreateFirstUser`
- Automatically creates the first user unless `SkipAutoCreateFirstUser` is set.
- Adds helper methods for creating additional test users with pre-defined roles.
- Adds a helper method `RunAsFirstUser` as an escape hatch where required.

Rationale: a lot of unit tests were simply calling `client = coderdtest.CreateFirstUser()` and performing all testing with that client. As that client has unrestricted permissions, there is a high possibility of unintentionally missing auth-related bugs.

I have not run through all of the existing unit tests, as that would be a prohibitively large diff. We can instead update as we modify existing tests.

### CODE REVIEW

**Review by kylecarbs — COMMENTED** [review]
I'm concerned about how the code will look when we nest it all inside `AsFirstUser`.

What I like about the tests right now is how explicit they are about which user is being created, and `coderdtest.New` really _just_ creates a testing instance of `coderd`, nothing else.

Did we only have a single instance of poor permissions-related testing so far? And would this really prevent it? We still have to intentionally not use the owner to do some things and use the owner to do others.

**Comment by johnstcn** [comment]
> I'm concerned about how the code will look when we nest it all inside `AsFirstUser`.
 
I would interpret that as a code smell to be honest. If there's a significant amount of testing that needs to be done as an owner, it would make sense to create a user with those permissions explicitly and continue working with the client authenticated as that user.

> Did we only have a single instance of poor permissions-related testing so far? 

I haven't gone git-spelunking looking for more instances.

> And would this really prevent it?

To completely prevent it would probably involve completely walling off the first user, which I'd like to avoid as it would be rather disruptive.

**Comment by Emyrk** [comment]
My initial thoughts are this is in a positive direction.

First, `CreateFirstUser` is almost always called in all unit tests, and because it's **required**, and returns a client, everyone just writes the tests with said client. It's easy and convient.

What I think we are trying to move to in this, is make the `Owner` user less convenient, or make it just as convenient to use a different user.


> I'm concerned about how the code will look when we nest it all inside AsFirstUser.

At first I was too, but then I realized this is setup code, and nesting it inside a function prevents the owner role from bleeding elsewhere in the test. It sort of separates the concerns of "setup" vs "test". 


---

We are so locked to that first returned client though, that this doesn't prevent people from doing the status quo.

It probably isn't worth refactoring all the existing tests, that would just take too long. Maybe just keeping the helpers `CreateTemplateAdmin`, `CreateUserAdmin` is a positive step :shrug:.

**Comment by johnstcn** [comment]
> We are so locked to that first returned client though, that this doesn't prevent people from doing the status quo.

Should `coderdtest.New` only return the URL of the running coderd instance, perhaps?

**Comment by Emyrk** [comment]
> > We are so locked to that first returned client though, that this doesn't prevent people from doing the status quo.
> 
> Should `coderdtest.New` only return the URL of the running coderd instance, perhaps? Right now the client is unauthed until you run `coderdtest.CreateFirstUser`.

I guess I mean, we already do `coderdtest.CreateFirstUser`. If we moved to `AsFirstUser` to contain setup, then it would correctly prevent owner usage within the test. Which is a good win :tada:. But that would require refactoring all the existing tests, so we **have** to return the authed client, or keep the `CreateFirstUser` we already have. Both sidestep the `AsFirstUser` to the point I don't think it will be adopted.

**Comment by kylecarbs** [comment]
I'd love to understand which tests we haven't written correctly before we jump to a solution here. This is promoting a pattern of calling coderd with API requests opaquely on setup, which spooks me.

@johnstcn do we have a list of issues this would have prevented or something?

**Comment by johnstcn** [comment]
> I'd love to understand which tests we haven't written correctly before we jump to a solution here. This is promoting a pattern of calling coderd with API requests opaquely on setup, which spooks me.
> 
> @johnstcn do we have a list of issues this would have prevented or something?

Nope. It sounds like I might not be solving the right problem here, so let's shelve this for now and revisit later if needed!

**Pull request closed without merging**
