### PR TITLE
chore: minor tweaks to license ui

### PR DESCRIPTION
**Pull request by rodrimaia**
minor tweaks:
* Change 40 / Unlimited users to 40 users / Unlimited
* Change Add new License to Add new license
* Change February 3, 2024\nValid until to Valid until\nFebruary 3, 2024

new screenshot: 
image

### CODE REVIEW

**Comment by matifali** [comment]
What do you think about changing to
Users: 2 / 25

**Review by BrunoQuaresma — APPROVED** [review]
I'm good with them just notice one thing, when there is a single license, it is showing "users" in the plural. Also, what do you think about @matifali suggestion? Up to you.

**Review by bpmct — APPROVED** [review]

**Comment by rodrimaia** [comment]
Thank you for the suggestions Bruno and @matifali . updated version: 
image

**Comment by matifali** [comment]
One last thing, do we have a double-check when the user clicks on remove? We should not allow removing license accidentally.

**Comment by bpmct** [comment]
> One last thing, do we have a double-check when the user clicks on remove? We should not allow removing license accidentally.

We double-check :)

**Pull request merged**
