### PR TITLE
web: use seconds in max TTL input

### PR DESCRIPTION
**Pull request by ammario**
Milliseconds are more difficult to deal with due to
all of the zeros.

### CODE REVIEW

**Comment by ammario** [comment]
@BrunoQuaresma, I'm pretty new to TS and our frontend codebase. If I did anything in a suboptimal way, please let me know.

**Comment by BrunoQuaresma** [comment]
Since the BE does not accept a `max_tll` field, we have to keep the `max_ttls_ms` field and convert the value on submit.

**Comment by BrunoQuaresma** [comment]
I think we could do better, and set this as minutes, what do you think?

**Comment by BrunoQuaresma** [comment]
@ammario I made the conversion in the handlers, so we don't have to add extra logic to map BE errors to a diff field, and vice-versa.

**Comment by ammario** [comment]
@BrunoQuaresma — makes sense. Thanks for showing me how this is done. Plz approve and then it can merge.

**Review by johnstcn — APPROVED** [review]
I'm all in favour of this! I think minutes is the lowest useful granularity of time with autostart though.

**Review by jsjoeio — APPROVED** [review]
I like this as well! Approving on behalf of FE to help you move this forward

**Comment by ammario** [comment]
> I'm all in favour of this! I think minutes is the lowest useful granularity of time with autostart though.

I agree. Ideally the frontend accepts the same input as the CLI so there's so no truncation.

I thought this PR was a step forward but not ideal.

**Pull request merged**
