### PR TITLE
docs: update release schedule

### PR DESCRIPTION
**Pull request by matifali**
These changes should be automated.
cc: @stirby @mafredri

### CODE REVIEW

**Comment by mafredri** [comment]
@matifali @stirby do we have an issue to track the automation work?

**Comment by matifali** [comment]
Not I am aware of. 
Let's wait for @stirby if he wants to prioritize this yet.

**Comment by stirby** [comment]
We should. May ask @mafredri to write a script that automates the release schedule, but that version flag _should_ have been bumped. 

I'll add two tickets after checking the autoversion PR.

**Comment by stirby** [comment]
My fault, I didn't run the promotion script when releasing v2.13. I had assumed a mainline minor release would execute that script.

**Pull request merged**
