### PR TITLE
feat: add 'display_name' column to 'workspace_agent_scripts'

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Add a `display_name` column to `workspace_agent_scripts` table.

`display_name` is sourced from `coder_script` resource in [the coder terraform provider](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/script#display_name). It will be used in the UI when we display script timings.

Work on https://github.com/coder/coder/pull/14713 requires `display_name` to be present in the database.

### CODE REVIEW

**Review by dannykopping — APPROVED** [review]
LGTM

Would you mind adding some more detail to the description about where this value comes from, and how it will be used?

**Comment by DanielleMaywood** [comment]
> Would you mind adding some more detail to the description about where this value comes from, and how it will be used?

Done! Let me know if you want more detail.

**Comment by dannykopping** [comment]
Perfect, thanks 👍

**Comment by dannykopping** [comment]
@DanielleMaywood should we wait for the other PR to be merged first?

**Comment by DanielleMaywood** [comment]
I think this PR should go first as this is to pull out the `display_name` change from that one into a separate PR.

**Review by johnstcn — APPROVED** [review]
👍

**Pull request merged**
