### PR TITLE
docs: move architecture to top level

### PR DESCRIPTION
**Pull request by ericpaulsen**
this moves our architecture documentation to the top level, and adds a nice container SVG for the icon.

### CODE REVIEW

**Review by matifali — DISMISSED** [review]
There are multiple incorrect links in the refactor. 
Please see: https://github.com/coder/coder/actions/runs/9716022262/job/26818707420?pr=13722#step:4:1048

**Comment by ericpaulsen** [comment]
done @matifali

**Review by matifali — COMMENTED** [review]
@stirby @bpmct, does it conflict with the refactoring you are doing for #13434 at https://coder.com/docs/@restructure?

I am waiting for your response otherwise, LGTM.

**Review by stirby — APPROVED** [review]
This will be overwritten by the restructure, but we can revisit it's placement or linking it in the homepage when that's merged.

**Pull request merged**
