### PR TITLE
fix(scripts): check if PR list is empty

### PR DESCRIPTION
**Pull request by phorcys420**
I am currently (= finally) working on a PR for chocolatey support.

During testing, It occured to me that the release notes were always failing, that is because ``check_commit_metadata.sh`` tries to loop over ``$pr_metadata_raw`` even if it is empty, this causes an issue because PRs don't ususally have PRs.
This PR makes it so that it checks if the PR list is empty before looping.

### CODE REVIEW

**Comment by phorcys420** [comment]
I have accidentally pushed to the wrong branch.

**Review by mafredri — APPROVED** [review]
Could you share a bit about your use-case and why you need to call the commit metadata script on a branch?

I think this change could be fine, although the previous behavior is a bit safer in that we may not want to continue if the `gh` command doesn't return any output (since we don't know if it guarantees a proper exit code).

Then again, the previous behavior might fail in an edge case where we only want to release a single commit that wasn't merged via PR.

**Comment by phorcys420** [comment]
hey @mafredi, I am looking at making the release action work (atleast mostly) in a branch  that way you can do dry-runs in a fork.

The idea is that it would allow for easier testing when PRiing stuff like Chocolatey or Scoop support.

**Comment by mafredri** [comment]
Alright, thanks for expanding on that. Let's get this merged and hopefully unblock you! ☺️ Thanks for the PR!

**Pull request merged**
