### PR TITLE
feat: add `--net-admin` option to install script

### PR DESCRIPTION
**Pull request by coadler**
This allows the install script to add `CAP_NET_ADMIN` to the installed
binary with user consent. Combined with adding `CAP_NET_ADMIN` to the
agent binary, we see an increase of >50% in networking speeds.

### CODE REVIEW

**Comment by coadler** [comment]
Current dependencies on/for this PR:
* main
  * **PR #9953** <a href="https://app.graphite.dev/github/pr/coder/coder/9953" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coder/coder/9953?utm_source=stack-comment).

**Review by kylecarbs — COMMENTED** [review]
Can we try to passively do this automatically? And then this would force failure instead?

**Comment by ammario** [comment]
Agree with kyle. If we could do this optimistically in the agent and avoid additional configuration that would be awesome. We could apply a similar optimistic approach to niceness. (cc @sreya)

**Comment by coadler** [comment]
@kylecarbs @ammario Ideally yes, but I'd really like to learn all of the edge cases by having this opt-in for a bit. I'm using this as more of a feature flag for us to test and share with some customers. Once tested I'll make this automatic.

**Comment by coadler** [comment]
For example, in Docker you can successfully add the capability. But if your container doesn't have the capability, the binary will always fail to run. There's also some security considerations when enabling this.

**Comment by ammario** [comment]
👍🏽

**Review by kylecarbs — APPROVED** [review]

**Comment by coadler** [comment]
Updates https://github.com/coder/coder/pull/9953

**Pull request merged**
