### PR TITLE
chore: check for invalid markdown links in docs weekly

### PR DESCRIPTION
**Pull request by matifali**
As per #6793, there are multiple broken links in our docs. This action will check if all markdown links are valid.

cc: @ammario @bpmct

### CODE REVIEW

**Comment by ammario** [comment]
We had this before but it was flakey since requests randomly timed out in CI.

**Comment by matifali** [comment]
Ok. You can close it. From now on, we can be more careful with links and should test manually before pushing.

I can close as not planned. Your call.

**Comment by ammario** [comment]
Maybe do this as an actions cron for now? We can probably have it notify a slack channel.

**Comment by matifali** [comment]
To post to a slack channel, I will probably need some help from the team. https://github.com/slackapi/slack-github-action

**Comment by matifali** [comment]
It turns out that the link check action does not have any outputs, so a workaround will be to follow the steps,
1. Run Markdown Link check workflow and save the workflow log
2. Run another workflow that runs when 1. completes, parses the log and send a message to slack.

Any other ideas?

**Comment by matifali** [comment]
This is a partial solution, as we have to check the output of this workflow every week. I plan to set up slack integration in a separate PR after I find out how to use this action's output instead of saving logs, parsing, and running another workflow to post that to slack.

Merging this will at least give us timely reports if there are any invalid links.

**Comment by matifali** [comment]
@bpmct suggested posting a message to slack when this workflow runs. We can check the logs on GitHub.

**Review by bpmct — APPROVED** [review]

**Comment by matifali** [comment]
Can it be merged as it is unharmful and will provide us with useful insights on the docs? @bpmct

**Pull request merged**
