### PR TITLE
fix: change alpha badge color to violet

### PR DESCRIPTION
**Pull request by sreya**
- Makes it less scary.

Screenshot 2023-10-03 at 6 08 30 PM

### CODE REVIEW

**Comment by aslilac** [comment]
I feel like blue isn't scary enough, personally. what if we did something kinda "silly" like magenta?

**Comment by aslilac** [comment]
Screenshot 2023-10-03 at 5 18 20 PM

I kinda like how turquoise feels

**Comment by sreya** [comment]
Those looks good, I'm curious what @bpmct thinks?

**Comment by aslilac** [comment]
Ooo, violet also looks really nice:

Screenshot 2023-10-03 at 5 26 15 PM

<details>
<summary>Code</summary>

```tsx
import { colors } from "theme/colors";

export const AlphaBadge: FC = () => {
  return (
    <span
      css={[
        styles.badge,
        {
          border: `1px solid ${colors.violet[10]}`,
          backgroundColor: colors.violet[14],
          color: colors.violet[1],
        },
      ]}
    >
      Alpha
    </span>
  );
};
```

</details>

You can just swap out the color name in there depending on what we decide to go with, but this is the code I ended up with

**Comment by bpmct** [comment]
Huge fan of violet.

**Comment by matifali** [comment]
I like yellow

**Comment by Emyrk** [comment]
I like the purple too

**Review by aslilac — APPROVED** [review]

**Pull request merged**
