### PR TITLE
chore(site): fix material ui warning

### PR DESCRIPTION
**Pull request by jsjoeio**
I was annoyed by the Material UI warning I kept seeing in the console when running `yarn test` so I decided to fix it based on this [StackOverflow answer](https://stackoverflow.com/questions/68822767/material-ui-the-css-function-is-deprecated-use-the-stylefunctionsx-instead#68822767).

## Changes
See commits for descriptions

- chore(deps): upgrade @material-ui/core to 4.12.4
- refactor: use alpha() instead of fade
- refactor: rows -> minRows
- refactor: overlap circle -> circular
- refactor: createMuiTheme -> createTheme

### CODE REVIEW

**Review by Kira-Pilot — APPROVED** [review]
Thanks for doing this! That was bugging me, too.

**Comment by jsjoeio** [comment]
Looks like there are some other changes I missed. Adding those now.

**Comment by jsjoeio** [comment]
I'm not seeing these same errors locally when I run `yarn test:coverage`  🤔 I'll fix them first thing tomorrow: https://github.com/coder/coder/actions/runs/3109252710/jobs/5039309180#step:6:1088

**Comment by jsjoeio** [comment]
Hmm possibly a showstopper if this is true: https://github.com/mui/material-ui/issues/33216#issue-1276184787

**Comment by BrunoQuaresma** [comment]
> Hmm possibly a showstopper if this is true: [mui/material-ui#33216 (comment)](https://github.com/mui/material-ui/issues/33216#issue-1276184787)

Unfortunately it looks stale.

**Comment by jsjoeio** [comment]
Nevermind, I figured it out. Had to use generics in `Pill.tsx`
image

**Review by kylecarbs — APPROVED** [review]

**Pull request merged**
