### PR TITLE
feat: Support `--header` for CLI commands to support proxies

### LINKED ISSUE #3527: Support `--header` for CLI commands to support CloudFlare Access or other identify-aware proxies
## Problem statement

We had a request from someone in our community to add this in order to support using the CLI when Coder is hosted under CloudFlare access. Vault did something similar: hashicorp/vault#12508

## Definition of done

Users can use the CLI and pass arbitary headers.

e.g.
```sh
coder login --header "CF_ACCESS_TOKEN=asdf"
coder ls --header "CF_ACCESS_TOKEN=asdf"
```

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #3527.

### CODE REVIEW

**Review by sreya — COMMENTED** [review]
Seems fine but wouldn't this make more sense being integrated in the sdk? You could just add a variadic options parameter to `codersdk.New` and modify the transport on the HTTP client there.

**Comment by kylecarbs** [comment]
I didn't want to abstract the client just for this change, because it seems like a weird one.

**Comment by sreya** [comment]
Based on the issue though isn't the expectation that all commands accept an arbitrary list of headers?

**Comment by sreya** [comment]
Like I said it's fine but it's just weird we're introducing a new way that every command needs to instantiate a client. It's technically a bug to call `codersdk.New` directly now in `cli`. Also if any third party wants to use `codersdk` as a library they lose out on this functionality and have to write a similar wrapper. 

Also unless I'm missing something this PR only implements arbitrary headers for `login` is there some reason we're not addressing the rest of the commands in this PR?

**Comment by kylecarbs** [comment]
Nah, this just tests it against `login` but we could test it against arbitrary commands.

My argument for not exposing this functionality is that it's pretty weird and also trivial for someone else to implement if they want to do so.

**Review by sreya — APPROVED** [review]

**Pull request merged**
