### PR TITLE
fix: disable auto-create if external auth requirements aren't met

### LINKED ISSUE #12491: Bug: Launching a workspace with`mode=auto` does not check for required external authentication for the template
When using "Open in Coder" and selecting `mode=auto` the developer should still be prompted to do external authentication if that requirement was not met.

You get the expected outcome when you use `mode=form`

Screenshot 2024-03-08 at 4 27 01 PM

Related Coder Docs: https://coder.com/docs/v2/latest/admin/external-auth#require-git-authentication-in-templates
Running 2.8.4 Coderd

### PR DESCRIPTION
**Pull request by aslilac**
Closes #12491 

Basically, `mode=auto` should be ignored if a required auth provider is missing

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
I'm missing a test for this use case.

**Comment by aslilac** [comment]
> Will disabling this point the user to authenticate with the external provider and then auto create the workspace?

it'll just show them the normal form, and they'll have to click "create" when they've connected.

**Comment by aslilac** [comment]
ok, I've hit a weird block with this.

I can add `.skip` to the new test, and the entire rest of the test suite will pass. I can add `.only` to the new test, and it will run by itself and pass. but for some reason, in full runs, it causes _other tests_ to fail.

@BrunoQuaresma any ideas why? I tried with msw instead of mocking as well, but that had a similar problem.

**Comment by BrunoQuaresma** [comment]
@aslilac Unfortunately I don't 😢  and this is sort of related to the issue that I'm facing here https://github.com/coder/coder/pull/12597

**Review by BrunoQuaresma — APPROVED** [review]
I like the test and the new error helper function 👍

**Pull request merged**
