### PR TITLE
chore: update generated files after pnpm upgrade

### PR DESCRIPTION
**Pull request by dannykopping**
I'm unsure how `main` got into this state, but when running `make gen` in one of my branches it produces diffs in these files.

@coadler maybe you know? I guess this should've changed after https://github.com/coder/coder/pull/13843 so maybe our `make gen` target is buggy?

### CODE REVIEW

**Comment by dannykopping** [comment]
Not really sure why CI is failing.

**Comment by coadler** [comment]
Sorry about taking a bit to review, I think the reason it's failing is bc I neglected to update pnpm in CI. That should fix it

**Review by coadler — APPROVED** [review]

**Comment by dannykopping** [comment]
No worries @coadler 👍 
Any idea why CI is failing with this error?

```
 ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is absent
```

https://github.com/coder/coder/actions/runs/10143062920/job/28043671521?pr=14036

**Comment by coadler** [comment]
I think the bump from v8 -> v9 changed lockfile formats, so maybe that's what v8 errors with when it sees the new format?

**Comment by dannykopping** [comment]
Any idea how to resolve it?

**Comment by coadler** [comment]
https://github.com/coder/coder/blob/main/.github/actions/setup-node/action.yaml#L16 `8` -> `9` I think

**Comment by BrunoQuaresma** [comment]
I'm changing this again because the pnpm and node versions should be the same we use in the workspaces which are 8.14.0 for pnpm and v18.20.4 for node.

**Pull request merged**
