### PR TITLE
fix: Race when writing to a closed pipe

### PR DESCRIPTION
**Pull request by kylecarbs**
This is such an intermittent race it's difficult to track,
but regardless this is an improvement to the code.

```
==================
WARNING: DATA RACE
Write at 0x00c000502397 by goroutine 179:
  encoding/binary.bigEndian.PutUint16()
      /usr/local/goboring/src/encoding/binary/binary.go:108 +0x44c
  github.com/hashicorp/yamux.header.encode()
      /home/coder/projects/coder/coder/vendor/github.com/hashicorp/yamux/const.go:179 +0x3f1
  github.com/hashicorp/yamux.(*Stream).write()
      /home/coder/projects/coder/coder/vendor/github.com/hashicorp/yamux/stream.go:201 +0x349
  github.com/hashicorp/yamux.(*Stream).Write()
      /home/coder/projects/coder/coder/vendor/github.com/hashicorp/yamux/stream.go:158 +0x185
  storj.io/drpc/drpcwire.(*Writer).Flush()
      /home/coder/projects/coder/coder/vendor/storj.io/drpc/drpcwire/writer.go:85 +0xb9
  storj.io/drpc/drpcstream.(*Stream).sendPacket()
      /home/coder/projects/coder/coder/vendor/storj.io/drpc/drpcstream/stream.go:267 +0x227
  storj.io/drpc/drpcstream.(*Stream).Close()
      /home/coder/projects/coder/coder/vendor/storj.io/drpc/drpcstream/stream.go:478 +0x184
  github.com/coder/coder/peerbroker/proto.(*drpcPeerBroker_NegotiateConnectionClient).Close()
      <autogenerated>:1 +0x49
  github.com/coder/coder/peerbroker.Dial.func1.1()
      /home/coder/projects/coder/coder/peerbroker/dial.go:23 +0x48
  runtime.deferreturn()
      /usr/local/goboring/src/runtime/panic.go:436 +0x32

Previous read at 0x00c000502397 by goroutine 153:
  runtime.slicecopy()
      /usr/local/goboring/src/runtime/slice.go:295 +0x0
  io.(*pipe).read()
      /usr/local/goboring/src/io/pipe.go:59 +0x193
  io.(*PipeReader).Read()
      /usr/local/goboring/src/io/pipe.go:136 +0x64
  github.com/coder/coder/provisionersdk.(*readWriteCloser).Read()
      <autogenerated>:1 +0x76
  bufio.(*Reader).Read()
      /usr/local/goboring/src/bufio/bufio.go:236 +0x4da
  io.ReadAtLeast()
      /usr/local/goboring/src/io/io.go:331 +0xdd
  io.ReadFull()
      /usr/local/goboring/src/io/io.go:350 +0x12f
  github.com/hashicorp/yamux.(*Session).recvLoop()
      /home/coder/projects/coder/coder/vendor/github.com/hashicorp/yamux/session.go:483 +0xf1
  github.com/hashicorp/yamux.(*Session).recv()
      /home/coder/projects/coder/coder/vendor/github.com/hashicorp/yamux/session.go:462 +0x2e
  github.com/hashicorp/yamux.newSession.func1()
      /home/coder/projects/coder/coder/vendor/github.com/hashicorp/yamux/session.go:113 +0x39
```

### CODE REVIEW

**Comment by kylecarbs** [comment]
Yup, I've come to the same conclusion! Thanks for the investigation @mafredri 🥳

**Comment by mafredri** [comment]
No prob! And looks like I was wrong about `write` not being protected, it seems to be locked here: https://github.com/hashicorp/yamux/blob/0bc27b27de87381b58e35462a8dcbd69040279c1/stream.go#L154-L155, so that leaves the third use from session.

**Comment by kylecarbs** [comment]
@mafredri if I change https://github.com/storj/drpc/blob/main/drpcwire/writer.go#L85 to copy the buffer with `buf[:]`, it works!

**Comment by kylecarbs** [comment]
@mafredri I changed this to use `net.Pipe` (which is a cleaner impl), and I haven't been able to reproduce the race since 🤔🤔🤔

**Comment by kylecarbs** [comment]
I ran this *a lot* without the failure..... seems to work!

**Review by mafredri — APPROVED** [review]
Awesome refactor, `net.Pipe` made this beautiful!

I think if you can't repro, this is good to 🚀.

Meanwhile, I did make a PR about that one discovery: https://github.com/hashicorp/yamux/pull/100

**Pull request merged**
