### PR TITLE
feat(site): allow any file extension on template editor

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
- Accepts any file extension on the template editor
- Keep the version updated in the URL so the page does not lose state
- Keep the active file in the URL so it is "shareable" and does not lose state on refresh

https://github.com/coder/coder/assets/3165839/1f70a74f-907a-4bbb-bffc-f1e63d4ad04f

https://github.com/coder/coder/assets/3165839/c5c25b6a-60a8-4cf9-ba63-abe8f83e9e8a

@matifali I really would appreciate a rough QA on this 🙏

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
I still need to refactor the TemplateFilesPage.

**Review by mtojek — COMMENTED** [review]
Thoughts based on videos you posted:

1. Could we join directories without files? For example, `usr/share/keyrings` instead of: 
Screenshot 2024-02-06 at 16 09 41

Definitely, less clicking.

2. Can you try with relatively long names and deep, deep directories?

3. Can we grey out hidden files, so ones starting with a dot?

**Comment by BrunoQuaresma** [comment]
1. I like the idea! Let me see if I can extend this component to support this.
2. This is going to generate horizontal scrolling like happens with VSCode and any IDE editor. Thoughts?
3. If by "hidden files" you mean folders or files that start with a dot, we can do it easily.

**Comment by mtojek** [comment]
> This is going to generate horizontal scrolling like happens with VSCode and any IDE editor. Thoughts?

It might be inevitable in this case, not sure if there is a better way to show it in UI :)

**Review by mtojek — APPROVED** [review]
Thanks for addressing feedback!

**Review by matifali — APPROVED** [review]

**Pull request merged**
