### PR TITLE
feat: add minimal frontend for creating workspaces from specific template versions

### LINKED ISSUE #7157: template editor: better way to test "WIP" templates
Today, the template editor is great for small changes, but I still prefer to use the local flow for more involved changes or when I want to test my work against a workspace.

Here are a few reasons why:
- Every time I make a change, it exits the template editor. This makes it hard to "test" if something worked.
- While I can publish to a non-promoted version, it's not trivial to test that version on a workspace. 
  - Sometimes I want to test a template against a new workspace (e.g. fresh startup script). There's no way to create a new workspace with a non-promoted version
  - With existing workspaces, instead of clicking "update," I will have to click "change version" and pick the new (non-promoted) version I pushed.

## Some ideas

- Allow admin to create "test workspace" from the template editor using the WIP version (doesn't even need to be "published").
  - Perhaps Coder automatically cleans up these test workspaces?
- Some way to stay in the editor partially solves this (related #7153)

### LINKED ISSUE #9415: Allow template admins to create a workspace from any version
Helpful for iterating on templates. Currently you can only create a workspace from the default version, but template admins can switch versions once created. We should remove that unnecessary step, and allow creating a workspace from any version available.

Related to #9243 and #9346

### PR DESCRIPTION
**Pull request by aslilac**
Closes #9415
Closes #7157 

This is super barebones, but I wanted to have _some_ form of this working end-to-end before heading out for the long weekend, so here it is for people to look at!

- Removes some patching that was holding us over while implementation continued
- Adds a `version` search param to the "new workspace" page, which allows specifying the ID of a particular template version
- Uses the new backend support from #9471 to create the workspace

This change does not yet expose a "version selector" of any kind to the user. We probably want to add that still, and it shouldn't be to hard, but this is a useful upgrade as is and I think building this out further incrementally will work just as well.

### CODE REVIEW

**Comment by bpmct** [comment]
This is only available to template admins, right? A normal user cannot access "change version" so they shouldn't be able to create from a version.

**Comment by aslilac** [comment]
> This is only available to template admins, right? A normal user cannot access "change version" so they shouldn't be able to create from a version.

I haven't really looked into the permissions side of this at all yet. I forgot this week was a bit short, so I only had today to try to get something working.

**Comment by bpmct** [comment]
What happens if parameters are required for the workspace?

**Comment by aslilac** [comment]
> What happens if parameters are required for the workspace?

I didn't actually test it yet, but from looking at the code "auto build" should fail and redirect to the normal workspace creation form

**Comment by bpmct** [comment]
> normal workspace creation form

Gotcha. And in that case, it won't persist the version it wants to use, right?

**Comment by aslilac** [comment]
> > normal workspace creation form
> 
> Gotcha. And in that case, it won't persist the version it wants to use, right?

It will! The parameter isn't exposed in the UI, but the state machine will remember it!

**Comment by bpmct** [comment]
Ahh gotcha! I think we should probably show a `lil component that, even if not changeable, shows that we are respecting that version from the state machine. If it's not in the machine (and its using the default), we just hide that component in the form. I think its good visual feedback that the user is on the right track and Coder didn't bug out.

**Comment by aslilac** [comment]
good point! that sounds like a nice improvement.

**Comment by aslilac** [comment]
Screenshot 2023-09-05 at 4 12 15 PM

**Review by BrunoQuaresma — APPROVED** [review]
LGTM

**Comment by BrunoQuaresma** [comment]
Minor thing: Should we display the version name instead of the ID? I think most of the users will not care about or recognize the ID.

**Comment by aslilac** [comment]
> Minor thing: Should we display the version name instead of the ID? I think most of the users will not care about or recognize the ID.

long term yes, but the only information the page has available to it right now is the id. once we actually load version information and have the names available, we should display those instead.

**Comment by aslilac** [comment]
this is ready to merge, but this test failure is unrelated to my changes and the tests seem to be failing pretty consistently :\

**Pull request merged**
