### PR TITLE
Sidebar icons

### PR DESCRIPTION
**Pull request by antonkor**
Added sidebar icons to all inner items. 

related [ #109](https://github.com/coder/coder.com/issues/109)

### CODE REVIEW

**Comment by ammario** [comment]
I think it's better to leave them blank since the sidebar looks awkward to me with too many duplicate icons.

**Comment by antonkor** [comment]
sorry. pushed this bit of code into the wrong old branch. but the bit of code i pushed should work as intended. 
related: https://github.com/coder/coder.com/pull/119

just curious, should i have made a new one?

**Comment by ammario** [comment]
@antonkor yeah, that's chill.

**Comment by ammario** [comment]
@antonkor, you'll probably want to rebase away the old commits. I assume you just want to merge https://github.com/coder/coder/pull/3474/commits/2f16280e8aedb377174408c32ad9949b8f01ccab?

**Pull request closed without merging**
