### PR TITLE
chore(dogfood): automatically login coder cli in dogfood workspaces

### PR DESCRIPTION
**Pull request by matifali**
This will auto-authenticate a user with coder in their dogfood workspace.

### CODE REVIEW

**Review by mafredri — APPROVED** [review]
Hmm. I wonder if we should do this via envs? Since envs override the config in e.g. `~/.config/coderv2`, this might lead to unexpected behavior.

But also, overwriting config in `~/.config/coderv2` may _also_ lead to unexpected behavior.

Say I've logged in to a different coder instance, but every restart these settings are overridden (env) or overwritten. It would be interesting to introduce this mechanism into the agent.

Something like:

1. Agent checks `[config_dir]/session`
2.
	- If missing, write `session`, `url` and `.agent_managed_login` with same modified timestamp as session/url
	- If present, verify timestamp against `.agent_managed_login` and if they're the same, update `session` and `url`
	- If present but diverge, do nothing

Just an idea off the top of my head. Not sure what the right approach would be.

Then again, the envs are probably fine for _now_.

**Comment by matifali** [comment]
@mafredri Yes. Thanks for the idea. I faced this as this will automatically invalidate existing auth for any other coder deployment. I guess going the agent way will need some backend work to be done first.

**Comment by matifali** [comment]
@mafredri writing `[config]/.workspace_session`, `[config]/.workspace_url` from terraform will likely need updating coder terraform provider if we want it to be a native feature.
Something like
```hcl
resource coder_agent {
	auto_login = true
}
```
And this will enable coder agent to automatically create the above session files given, we support fallback in cli.

**Comment by ammario** [comment]
As @mafredri suggested, this change would mess up my workflow where I'm usually authenticated to my development deployment.

That said, automatically logging in the user is a nice default since most of our users aren't developing Coder itself. The auto-login default should apply without template modifications. Using some kind of hierarchy of session token locations where the agents' is last is a good idea.

**Comment by matifali** [comment]
@ammario sure. Let us close this and move the discussion to a new issue.

**Pull request closed without merging**
