### PR TITLE
refactor(site): Improve workspaces filtering

### LINKED ISSUE #7586: Remove the WS filter owner:me when user is Owner
As an admin of Coder, I would like to see as default all workspaces created, not only mine. Each time I enter to workspaces tab, need to the delete this filter... Isn't that of an issue, but it's annoying

### LINKED ISSUE #7626: Improve workspace filter
I think our filters in the UI are quite complex and the user kinda has to spend some time trying to figure out how it works and what fields can be used. Thinking on this, I think we can make filtering more easier by allowing the user to select/type the value for each field that can be used for filtering. So I mocked a design where the filter is not filtering anything and another one with some filled values.

image

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
What is included:
- Makes filtering easier by adding additional controls. Close https://github.com/coder/coder/issues/7626
- Remove the default "owner:me" filter since members only can see their own workspaces. Close https://github.com/coder/coder/issues/7586
- Do not show an alert on the page if the error is related to the filter
- Do not re-fetch the workspace list if there is a filter error

Demo:
https://github.com/coder/coder/assets/3165839/1ecafeaa-4b1e-44ea-bc65-9335416b1617

PS: Tests are on the way but I want to validate this feature before writing them.

### CODE REVIEW

**Review by bpmct — CHANGES_REQUESTED** [review]
Looks awesome! This is a huge improvement to our current filtering.

I noticed a few things. 

1. I noticed I have to press enter to search now. This doesn't feel natural, compared to the previous behavior that searches with a debounce
   
    https://github.com/coder/coder/assets/22407953/00a92a3d-08f0-44b2-8f5e-23f3b824b333


3. Do you think we should change "Canceling action" and "Canceled action" to "Canceling" "Canceled" and use a grey dot?
    Screenshot 2023-05-25 at 10 40 33 AM

3. The workspaces page shows "All users" workspaces by default, which is a change in behavior and makes it difficult for admins to reach their workspaces. What do you think about changing it to show `owner:me` by default, like the original?
4. ✅ Confirmed this works as expected with "template admin" and "user admin"
5. Searching on "page 2" with filters will not return to page 1 to find a result. Do you think we should add a test for this since it happened with our previous pagination behavior (then we fixed it?) I am concerned future refactors may not have this.

      https://github.com/coder/coder/assets/22407953/c9324bb0-dd5f-45a8-aadd-790e31719006

6. When a final workspace is taken off page 2, the user is not taken to page 1 and it says there are no results

    https://github.com/coder/coder/assets/22407953/cb89c0c5-ca81-481a-a3f0-ec369b2b162a

7. Status: deleting doesn't seem to work.

    https://github.com/coder/coder/assets/22407953/1e71b817-af89-433d-aca7-7459dbec59f7

8. Can you check all of the statuses to make sure the filter works as expected? I am concerned there are more that do not filter, like "Deleting"

9. What do you think about adding "All statuses" and "All templates" as dropdown item? I don't think it is necessary but makes it a bit more clear you can unselect.

10. Status "stopping" shows me a failed workspace for some reason.

    https://github.com/coder/coder/assets/22407953/a70a1b6f-1276-4fea-a7db-26bef764be76

I used `coder scaletest create-workspaces --template=docker --concurreny=30 --count=100` to test this with a lot of workspaces and users.

Nice to have additional enhancements:

- Show # of results returned from a filter (e.g. I'd love to know how many workspaces are pending, or failed, or running)
- Somewhere to link to docs for advanced search syntax (e.g. has-agent)
- Add this design to the audit log & templates page. Audit log would be the most beneficial

**Comment by BrunoQuaresma** [comment]
@bpmct I missed these:

> Nice to have additional enhancements:
Show # of results returned from a filter (e.g. I'd love to know how many workspaces are pending, or failed, or running)
Somewhere to link to docs for advanced search syntax (e.g. has-agent)
Add this design to the audit log & templates page. Audit log would be the most beneficial

> Show # of results returned from a filter (e.g. I'd love to know how many workspaces are pending, or failed, or running)

This is a good one, let me think if there is an easy way to do this

> Somewhere to link to docs for advanced search syntax (e.g. has-agent)

This is a hard one.... but I will also think about it.

> Add this design to the audit log & templates page. Audit log would be the most beneficial

Totally, we can do this after this get merged.

**Comment by BrunoQuaresma** [comment]
I found another bug: If I select a user in the filter, and after changing it in the search input, it does not update the dropdown filter.

**Review by rodrimaia — APPROVED** [review]
LGTM

**Review by rodrimaia — APPROVED** [review]

**Review by bpmct — APPROVED** [review]

**Pull request merged**
