### PR TITLE
Update templates.md doc

### PR DESCRIPTION
**Pull request by endingwithali**
missing word

### CODE REVIEW

**Comment by endingwithali** [comment]
I have read the CLA Document and I hereby sign the CLA

recheck

**Review by bpmct — APPROVED** [review]
nice

**Comment by bpmct** [comment]
@endingwithali i think it didn't like your CLA comment.

**Comment by endingwithali** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by endingwithali** [comment]
recheck

**Pull request merged**
