### PR TITLE
chore: add pull_request_template.md

### PR DESCRIPTION
**Pull request by matifali**
# PR Summary

Adds a pull request template

## PR Context

This will allow us to have meaningful pull requests and will hopefully make them easier to review or understand.

## PR Checklist

- [x] [PR has a meaningful title](https://coder.com/docs/v2/latest/CONTRIBUTING#commit-messages)
    - Use the present tense and imperative mood when describing your changes
- [ ] Summarized changes
- [x] This PR is ready to merge and is not.
    - If the PR is a work in progress, please [mark it as draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) or add the prefix `WIP:` or `[ WIP ]` to the beginning of the title.
- [ ] **[Breaking changes](https://coder.com/docs/v2/latest/CONTRIBUTING#breaking-changes)**
- [Experimental flags(s) needed](https://coder.com/docs/v2/latest/cli/server#--experiments)
    - [x] None   
    - [ ] Experimental flag name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed
        - [ ] Issue filed: 
    - **OR**
    - [ ] Documentation included. 
- **Testing**
    - [x] N/A or can only be tested interactively 
    - **OR**
    - [ ] Make sure you've added a new test if existing tests do not effectively test the code changed.

### CODE REVIEW

**Comment by ammario** [comment]
I've historically been against PR templates because they discourage small contributions and, even with medium sized PRs, only a portion of the template is relevant.

**Comment by matifali** [comment]
@ammario do you suggest any improvement or simplification?

**Comment by ammario** [comment]
From Ben I think the main issue you're trying to solve is making it easier to write documentation and release notes. Does that match with you?

**Comment by matifali** [comment]
@ammario Yes, this is the motivation. Another reason is that if we check old PRs, It will make it easier to determine what was changed instead of checking empty body PRs for file diffs.

**Comment by ammario** [comment]
Maybe we can try solving this with some gentle nudges. If you think a merged PR has insufficient documentation in the future could you ping me?

**Comment by matifali** [comment]
@ammario Sure, we can just close this for now, okay?

**Comment by ammario** [comment]
Ok. Thank you for your work here.

**Pull request closed without merging**
