### PR TITLE
feat: mask coder login token to enhance security

### PR DESCRIPTION
**Pull request by michaelbrewer**
Masks the coder token when pasting it after the `coder login` . 

When doing public demos of coder this can be an awkard moment...

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@kylecarbs  - not sure if i should add some unit tests for this, but i did manually validate that the token still works and is not shown

**Review by ericpaulsen — APPROVED** [review]
in a future state, we should display `***` characters, for a better UX.

**Comment by matifali** [comment]
@ericpaulsen IIRC, it was the original behavior, and the token was shown after some customer feedback.

**Comment by coadler** [comment]
Yeah, hiding the input was changed because users couldn't tell if they were actually pasting into the box or not. I'm in favor of changing it back to secret until we can add in replacing the text with asterisks.

**Comment by michaelbrewer** [comment]
@coadler  - there are various other places where `Secret` is used in a prompt, so i might be a generic solution for those cases too.

**Comment by coadler** [comment]
> @coadler - there are various other places where `Secret` is used in a prompt, so i might be a generic solution for those cases too.

Yeah, definitely.

**Comment by michaelbrewer** [comment]
would be nice to have this resolved for when i do demos.

**Comment by michaelbrewer** [comment]
@ericpaulsen  is there a decision on how to handle the secret being printed?

**Review by kylecarbs — APPROVED** [review]

**Pull request merged**
