### PR TITLE
chore: de-flake TestWorkspaceAgent_Metadata

### PR DESCRIPTION
**Pull request by ammario**

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
Why is it important that we check the duration that occurred?

**Comment by mafredri** [comment]
This still seems to flake, the merge to main had such a flake.

**Comment by ammario** [comment]
@kylecarbs — it's not critical, and not worth a flake.

@mafredri — I see. We can remove these time checks altogether, disable them in CI, or maybe just disable t.Parallel here if in CI and Windows. What do you think?

**Comment by mafredri** [comment]
> @kylecarbs — it's not critical, and not worth a flake.
> 
> @mafredri — I see. We can remove these time checks altogether, disable them in CI, or maybe just disable t.Parallel here if in CI and Windows. What do you think?

Any of those sounds reasonable to me. I think as far as parallelism is concerned only linux runners are “safe”. Maybe another option is to skip if short test?

**Pull request merged**
