### PR TITLE
chore: fix pnpm lock version

### PR DESCRIPTION
**Pull request by BrunoQuaresma**

### CODE REVIEW

**Comment by matifali** [comment]
I think you are using pnpm v8, @dannykopping recently fixed this in https://github.com/coder/coder/pull/14036

**Review by kylecarbs — APPROVED** [review]

**Review by matifali — DISMISSED** [review]
This will cause CI to fail. See #14036

**Comment by BrunoQuaresma** [comment]
@matifali I'm using the pnpm version from the workspace that is 8.14.0, and I don't look like the CI is failing because of it.

**Comment by BrunoQuaresma** [comment]
I'm checking how to make things consistent in CI and workspace. Right now, WS is not using the right versions.

**Comment by matifali** [comment]
But we have moved to v9. 
cc @coadler

**Comment by BrunoQuaresma** [comment]
I'm still figuring out why the workspace is not reflecting the changes in the Docker file.

**Pull request closed without merging**
