### PR TITLE
refactor(site): use a pie chart instead of linear chart for app usage

### LINKED ISSUE #13627: Use pie chart for app usage in template insights
We currently use bars to show the usage of coder apps in the template insights page. These bars represent the percentage of total activity that was recorded through each app. Bar graphs/displays are not often used to express distribution so it's a little hard to understand:

Screenshot 2024-06-20 at 2 19 17 PM

I propose we switch it to a pie chart with tooltips explaining they're a percentage of usage. Much easier to see that they add to 100%:

Screenshot 2024-06-21 at 11 01 29 AM

We could also add app icons to the slices that are large enough to hold them, while keeping the "legend" as shown on the right. 

Yielding to your better eye for design here @BrunoQuaresma.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Before:
Screenshot 2024-07-01 at 15 25 39

After:
Screenshot 2024-07-01 at 15 23 39

Close https://github.com/coder/coder/issues/13627

### CODE REVIEW

**Comment by matifali** [comment]
IMO, a pie chart with more vibrant colors will look better. The current color maps have too similar colors. 
image

Agreeing with @aslilac, I think bar charts looks better,
image

**Comment by BrunoQuaresma** [comment]
@matifali, colors need to also have a sufficient contrast in a pie chart so people with vision limitations can understand it. Currently, we use bar charts horizontally, which, in my opinion, is better than vertical bar charts.

**Review by aslilac — COMMENTED** [review]
as pie charts go, it looks fine, but I'm not convinced a pie chart is actually the right choice here. I left a [comment on the motivating issue](https://github.com/coder/coder/issues/13627#issuecomment-2200816960) but I think a pie chart is a downgrade here.

**Comment by BrunoQuaresma** [comment]
@aslilac I pinged @stirby to help us to take a decision on this.

**Comment by stirby** [comment]
I [left a comment](https://github.com/coder/coder/issues/13627#issuecomment-2204277583). I do think the current pie chart is a downgrade, we need more contrast and better visual association with the apps. The vertical bar would be a larger downgrade IMO.

We should continue the discussion in the issue.

**Pull request closed without merging**
