### PR TITLE
feat: implement callback authorisation for cli tokens

### PR DESCRIPTION
**Pull request by bartonip**
Oops in the process of rebasing I've accidentally closed #9502

### CODE REVIEW

**Comment by bartonip** [comment]
1. we like to avoid polling early in a design to minimize HTTP log-spam and other per-HTTP overhead
2. websockets/SSE is pretty easy for us as we already use it in many places throughout the codebase
3. websocket/SSE simplifies login session cleanup as we know exactly when the client disappears and can `defer delete()`. Accordingly, it mitigates the DoS attack value of the endpoint.

_Originally posted by @ammario in https://github.com/coder/coder/issues/9502#issuecomment-1772961630_

Hey @ammario,
Just thought I'd provide my thoughts on the above here.
1. I may be wrong depending on how Coder server is designed, but I would believe that per-HTTP overhead would be minimal for a single in-memory value lookup. HTTP log-spam would be minimal as the polling rate would most likely be >1000ms. We can put in mitigations for this easily.
2. Great! If SSE is used, I would gravitate towards that because websockets seems like a pandora's box because of the reasons below.
3. Regarding DoS attack value, wouldn't opening a websocket INCREASE the chance of DoS and lower the difficulty of such an attack as the attacker now simply has to exhaust available sockets on the Coder server rather than overwhelming the Coder server with requests which would require 1-2 orders of magnitude more requests. 

I would be happy to implement as a SSE as websockets seems risky. (As does SSE however the API is basically designed to handle a bajillion connections anyway).

**Comment by bartonip** [comment]
Just on third thought- if we are now not having the browser deliver the key directly to the CLI and the CLI is receiving the key from the server. We need to implement a second factor to ensure that the user knows which session they are authenticating.

For example, a user is authenticating a legitimate request for access to the CLI. The user clicks on a phishing email which has a pre-formulated `/cli-auth?sessionid=${sessionId}` link. With both of these tabs open, the user does not know which is the legitimate request.

If we do it this way, we will need a second factor to ensure that the user only authenticates sessions they intend. 

The authentication flow needs to be as below:
1. User runs `coder login`
2. User's browser is open to the `/cli-auth` page, a OTP is displayed in the CLI.
3. User pastes the CLI into an input box in the `/cli-auth` page.
4. The session ID and OTP is compared to ensure correctness.
5. Server issues API key to SSE channel that the CLI is listening to.

**Comment by ammario** [comment]
Sorry for taking so long in getting back to you. We had an offsite last week and this week I've been feeling unwell.

Note: I haven't benchmarked my claims. I'm going off intuition and experience with scaled-out Coder deployments. A lot of my anti-polling perspective is based on our experiences delivering v1, where we had a lot of issues due to an excess culture of polling. By pushing this change towards SSE/WebSockets, we're creating a strong precedent and pattern for future ones.

---


> I may be wrong depending on how Coder server is designed, but I would believe that per-HTTP overhead would be minimal for a single in-memory value lookup. HTTP log-spam would be minimal as the polling rate would most likely be >1000ms. We can put in mitigations for this easily.

Right now, there is a significant per-request overhead in DB queries and rego evaluation for auth. We're working towards reducing the overhead but it has ailed us for the past year or so.

> Regarding DoS attack value, wouldn't opening a websocket INCREASE the chance of DoS and lower the difficulty of such an attack as the attacker now simply has to exhaust available sockets on the Coder server rather than overwhelming the Coder server with requests which would require 1-2 orders of magnitude more requests.

This is related to the first point. Due to our per-request overhead, I'd wager a persistent websocket/SSE is less resource-intensive than a 1s poll. There's also more GC pressure with polling.

---

I think @mafredri would be a good person to review the code.

**Comment by mafredri** [comment]
> The authentication flow needs to be as below:
> 
> 1. User runs `coder login`
> 2. User's browser is open to the `/cli-auth` page, a OTP is displayed in the CLI.
> 3. User pastes the CLI into an input box in the `/cli-auth` page.
> 4. The session ID and OTP is compared to ensure correctness.
> 5. Server issues API key to SSE channel that the CLI is listening to.

This sounds a lot like [OAuth 2.0 Device Authorization Grant](https://datatracker.ietf.org/doc/html/rfc8628). I think it would be a good fit considering where `coder login` may be used. Are you interested in changing the implementation to this @bartonip?

The steps you've outlined adds a bit more burden on the user, via having to enter the user code manually. The RFC, however, does have an optimization for that via [`verification_uri_complete`](https://datatracker.ietf.org/doc/html/rfc8628#section-3.3.1). It would allow the "`/cli-auth`"-page to receive and display the code (for visual confirmation) instead of requiring user input. I imagine we could utilize this if Coder is running on the local machine and we are able to automatically open the browser.

We should also decide on a length for the user code, and add rate-limiting to prevent abuse (the RFC has a discussion on this). User codes of 8 characters seem to be pretty common.

PS. Regarding polling vs SSE, I think SSE is preferable for both response time and reduced server load, but I'd say polling is also acceptable. We shouldn't need to deal with rego or any of our existing auth layers for this, but due to replicas, we would still need to hit the database on each poll vs doing it in memory.

**Comment by bartonip** [comment]
> This sounds a lot like [OAuth 2.0 Device Authorization Grant](https://datatracker.ietf.org/doc/html/rfc8628). I think it would be a good fit considering where `coder login` may be used. Are you interested in changing the implementation to this @bartonip?

I'd be happy to implement OAuth, would be good if I could have a couple minutes to pair with yourself @mafredri just to orient me to the codebase.

I am still of the opinion that the reduced complexity of polling is better than SSE but happy to implement it whichever way you like. 

That said- I am happy to work on OAuth first and worry about the code transmission later.

**Pull request closed without merging**
