### PR TITLE
ci: execute enterprise and non-enterprise e2e tests concurrently

### PR DESCRIPTION
**Pull request by aslilac**
- Run the non-enterprise tests and the enterprise tests in a matrix, so that they can be parallelized.
- We can skip installing a ton of stuff by just running `make gen/mark-fresh`, further speeding things up. If things are out of date, that'll get caught by the dedicated gen job that we already have.

Skipping `go install` saves about a minute, and running them concurrently can save like 2-10 minutes depending on lots of factors. Generally gonna be more on the 2 side, but still!

### CODE REVIEW

**Comment by aslilac** [comment]
CI is failing with...

```
==> Tests failed
26 passed
4 failed
  site/e2e/tests/app.spec.ts › app
  site/e2e/tests/outdatedAgent.spec.ts › ssh with agent v0.27.0
  site/e2e/tests/outdatedCLI.spec.ts › ssh with client v0.27.0
  site/e2e/tests/webTerminal.spec.ts › web terminal
1 timed out
  site/e2e/tests/updateWorkspace.spec.ts › update workspace, new required, mutable parameter added
```

...and when I run the tests in dogfood I get...

```
==> Tests failed
24 passed
4 failed
  site/e2e/tests/groups/removeGroup.spec.ts › remove group
  site/e2e/tests/app.spec.ts › app
  site/e2e/tests/outdatedAgent.spec.ts › ssh with agent v0.27.0
  site/e2e/tests/webTerminal.spec.ts › web terminal
3 timed out
  site/e2e/tests/updateWorkspace.spec.ts › update workspace, new optional, immutable parameter added
  site/e2e/tests/startWorkspace.spec.ts › start workspace with ephemeral parameters
  site/e2e/tests/updateWorkspace.spec.ts › update workspace, new required, mutable parameter added
```

or sometimes something more like...

```
==> Tests failed
28 passed
3 failed
  site/e2e/tests/app.spec.ts › app
  site/e2e/tests/outdatedCLI.spec.ts › ssh with client v0.27.0
  site/e2e/tests/outdatedAgent.spec.ts › ssh with agent v0.27.0
```

... and when I run the tests on macOS...

```
==> Tests failed
25 passed
2 failed
  site/e2e/tests/outdatedAgent.spec.ts › ssh with agent v0.27.0
  site/e2e/tests/outdatedCLI.spec.ts › ssh with client v0.27.0
4 timed out
  site/e2e/tests/externalAuth.spec.ts › external auth device
  site/e2e/tests/app.spec.ts › app
  site/e2e/tests/updateWorkspace.spec.ts › update workspace, new optional, immutable parameter added
  site/e2e/tests/updateWorkspace.spec.ts › update workspace, new required, mutable parameter added
```

**Comment by aslilac** [comment]
this inconsistency is definitely a problem, so I'm gonna work on ironing out as many of these flakes as I can today 😄

**Review by Emyrk — APPROVED** [review]
Is the secret already set on the github side?

**Comment by aslilac** [comment]
> Is the secret already set on the github side?

yes!

**Pull request merged**
