### PR TITLE
chore: k8s example persistence & coder images

### PR DESCRIPTION
**Pull request by ericpaulsen**
this PR looks to address @ammario's feedback in #3588 by adding persistence to our k8s example template.

it also removes the VS Code dev container images in favor of [Coder's enterprise images](https://github.com/coder/enterprise-images). The dev container images used `/home/vscode`, which contained shell scripts/customizations that would be wiped with a `/home/vscode` volume mount.

open to thoughts/feedback on removing the dev container images.

### CODE REVIEW

**Review by ammario — APPROVED** [review]
Thanks for knocking this out. I didn't test it, but I assume you did. Feel free to merge if that's the case.

**Comment by ammario** [comment]
And, I do think it's odd how there are multiple containers. That seems like a niche use case.

**Comment by ericpaulsen** [comment]
> And, I do think it's odd how there are multiple containers. That seems like a niche use case.

i agree - i originally considered reducing it to one container. i'll push commit reflecting this, and also include `code-server` in the template (something we should do for all of our examples).

**Comment by bpmct** [comment]
> And, I do think it's odd how there are multiple containers. That seems like a niche use case.

This template is called `kubernetes-multi-service` so we'll need to change the name to reflect that it's no longer highlighting that use case.

I also noticed disk size & controls was removed. Was this to prevent breaking changes?

**Pull request merged**
