### PR TITLE
fix: remove connected button

### PR DESCRIPTION
**Pull request by kylecarbs**
It didn't make a lot of sense in current form. It will when we improve autostop.

### CODE REVIEW

**Review by f0ssel — APPROVED** [review]

**Comment by BrunoQuaresma** [comment]
This part of the code has been quite fragile, and I'm wondering if we should have added tests to ensure the correct behavior before merging it.

**Comment by kylecarbs** [comment]
Since this is just removing I'm less concerned about that. We can manually test on dev before release.

**Comment by BrunoQuaresma** [comment]
My concern is more about future changes and making sure our future selves remember what the correct behavior should be.

**Comment by BrunoQuaresma** [comment]
I'm being extra cautious here because we've already introduced a good number of bugs in this component with just simple changes.

**Pull request merged**
