### PR TITLE
feat: archive template versions to hide them from the ui

### LINKED ISSUE #9478: Delete/purge old template versions
A user has requested to add the ability to delete or purge old versions of a template.

## Motivation 
Sometimes an old version of the template can be unusable due to many factors such as the docker image it refers doesn't exist anymore or have been renamed etc.

## Solution
In such cases, when the old versions are practically unusable it's good to allow deleting them from the CLI and UI
e.g., 

```shell
coder templates version delete VERSION_NAME
```

Originally requested in: https://github.com/coder/coder/issues/8307#issuecomment-1664277865

### PR DESCRIPTION
**Pull request by Emyrk**
Moved to https://github.com/coder/coder/pull/10179

# What this does

Allows "archiving" template versions to clean them up from the UX. By default archived are not listed when calling `/versions` for a template. This action is reversible. Archived versions cannot be promoted or used in workspace builds.

Template versions that are in use or the current active template version cannot be archived.

Closes https://github.com/coder/coder/issues/9478

# Cli Commands

## Archive a template

```shell
# Archive all failed template versions for the template 'docker'
$ coder templates archive docker
# Archive all unused template versions
$ coder templates archive docker --all
```

Screenshot from 2023-10-09 18-21-59

## Archive a template version

Archive/unarchive specific versions.

```shell
# Archive
$ coder templates versions archive docker strange_khorana9
Version strange_khorana9 archived at Oct  9 18:22:41


# Unarchive
$ coder templates versions unarchive docker strange_khorana9
Version strange_khorana9 unarchived at Oct  9 18:22:41
```

# Future Work

- Allow the UI to see archived versions with some toggle
- Allow UI to archive/unarchive versions

# Open issues

- Deleted workspaces "reserve" a template version from archiving.

### CODE REVIEW

**Review by johnstcn — CHANGES_REQUESTED** [review]
This is too large a PR to review well in its current state. Could you please break it up into a few smaller ones?

Suggestion (but up to you):
- Database-related changes
- API/CLI-related changes
- Other misc plumbing as required, golden files, etc.

I also see changes relating to `ExternalAuth` in this PR, which I don't believe are correct.

**Comment by Emyrk** [comment]
@johnstcn the external auth stuff is not my change... I merged in `main` and now I am seeing a lot more diffs. Will figure out what happened... The merge worked without any conflict, didn't expect this :thinking:

**Comment by Emyrk** [comment]
The diff before was wildly inaccurate, I am unsure what happened there. I merged with `main` again and now the diff is correct.

I can break this up though

**Comment by johnstcn** [comment]
Yeah I have no clue what went on with the diff!

> I can break this up though

Please do! I know it's annoying to do, but smaller diffs are easier to review.

**Comment by Emyrk** [comment]
Moved to https://github.com/coder/coder/pull/10179

**Pull request closed without merging**
