### PR TITLE
feat: Redesign workspaces page

### PR DESCRIPTION
**Pull request by kylecarbs**
image

As part of redesigning the workspaces page, I updated the theme to dark mode and removed overrides resolving https://github.com/coder/coder/issues/1449. There's a lot of work that can be done here to improve, but this is a good start!

I've checked all pages to ensure nothing is bugged/broken, and it all looks good!

A text input will be added in the future to allow for filtering. This will work similarly to GitHub's issue filters: `owner:kylecarbs`, `status:running`, `is:outdated`, etc.

I proposed initially that workspaces be nested under templates, but that provided a restrictive view for admins. Admins and managers should get a full view of their Coder deployment from the workspaces page, which they now can!

Todo
- [x] Write some tests
- [x] Remove the old flow via templates
- [x] Empty view 🔍
- [x] Get some feedback on the UI
- [x] ~Maybe pagination? Might do that in another PR~

### CODE REVIEW

**Review by code-asher — COMMENTED** [review]
Looks good to me so far!  All the pages look great but I think something needs to be updated for the stories since they are all throwing errors.

**Review by Kira-Pilot — APPROVED** [review]

**Review by code-asher — COMMENTED** [review]
I like the default look of the field input labels.  The dialogs looked a bit better before IMO but definitely still usable (I like the reset password dialog though).

The margins component might need a background color removed or something, right now it has white text on a gray background https://www.chromatic.com/test?appId=624de63c6aacee003aa84340&id=62828332ad84ca004a3e0e03

Very handy we can see all the different workspace states in Chromatic!

Edit: this one seemed a bit strange to me as well, is that a disabled button? https://www.chromatic.com/test?appId=624de63c6aacee003aa84340&id=62828332ad84ca004a3e0ded
Not sure if this matters but should this be white? https://www.chromatic.com/test?appId=624de63c6aacee003aa84340&id=62828332ad84ca004a3e0dfd

**Review by greyscaled — COMMENTED** [review]
One quick question I thought I'd submit review for right away since it's simple.

Following up with other items shortly.

**Review by code-asher — APPROVED** [review]

**Review by presleyp — APPROVED** [review]
Looks good, I have a couple important but small comments about the status bar and then some stylistic things you can decide on

**Pull request merged**
