### PR TITLE
ci: delete old workflow runs

### PR DESCRIPTION
**Pull request by matifali**
This cleans up old workflow runs for `pr-cleanup.yaml` as this action runs on every PR close event, so we have a lot of failed workflow logs as it tried to clean up every pr, and we do not have deployments for every pr.

More workflows can be added by appending to the list e.g.
`delete_workflow_pattern: ["pr-deploy.yaml", "pr-cleanup.yaml"]`

### CODE REVIEW

**Comment by ammario** [comment]
I find the old, failed workflows helpful when investigating flakiness and performance trends.

**Comment by matifali** [comment]
> I find the old, failed workflows helpful when investigating flakiness and performance trends.

Can we only allow these for pr-cleanup.yaml?

**Comment by ammario** [comment]
Why do you want to cleanup at all? What bothers you about the current system?

**Comment by matifali** [comment]
@ammario https://github.com/coder/coder/actions/workflows/pr-cleanup.yaml
This will have a failed run for every closed pr that did not have a pr deployment. If this is ok, we can close this.

**Review by ammario — APPROVED** [review]

**Pull request merged**
