### PR TITLE
chore: group various npm dependencies

### PR DESCRIPTION
**Pull request by matifali**
This PR groups various npm dependencies for dependabot PRs.

1. react
	  - "react*"
	  - "@types/react*"
2. xterm:   
 	 - "xterm*"
3. xstate:
	  - "xstate"
 	 - "@xstate*"
4. mui:
 	 - "@mui*"
5. storybook:
	  - "@storybook*"
 	 - "storybook*"
6. eslint:
	  - "eslint*"
	  - "@eslint*"
	  - "@typescript-eslint/eslint-plugin"
	  - "@typescript-eslint/parser"
7. jest:
	  - "jest*"
	  - "@swc/jest"
	  - "@types/jest"

### CODE REVIEW

**Comment by matifali** [comment]
@BrunoQuaresma, you can change or remove the grouping as more suitable.

**Comment by BrunoQuaresma** [comment]
Not sure if I got it, what is the advantage of using this?

**Comment by matifali** [comment]
@BrunoQuaresma This will create a single PR for the group instead of individual PRs for each dependency. Enabling this would be harmless, I guess, and we can always revert if we see it not suitable.
I need your input on grouping as I am unsure which dependencies are related and must be updated together.

**Review by BrunoQuaresma — APPROVED** [review]
Let's try it and see how it goes. Thank you for the help.

**Pull request merged**
