### PR TITLE
fix: Clean up conn on NewStream error in memDRPC

### PR DESCRIPTION
**Pull request by mafredri**
If we don't close the connections, we'll leak memory/leave connections open.

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
Hey! Could you please add a short writeup to the issue description, so that it's clear why is it necessary?

**Comment by mafredri** [comment]
> Hey! Could you please add a short writeup to the issue description, so that it's clear why is it necessary?

Done 👍🏻.

**Comment by mtojek** [comment]
Ok, that's what I expected. Is there any issue that should linked or did you find it accidentally?

**Comment by mafredri** [comment]
CI failure, was an easy fix so I didn't open an issue for it.

**Review by mtojek — APPROVED** [review]
LGTM if it helps 👍

**Pull request merged**
