### PR TITLE
fix(coderd): use insights for DAUs, simplify metricscache

### LINKED ISSUE #12134: A slow SQL query is causing high database load
By checking our AWS RDS metrics, we found that one slow query is consuming a lot of database resource and causing high database load. 

This is the query ```
-- name: GetDeploymentDAUs :many SELECT (created_at at TIME ZONE cast($1::integer as text))::date as date, user_id FROM workspace_agent_stats WHERE connection_count > ? GROUP BY date, user_id ORDER BY date ASC```

We may have a query or table to optimise here. The avg latency per call is 42s for a single query.
Screenshot 2024-02-14 at 2 26 07 pm

### PR DESCRIPTION
**Pull request by mafredri**
This PR simplifies the DAU logic by relying on rolled up insights giving us great query performance and removing the need for caching each individual timezone.

For this fix, I opted not to refactor the WebUI requests to use `start_time=...&end_time=...` like template insights requests do. Instead I retrofitted this logic on the `/daus` API endpoints using the TZ offset.

I also opted to always return 60 days (2 months), just because the way this is used it doesn't make sense to return more.

In the future, we can request this data from `/insights/templates?section=interval&start_time=&end_time&interval=day` instead, this also takes care of the 60 days hardcoding.

Fixes #12134
Fixes https://github.com/coder/customers/issues/384
Refs #12122

### CODE REVIEW

**Comment by mafredri** [comment]
* **#12775** <a href="https://app.graphite.dev/github/pr/coder/coder/12775?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @mafredri and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by kylecarbs — APPROVED** [review]
Code deletion 🤤🤤🤤

**Comment by f0ssel** [comment]
This was an area I spotted as a rough patch in our code, very happy to see significant deletions here!

**Review by mtojek — APPROVED** [review]
Nice!

**Review by Emyrk — APPROVED** [review]
:heart:

**Pull request merged**
