### PR TITLE
chore(docs): correct inaccuracies in the "Docker in Workspaces" page

### PR DESCRIPTION
**Pull request by phorcys420**
The Sysbox part does not mention that it also works with regular Docker, this has caused confusion for one of our users in the Discord.
The wording I've used for the Sysbox part might not be the best, feel free to adjust the wording :-)

### CODE REVIEW

**Review by stirby — APPROVED** [review]
Thanks Phorcys! Would you mind adding these to the `restructure-new` branch too?

**Comment by phorcys420** [comment]
sure @stirby, changed the base branch!

**Comment by phorcys420** [comment]
ugh, this did introduce some other changes, let me fix this

**Comment by phorcys420** [comment]
@stirby let's merge this into `main` and i'll merge `restructure-new` with `main` right after

**Pull request merged**
