### PR TITLE
chore: make LICENSE.enterprise extend the AGPL

### PR DESCRIPTION
**Pull request by phorcys420**
related to #9267 

---

~~This PR removes the license crafting in the windows installer script and adds a ``LICENSE.mixed`` to the root of the repo.
This was decided upon discussion with @deansheather.~~

This PR extends LICENSE.enterprise to include AGPL

### CODE REVIEW

**Review by kylecarbs — CHANGES_REQUESTED** [review]
What prompted the discussion?

Putting another `LICENSE` file in the repository may slow sales-cycles, with users wondering what the `LICENSE.mixed` means. I haven't seen it before.

**Comment by deansheather** [comment]
@kylecarbs we need to put a single license file somewhere for the chocolatey package. Currently we link to the coder.com terms of service which isn't a valid license. We also need to include a text file of the license in the chocolatey package which matches the contents of the license URL.

Linking the enterprise license only means that we're claiming the whole binary is enterprise licensed. Linking the AGPL license is the same thing but the opposite. So we need to link to and have a single file containing both license texts. It doesn't have to be called `LICENSE.mixed` or even exist in the root directory. What do you suggest?

**Comment by phorcys420** [comment]
makes sense to me too

**Comment by deansheather** [comment]
> makes sense to me too, do I close this?

No, rename the LICENSE.mixed file to LICENSE.enterprise overwriting the existing file.

**Comment by phorcys420** [comment]
> No, rename the LICENSE.mixed file to LICENSE.enterprise overwriting the existing file.

Done, but are you sure this "extends the AGPL" as @kylecarbs said?

**Review by kylecarbs — COMMENTED** [review]
Seems like we should probably get legal to review this change.

**Comment by phorcys420** [comment]
whoops, I accidentally deleted the branch.

**Pull request closed without merging**
