### PR TITLE
feat: audit git ssh key regeneration

### PR DESCRIPTION
**Pull request by coadler**
Updates #4541

### CODE REVIEW

**Comment by Kira-Pilot** [comment]
The resource name for this type of diff is quite long - a whole key.
You can see the string displayed on the FE below:
Screen Shot 2022-10-14 at 1 56 51 PM

Do you think we could get away with not displaying the resource name for audit logs of this type, i.e. amending the description field such that it returns `"description": "{user} updated git ssh key"` instead of `"description": "{user} updated git ssh key {target}"`?

**Comment by Kira-Pilot** [comment]
This is working great for the `regenerateGitSSHKey` handler as it is hit from the UI.

Is there any CLI command counterpart we need to worry about here?

If not, do you mind adjusting `audit-logs.md` so that we show support for `GitSSHKey` again?

**Comment by coadler** [comment]
> The resource name for this type of diff is quite long - a whole key. You can see the string displayed on the FE below: Screen Shot 2022-10-14 at 1 56 51 PM
> 
> Do you think we could get away with not displaying the resource name for audit logs of this type, i.e. amending the description field such that it returns `"description": "{user} updated git ssh key"` instead of `"description": "{user} updated git ssh key {target}"`?

I think that's a good idea! I'll change that.

> This is working great for the `regenerateGitSSHKey` handler as it is hit from the UI.
> 
> Is there any CLI command counterpart we need to worry about here?
> 
> If not, do you mind adjusting `audit-logs.md` so that we show support for `GitSSHKey` again?

CLI commands don't need to be updated, I'll add it back as well!

**Comment by coadler** [comment]
> Screen Shot 2022-10-14 at 2 03 34 PM
> 
> Since the private key diff value will be empty, can we omit this?

The idea of secret values in diffs is so we can tell a value changed without leaking that value. Maybe we can get a better way to display secret values?

**Review by Kira-Pilot — APPROVED** [review]

**Pull request merged**
