### PR TITLE
feat: Allow admins to create workspaces for other users

### LINKED ISSUE #3263: Allow admins to create workspaces on behalf of users
As a Coder administrator, I'd like to use the API/CLI (or even the web dashboard) to create and edit workspaces on behalf of other users.

Use cases:
- Migrating platforms or workspaces on behalf of users
  - e.g. moving to another template, migrating from Coder v1
- Automate/integrate Coder into another platform
- Automated load testing (create users with workspaces)
- Ensure developers have one workspace when their account is created

This seems like it could be an API/CLI-only feature. @Emyrk brought up the idea that admins could "masquerade" users (e.g. "Log in to Coder as @user-1").

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #3263.

This is now possible via the API, but still isn't possible via the UI.

### CODE REVIEW

**Review by Kira-Pilot — APPROVED** [review]
I'd be interested in picking the FE of this up next week if its something we're interested in.

**Comment by kylecarbs** [comment]
@Kira-Pilot it'd be cool to have a user-dropdown appear in the create workspace screen if you are an admin.

image

Similar to how GitHub has it would be nice :nerd_face:

**Comment by Kira-Pilot** [comment]
@kylecarbs I'll start on that on Monday!

**Comment by bpmct** [comment]
this is so cool 🎉

**Review by coadler — APPROVED** [review]

**Pull request merged**
