### PR TITLE
fix: redirect to login upon authentication error

### LINKED ISSUE #9090: You are signed out or your session has expired. Please sign in again to continue.
Version: [`v2.0.2+76ad116`](https://github.com/coder/coder/commit/76ad116e12552ed76dcef9239347fabc37b99e81)

image

I purposely set CODER_SESSION_DURATION to 2 days so when this occurs, I only get an error message and no auto-redirect to the login page. Coder basically doesn't fully kick the user out and shows errors or blank screens.

image

image

### PR DESCRIPTION
**Pull request by aslilac**
Fixes #9090

- ~~This is like, way very much the wrong place to do this. I'd love some feedback on where a more appropriate place might be from someone more familiar with the codebase.~~
- ~~Do we use 401 codes for any other circumstance? (ie. properly logged in, but not enough permission) How can we disambiguate?~~
- ~~I tried using `Navigate`, `useNavigate`, etc. from react-router-dom and they all seem to just...not work, for some reason. 🙃 I spent like 15 minutes trying to debug it and got nowhere.~~

- Checks `detail` to make sure it's an expired token, because we use 401 for several things
- Adds an interceptor to axios when the `RequireAuth` component is mounted to check for any responses failing because of expired auth.
- Updates the auth state to signed out when detected, which will automatically kick users out to the login screen (and will display the error message that resulted in this behavior)

### CODE REVIEW

**Comment by aslilac** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by BrunoQuaresma** [comment]
What I would do, in this particular case, is to add an Axios interceptor in the `api/api.ts` that checks for unauthorized errors and, if there is an unauthorized error do a "hard" redirect to the login page like `window.location.href = "/login"`.

**Comment by BrunoQuaresma** [comment]
PS: I don't think this a great way of doing it but the best I can think 🤔 feel free to propose any refactor if you think we should deal with that differently

**Comment by aslilac** [comment]
> PS: I don't think this a great way of doing it but the best I can think 🤔 feel free to propose any refactor if you think we should deal with that differently

it's definitely better than doing it in some random component that may or may not always get rendered :p

I think this is the kind of issue that's fine to fix in a "good enough" way and improve later if it becomes an issue

**Comment by aslilac** [comment]
so after a bit more playing around with this, I'm not sure that I like handling this from outside of React... it makes it feel a lot more fragile, and requires that you check manually for any routes that shouldn't require authentication (like /login and /setup) or you can get stuck with buggy redirects. I'd really love to figure out a non-invasive way to have the `RequireAuth` component be in charge of this...

**Comment by BrunoQuaresma** [comment]
@aslilac this is the ideal scenario. Maybe, you might be able to add the interceptor in the RequireAuth component using a `useEffect`. The good thing is, you can also remove it when the component is unmounted(when the user navigates outside of authenticated routes) and use `navigate()`.

```tsx
// RequireAuth.tsx

const navigate = useNavigate()

useEffect(() => {
  // This is just a mock code, Idk what is the exact Axios API to do that
 const interceptor = axios.interceptor((_req, res, next) => {
    if(res.code === 401) {
      redirectToLoginWithCurrentUrl()
      return
    }
    next()
  })
  return () => {
    interceptor.remove()
  }
})
```

**Comment by aslilac** [comment]
clever! best of both worlds!

**Comment by aslilac** [comment]
Screenshot 2023-08-17 at 9 56 35 AM

this works super well, and lets the error still display on the log in page. really happy with how this turned out now. :)

**Review by BrunoQuaresma — APPROVED** [review]
🐑 it

**Pull request merged**
