### PR TITLE
fix: make sure `fly_app` name is lower case

### LINKED ISSUE #9767: Uppecase username fails in default template workspace creation
Workspace owner name is set after the username, it is allowed to use uppercase in the username, however, it is not allowed to use uppercase for workspace name and the following validation error is returned.

`createApp Validation failed: Name may only contain numbers, lowercase letters and dashes`

Default fly template fails with uppercase username
```
resource "fly_app" "workspace_fly_app" {
  name = "coder-${data.coder_workspace.me.owner}-${lower(data.coder_workspace.me.name)}"
  org  = var.fly_org
}
```

workaround add `lower()`
```
resource "fly_app" "workspace_fly_app" {
  name = "coder-${lower(data.coder_workspace.me.owner)}-${lower(data.coder_workspace.me.name)}"
  org  = var.fly_org
}
```

Restrict username to lowercase characters.

NOTE: I am aware of https://github.com/coder/coder/issues/1689#issuecomment-1203371376 , however this requirement should be somewhere documented.

### PR DESCRIPTION
**Pull request by pi3ch**
fly_app does not support uppercase. Coder allows uppercase for username/owner.

### CODE REVIEW

**Comment by pi3ch** [comment]
recheck
I have read the CLA Document and I hereby sign the CLA

**Comment by pi3ch** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pi3ch** [comment]
recheck

**Review by matifali — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
