### PR TITLE
ci: enable nestif linter

### PR DESCRIPTION
**Pull request by ammario**
ci: enable nestif linter

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

**Review by kylecarbs — APPROVED** [review]

**Comment by ammario** [comment]
a5331102:

Fixed up login and decomposed further.

**Review by Emyrk — COMMENTED** [review]
20 seems high. If we only have 1 violation, we can just `//nolint` that function

**Comment by ammario** [comment]
we had nolint before.. but i think it's too easy to abuse

**Comment by ammario** [comment]
E.g. when a function crosses the threshold, it's easy to "nolint" it and say that the lint rule doesn't apply to the function for such and such reason. I saw this happening before with `gocyclo`.

**Comment by Emyrk** [comment]
> E.g. when a function crosses the threshold, it's easy to "nolint" it and say that the lint rule doesn't apply to the function for such and such reason. I saw this happening before with `gocyclo`.

I agree `nolint` is a cop out. I thought you were adding a new linter, and raised the cyclo limit from 4 -> 20 to cover a single edge case.

**Comment by ammario** [comment]
Oh no. The linter's rules were configured but it wasn't enabled.

**Review by Emyrk — APPROVED** [review]

**Pull request merged**
