### PR TITLE
chore: add vault icon

### PR DESCRIPTION
**Pull request by matifali**

### CODE REVIEW

**Comment by matifali** [comment]
@aslilac I think some recent changes cause what we are doing regarding displaying icons. Can you please take a look? I think we need to update `make gen` to consider newly added icons but I am not sure what command to add there.

**Comment by aslilac** [comment]
I already updated `make gen`, you just need to run it

**Comment by aslilac** [comment]
can we use the file from here instead: https://github.com/hashicorp/vault/blob/main/ui/public/vault-logo.svg

issued under a known license, and we can just recolor it to their brand yellow

**Comment by matifali** [comment]
Hashicorp has both black and yello icons for the vault. Yellow looks better our dark UI. I guess it will be fine on the light UI too once we do it.

**Comment by matifali** [comment]
And I did run `make gen` but it didn't create any new file. I will try agin.

**Comment by aslilac** [comment]
yeah but the one you used doesn't seem like it's from hashicorp, it contains some comment about another website I've never heard of. I'd rather not use one from an unknown source, we should use one we obtained from hashicorp. 😅

**Comment by aslilac** [comment]
> And I did run `make gen` but it didn't create any new file. I will try agin.

maybe try `make -B gen`

**Pull request merged**
