### PR TITLE
fix(site): changing password no longer silently trims space chars in a password

### LINKED ISSUE #5638: When changing a password, it silently trims space characters from inside on every value change trigger
If a user is changing his password (SettingsSecurityForm.tsx) and enters a space, it will not be in the value but no error message is displayed that it's an invalid character.

This can result in a user setting a password with spaces in it like "some random sentence" which will result that he actually changed his password to "somerandomsentence" without seeing it. As he can enter that phase with spaces in the confirmation as well and they will match, he will only figure out that he can not login anymore with that password after it has been updated.

If however he copy pastes into the password field, a space character is possible so I'm not sure if the bug is not showing an error message or trimming on every change of the field.

### PR DESCRIPTION
**Pull request by rac2030**
Make the form behave the same way as the new user creation form without the trimming listener in password fields.
Bug documented in #5638

### CODE REVIEW

**Review by presleyp — APPROVED** [review]
Nice fix, thanks! You can address the pr title issue by adding "fix: " in front of your current title.

**Comment by coadler** [comment]
@rac2030 would you mind appeasing the CLA bot? Then we should be good to merge!

**Comment by rac2030** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rac2030** [comment]
recheck

**Pull request merged**
