### PR TITLE
feat: add display_name field to groups

### PR DESCRIPTION
**Pull request by Emyrk**
# What this does

Adds an optional non-unique human friendly group name for display purposes. This is required for #8214. This essentially allows mapping a non-friendly group name to a friendly one at runtime, rather than `OIDC_GROUP_MAPPING` (which requires a restart).

**This field defaults to the empty string ("").** By default `name` is used as the display name. So this features changes nothing about how groups currently work.

If the `display_name` is set however, then that name takes priority for the UI.

### CODE REVIEW

**Review by sreya — COMMENTED** [review]
Looks good overall, I don't see any tests in `post/patch` for `enterprise/coderd` though.

**Comment by Emyrk** [comment]
I'll add to the existing tests

**Comment by Emyrk** [comment]
I added onto the existing patch/create tests.

**Review by sreya — APPROVED** [review]
Would probably be good to add a test in `cli` too since we're supporting it there.

**Pull request merged**
