### PR TITLE
feat(site)!: avoid window.open for coder apps

### PR DESCRIPTION
**Pull request by fcsonline**
The current implementation of `AppLink` opens the specified application in a small popup instead of a new browser tab. The experience is not good because you lose all the browser toolbars. Also, if you open external links like `vscode://`, VSCode is opened but an empty browser window is left as leftover.

### CODE REVIEW

**Comment by fcsonline** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fcsonline** [comment]
A bit related https://github.com/coder/coder/issues/8796

**Comment by fcsonline** [comment]
Should I do something else?

**Comment by matifali** [comment]
This partly resolves #9452. I am not sure if we need the coder provider change as initially proposed in the issue. 
cc: @kylecarbs

**Comment by Emyrk** [comment]
I saw this talked about before, and iirc someone wanted it to stay a new window. I wonder if we can make this configurable?

**Comment by Emyrk** [comment]
I think it could? I was just trying to propose a way to have both behaviors exist

**Comment by bpmct** [comment]
There are certain use cases (e.g. url handlers such as `slack://` and `vscoder://`) we never want it to open in a new window. Because of this, and because I want to avoid a breaking change, can we add a property to `coder_app` to make it configurable?

There is also the user preference (new tab vs window) which is a real consideration, but something we should table for now. Making it a template preference gets us unblocked from the hard issue.

**Comment by fcsonline** [comment]
Can someone explain the use case for a "New window" path? Which is the benefit over a new tab? I can only see cons like:

- Popup blockers blocking this new window
- Window without browser toolbars and an arbitrary window size
- Desktop urls are not handled properly

With this change, I just wanted to emulate the default and most common behaviour with browsers that is open new stuff in a tab. I don't see the point of having this configurable because of the mentioned cons.

On the other hand, we tried hard to set an external/local url with a `vscode://` link, but we were not able to do it because we wanted to combine it with a `healthcheck` to enable it when all the dependant services were ready, but there is an incompatibility rule between `external` and `healthcheck` fields in Terraform.

**Comment by matifali** [comment]
@fcsonline external links to local apps now open direct in v2.2.0.

**Pull request closed without merging**
