### PR TITLE
feat(cli/vscodessh): add support for --wait and scripts that block login

### PR DESCRIPTION
**Pull request by mafredri**
This PR takes a quick stab at adding support for `--wait=auto|yes|no` to `coder vscodessh`. This allows the VS Code extension to block login until the blocking startup scripts are ready.

Implementing it this way has two down-sides, though:

1. The `Remote - SSH` extensions `Connection Timeout` setting needs to be raised (from the default `15s`, I set mine to `300s`)
2. The startup logs are not automatically shown (the user needs to click `details` to see what's going on (this can be seen as a pro, too)

An alternative approach would be to stream the logs directly in the Coder VS Code extension, at the risk of maintining two different code paths in two separate projects.

### CODE REVIEW

**Comment by mafredri** [comment]
@kylecarbs thoughts? Should we take this approach or implement this in the VS Code extension instead?

Here's a picture after clicking `details`, but before that the logs are not shown.

image

**Comment by ericpaulsen** [comment]
@mafredri - i'm reopening this, as another customer has inquired about this missing functionality.

**Review by johnstcn — APPROVED** [review]
I'm OK with this approach as a stop-gap measure, but I would like to see us eventually support this properly in the VSCode extension. We should also try to bump that 15s timeout automatically, but that's a separate PR.

**Comment by mafredri** [comment]
Once https://github.com/coder/vscode-coder/pull/194 is merged/released, we can merge this as well. Before that there's a high chance enabling this will lead to a worse user experience.

**Pull request merged**
