### PR TITLE
fix: Use immutable links for docker with intellij/pycharm

### PR DESCRIPTION
**Pull request by mafredri**
The original links broke and made [markdown link checker cry](https://github.com/coder/coder/actions/runs/3368834328/jobs/5588011866)

### CODE REVIEW

**Comment by mafredri** [comment]
> I assigned Mark and Ammar instead as they'll hopefully know better than anyone else whether the new links are the intended ones or not.

Thanks. This is blocking PRs currently, which is why I did the catch all review, but this is a fair assumption. (The links point to the same files as before, those files were simply moved.)

**Comment by sharkymark** [comment]
I removed the Docker projector links a. because the projector installation approach is out-dated and because pycharm and intellij on docker is a poor experience unless you have a lot of compute which most evaluators will not.

From what I see in the commit, the docker links are being added back.

**Review by sharkymark — APPROVED** [review]
I would prefer these get deleted but if this is blocking something, I approve.

**Comment by mafredri** [comment]
@sharkymark Ah, I didn't notice your PR that removes these links: https://github.com/coder/coder/pull/4819

I just wanted to fix the broken links in `main`. I'll merge this PR now to fix the immediate issue, but removing them is fine by me. 👍🏻

**Pull request merged**
