### PR TITLE
fix(site): set min and max attributes for workspace number parameters

### PR DESCRIPTION
**Pull request by toshikish**
Implements #14532.

This PR sets `min` and `max` attributes for workspace number parameter `<input>` elements using [inputProps](https://mui.com/material-ui/api/text-field/#text-field-prop-inputProps).

Note: When we update MUI to v6 or later, it is better to use `slotProps.htmlInput` instead.

### CODE REVIEW

**Comment by matifali** [comment]
Hi @toshikish, thank you for the contribution. Could you rebase your PR on `main` and make all the checks in CI pass? We should be able to review the contribution after that.

**Comment by toshikish** [comment]
@matifali Hi, thank you for reviewing. I rebased the branch and fixed the lint and unit test errors found so far.

**Comment by matifali** [comment]
> The cause of test-e2e-premium failure is that `license` is empty. [coder/coder/actions/runs/11565755422/job/32199523539?pr=15182#step:11:131](https://github.com/coder/coder/actions/runs/11565755422/job/32199523539?pr=15182#step:11:131)
> 
> The environment variable `CODER_E2E_LICENSE` seems substituted through CI secret, but is it set correctly? [toshikish/coder@`set-min-max-for-workspace-parameters`/.github/workflows/ci.yaml#L616](https://github.com/toshikish/coder/blob/set-min-max-for-workspace-parameters/.github/workflows/ci.yaml?rgh-link-date=2024-10-29T12%3A36%3A25Z#L616)

Yes, it is but unfortunately the secret is not available on PRs made through branches outside of coder/coder. 

cc:

**Comment by BrunoQuaresma** [comment]
I think rebasing this PR from main should fix the e2e tests.

**Comment by matifali** [comment]
@BrunoQuaresma unfortunately e2e tests can't work on forks as they don't have access to the repo secrets (the license).

**Comment by matifali** [comment]
@BrunoQuaresma COuld we run the e2e tests locally while we figure out a way to allow forks to run them?

**Comment by matifali** [comment]
@BrunoQuaresma Could you review it again? Thanks

**Comment by BrunoQuaresma** [comment]
@matifali the code didn't change from my last review so I think we are ready to go. My only concern is not being able to run the e2e tests using the premium license.

**Pull request merged**
