### PR TITLE
chore(cli): replace clibase with external `coder/serpent`

### PR DESCRIPTION
**Pull request by ammario**
I wanted to use clibase in a new thing I'm building, so it felt like a natural moment to move it into its own repo.

Unfortunately the help code is duplicated between this repo and serpent because we coupled our help handler with Coder specific concepts and I didn't want to make this change larger.

Most of the changes are simple find and replace except for `apitypings/main.go`.

TODO:
- [x] fix type generator

### CODE REVIEW

**Comment by ammario** [comment]
* **#12252** <a href="https://app.graphite.dev/github/pr/coder/coder/12252?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ammario and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by mafredri** [comment]
@ammario what's the plan for continuing development of `serpent`? I worry that splitting up the code base here will increase friction in improving the `coder` CLI.

At the moment, we're still missing critical features like shell completion. And some basic functionality like `coder badcommand` doesn't show that the subcommand doesn't exit, it just shows the help. I'm sure there are some other open issues for the cli/clibase as well.

**Comment by ammario** [comment]
There is no plan at the moment. It will make development marginally more difficult when trying to improve both the CLI base and coder/coder but the rate of changes (https://github.com/coder/coder/commits/main/cli/clibase) to clibase seems low enough that it shouldn't matter.

On the other side, we can improve serpent without the complex development loop and CI of coder/coder.

**Comment by ammario** [comment]
Plus, we can submit light changes to `serpent` without review.

**Comment by ammario** [comment]
Going to tag @kylecarbs instead to hopefully get it merged before the weekend and not deal with more conflicts.

**Review by kylecarbs — APPROVED** [review]
Essentially rubber stamping this.

I agree with @mafredri that making significant changes may be a pain in the butt, but I think it's worthwhile for us to try and advertise `serpent` to other large Go services that have many configurable properties.

**Review by mafredri — APPROVED** [review]
Also giving my stamp, but I'd want to see the relevant issues ported over (or at least referenced) to the serpent repo.

This will increase visibility for shortcomings in the project and also has the chance to attract contributors.

**Comment by ammario** [comment]
Will revisit this when I have some free cycles.

**Comment by ammario** [comment]
OK. Merging this in now. Will move the relevant issues to the new tracker and maybe knock some out today.

**Pull request merged**
