### PR TITLE
revert: update pnpm to v9

### PR DESCRIPTION
**Pull request by mtojek**
This reverts commit 2238593f575cb336e13369f322542f5681c762d5.

Unfortunately, my developer environment is unusable due to this change. Nix is rebuilding nodejs since an hour, and I'm blocked now. 

Please re-review the original PR, and verify if it does not affect OSX.

Screenshot 2024-07-19 at 14 43 08

### CODE REVIEW

**Comment by matifali** [comment]
I am trying to reproduce it on macOS. Will report back

**Review by aslilac — COMMENTED** [review]
looks fine to me, but I know nothing about nix so I'm hoping someone else will approve 😅

**Comment by matifali** [comment]
Working fine for me on `main` on macOS and also on linux arm64.

**Comment by coadler** [comment]
I'm a bit torn here. It unfortunate nix's random build cache misses prevent us from keeping tools up-to-date.

**Comment by dannykopping** [comment]
Do we understand currently how this change caused the cache misses on MacOS?

**Comment by mtojek** [comment]
> Do we understand currently how this change caused the cache misses on MacOS?

No, but I'm unsure if I want to spend a day reverse-engineering the nix caching logic. Right now I'm on Apple M1 Pro with Ventura (13.1).

The workaround I'm using now is to patch the `flake.lock` manually,

**Comment by dannykopping** [comment]
More specifically: what I mean is do we know which specific package is causing the issue? I assume it was `pnpm`?
We'll have to find out what is causing this if we ever want to upgrade passed `pnpm` v8.

We updated a few things in this PR, so if we can isolate what caused the issue we can a) just revert that specific change only and b) report the issue upstream (or find an issue which already exists which may contain a workaround).

**Comment by mtojek** [comment]
> We updated a few things in this PR, so if we can isolate what caused the issue

Alright, I will get back to this when I have capacity.

**Comment by matifali** [comment]
**not directly related** but our `flake.nix` is getting more complex, similar to our dogfood [Dokerfile](https://github.com/coder/coder/blob/main/dogfood/Dockerfile), and both can see some simplifications in the future.

**Pull request closed without merging**
