### PR TITLE
feat(site): display template's readme first on template page

### PR DESCRIPTION
**Pull request by rodrimaia**
~~This pull request moves the Readme section on the template page to appear first, replacing its previous position after the DAU and Template Resources sections.

We decided to not limit the readme section height for now. Another idea would be to have the option to collapse the section if we realize templates readme tend to be big ~~

We decided to have a new Docs tab with the Readme. We created also a redirect to point bookmarked links of /templateName#readme to the new tab! 

Loom video:
https://www.loom.com/share/3c83e8e528d744b1afb8fb8b049f8017

### CODE REVIEW

**Comment by kylecarbs** [comment]
Thoughts on DAU still coming first? Because README hasn't been near the top, users may not have actually filled it out.

Maybe we ask for some feedback in Discord.

**Comment by BrunoQuaresma** [comment]
I think asking this in Discord is a good one.

**Comment by BrunoQuaresma** [comment]
@rodrimaia I think we can move the chart to be the first element on the screen.

**Review by BrunoQuaresma — APPROVED** [review]
Since it is a tiny change, I'm approving it so you can merge it right away. Just remember to check Chromatic checks and approve the changes before merge!

**Review by BrunoQuaresma — APPROVED** [review]
LGTM

**Pull request merged**
