### PR TITLE
chore: rename notification banners to announcement banners

### PR DESCRIPTION
**Pull request by aslilac**

### CODE REVIEW

**Review by stirby — APPROVED** [review]

**Comment by stirby** [comment]
Do you see any issue with leaving the internal symbols as NotificationBanner?

**Comment by aslilac** [comment]
> Do you see any issue with leaving the internal symbols as NotificationBanner?

I kind of assumed that we'd already published a release with this feature, which would make renaming stuff in the code a breaking change, but I just double checked and realized that we haven't. It'd actually be a good idea to rename it more thoroughly, I just didn't realize I could. 😄

**Comment by stirby** [comment]
Ahh gotcha, appreciate you playing it safe 😁. The code freeze _is_ tomorrow but I can cherry pick this in if you need time for the rename. 👍

**Comment by aslilac** [comment]
I think it should be ready to go!

**Pull request merged**
