### PR TITLE
chore(cli): replace lipgloss with coder/pretty

### PR DESCRIPTION
**Pull request by ammario**
chore(cli): replace lipgloss with coder/pretty

This change will improve over CLI performance and "snappiness" as well as
substantially reduce our test times. Preliminary benchmarks show
`coder server --help` times cut from 300ms to 120ms on my dogfood
instance.

The inefficiency of lipgloss disproportionately impacts our system, as all help
text for every command is generated whenever any command is invoked.

The `pretty` API could clean up a lot of the code (e.g., by replacing
complex string concatenations with Printf), but this commit is too
expansive as is so that work will be done in a follow up.

### CODE REVIEW

**Comment by ammario** [comment]
f11d5cee:

Begun porting over `cli` and `enterprise/cli`.

65 problems left.

**Comment by ammario** [comment]
801c013c:

- Finished converting `cliui`

41 problems left.

**Comment by ammario** [comment]
737c80f9:

No more compilation or lint issues!

**Comment by ammario** [comment]
50a0f2a5:

- cmd/cliui presents nicely
- also, added help to cmd/cliui

**Comment by ammario** [comment]
c495ef6d: cli tests pass

**Review by sreya — APPROVED** [review]

**Pull request merged**
