### PR TITLE
feat: Add metadata support to the UI

### LINKED ISSUE #2989: Resource Metadata + Secrets
## Problem statement

Developers want to see additional metadata about resources in Coder. This could be an instance type, the number of cores an instance has, or a link to the cloud resource itself (say in a GCP dashboard).

As a developer, I want to see information about my workspace, both information that is dynamic (e.g external IP) and the most relevant aspects of the template (no. CPUs).

## Definition of done

We should add arbitrary key/value pairs that allow template authors to expose additional metadata. This should be added in our Terraform Provider, allowing customers to expose arbitrary values from existing resources that are provisioned. The key/value pairs would be available from the CLI and the dashboard. 

---
Implementation notes (@bpmct)

Dashboard [(figma)](https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-v2-Design?node-id=599%3A632):

Nested resources (3)

Template:

```hcl
resource "null_resource" "about" {}

resource "coder_metadata" "about_info" {
  resource_id = null_resource.about.id
  item {
    key = "type"
    value = null
  }
  item {
    key = "quicklinks"
    value = "[onboarding guide](https://mywiki.com/onboarding), [troubleshooting](https://mywiki.com/troubleshooting)"
  }
}

resource "kubernetes_pod" "main-dev" {
  # ...
}

resource "coder_metadata" "dev_info" {
  resource_id = kubernetes_pod.main-dev.id
  item {
    key = "api_key"
    value = "asdfjkl"
    sensitive: true
  }
}

```

CLI: 

```sh
$ coder metadata my-workspace
RESOURCE_NAME      KEY                 VALUE
about              workspace-id        acf2a70d-6347-4b8c
about              quicklinks          [onboarding guide](https://mywiki.com/onboarding), [troubleshooting](https://mywiki.com/troubleshooting)
main-dev           type             kubernetes_pod
main-dev           api_key             (hidden)

Some values are sensitive. Use `coder metadata myworkspace <key>` to fetch individual values.
```

In the future, perhaps `resource_id = "global"` or `global = true` could be used to display metadata workspace-wide in another panel if the hack is widely used.

---

Related:
- #1325 
- #1321

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Closes #2989 

Preview:
Screen Shot 2022-08-09 at 13 24 20

Demo:
https://user-images.githubusercontent.com/3165839/183706445-4f3dd7c5-f070-43f9-aba0-4a3b63c82fb5.mov

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

**Comment by ammario** [comment]
Stunning!


We need issues for:
- including metadata in example templates
- docs

**Comment by BrunoQuaresma** [comment]
> Stunning!
> 
> We need issues for:
> 
> * including metadata in example templates
> * docs

@dwahler since you made the BE side, do you think these are things that you could do or "drive"? I'm happy to help!

**Comment by dwahler** [comment]
> @dwahler since you made the BE side, do you think these are things that you could do or "drive"? I'm happy to help!

Yep, I opened #3432, #3433 and #3434 to track follow-up tasks.

**Comment by BrunoQuaresma** [comment]
@dwahler you are awesome!

**Pull request merged**
