### PR TITLE
feat: add avatar urls to groups

### LINKED ISSUE #4502: groups: add avatar_url to groups
gives users a way to stylize groups

### PR DESCRIPTION
**Pull request by sreya**
fixes #4502

@BrunoQuaresma i haven't done any validation of the avatar url in the FE, wasn't exactly sure what that should entail.

groups page:

image

edit page: 

image

create page:

image

templates page:

image

### CODE REVIEW

**Comment by Kira-Pilot** [comment]
@sreya I'm not sure if this out of the scope of this ticket, but when testing locally, I don't see the avatar show up in the groups page.

Also, if I go to edit the group, it seems like the URL isn't persisted in the input:

Kapture 2022-10-13 at 17 25 00
 
Let me know if I'm missing something!

**Comment by Kira-Pilot** [comment]
Your Chromatic snapshots have some text overflow. I left a comment in there; reach out if you need any help resolving it!

**Comment by sreya** [comment]
@Kira-Pilot what are you using as your backend? This includes a migration that supports the `avatar_url` in the database so if you're running against `dev.coder.com` or something it's not going to work. I looked at the snapshots you talked about and I don't see the text overflow you're talking about...perhaps we can discuss this offline?

**Comment by sreya** [comment]
> I looked at the snapshots you talked about and I don't see the text overflow you're talking about...perhaps we can discuss this offline?

Nvm I figured it out

**Comment by Kira-Pilot** [comment]
@sreya ahhh, that was the issue. Thanks for explaining. 
Looking great now!

**Review by Kira-Pilot — APPROVED** [review]

**Review by coadler — APPROVED** [review]

**Review by bpmct — COMMENTED** [review]
Can we use the same component as the icon picker for "template settings" to support emojis?

**Comment by sreya** [comment]
@bpmct i'm fine for that to be the next iteration but i'd like to merge this as-is

**Pull request merged**
