### PR TITLE
feat: add more rate limit control flags

### LINKED ISSUE #5531: scaletest: How can I avoid API rate limits?
I'm attempting to run a scale test on my Kubernetes cluster with the following command:

```sh
coder scaletest create-workspaces \
    --count 1000 \
    --template "kubernetes" \
    --concurrency 0 \
    --cleanup-concurrency 0 \
    --parameter "home_disk_size=10" \
    --run-command "sleep 2 && echo hello"
```

However, I'm only able to create roughly ~60 concurrent workspaces as I run into a rate limit error:

```sh
== FAIL: workspacebuild/794

        Error: login as new user: POST http://coder.example.com/api/v2/users/login: unexpected status code 429: You've been rate limited for sending more than 60 requests in 1m0s.
```

I have also set `CODER_API_RATE_LIMIT=-1` for my `coder server`, but saw that some routes are still rate limited, regardless of this value:

>       --api-rate-limit int                           Maximum number of requests per minute
>                                                      allowed to the API per user, or per IP
>                                                      address for unauthenticated users.
>                                                      Negative values mean no rate limit. Some
>                                                      API endpoints are always rate limited
>                                                      regardless of this value to prevent
>                                                      denial-of-service attacks.
>                                                      Consumes $CODER_API_RATE_LIMIT

### PR DESCRIPTION
**Pull request by deansheather**
Adds `--dangerous-disable-rate-limits` flag to entirely disable rate limits globally.

Also:
- Adds `DeploymentConfigField[].EnvOverride` because I moved the value in the deployment config struct and the name got changed.
- Changes `str.replaceAll` to `str.replace` to fix node version differences causing swagger generation to fail in dogfood

Closes #5531

### CODE REVIEW

**Review by bpmct — APPROVED** [review]
LGTM. Related, but semi off-topic: Should `coder scaletest` recommend people set `--dangerous-disable-rate-limits` if there is a rate limit error, or should we recommend most people scale test with `concurrency=1`? I ran into rate limits at the 60 user mark.

Regardless, I'll certainly document the flag in the scaling docs. The doc will also recommend scale testing on a staging deployment versus the prod one (where it would be dangerous to disable all rate limits on all occasions)

**Comment by deansheather** [comment]
Rate limits at low concurrency don't produce much load so I don't think we should recommend that. I think recommending this flag + using a staging deployment is OK. If customers really want to test on prod they'll most likely have to disable rate limits temporarily while they run their tests.

**Comment by ammario** [comment]
Can we just add a single disable rate limit flag? Three seems excessive for this narrow use case.

**Comment by deansheather** [comment]
We already have a flag to configure the API rate limit, so I think we should expose flags for configuring the other rate limits as well. Right now they are magic numbers in the code.

**Review by mtojek — APPROVED** [review]
👍

**Review by BrunoQuaresma — APPROVED** [review]
FE looks good to me

**Review by mtojek — APPROVED** [review]

**Pull request merged**
