### PR TITLE
feat: add lifecycle.Executor to manage autostart and autostop

### PR DESCRIPTION
**Pull request by johnstcn**
## What:

This PR adds a package `lifecycle` and an `Executor` implementation that attempts to schedule a build of workspaces with autostart configured. 

- `lifecycle.Executor` takes a `chan time.Time` in its constructor (e.g. `time.Tick(time.Minute)`)
- Whenever a value is received from this channel, it executes one iteration of looping through the workspaces and triggering lifecycle operations.
- When the context passed to the executor is Done, it exits.
- Only workspaces that meet the following criteria will have a lifecycle operation applied to them:
  - Workspace has a valid and non-empty autostart or autostop schedule (either)
  - Workspace's last build was successful
- The following transitions will be applied depending on the current workspace state:
  - If the workspace is currently running, it will be stopped.
  - If the workspace is currently stopped, it will be started.
  - Otherwise, nothing will be done.

## What was done:

- [x] Implement autostop logic

- [x] Add unit tests to verify that workspaces in liminal states and/or soft-deleted workspaces do not get touched by this.
- [x] Exclude workspaces without autostart or autostop enabled in the initial query
- [x] Move `provisionerJobStatus` literally anywhere else.
- [x] Wire up the AutostartExecutor to the real coderd
- [x] Renamed the `autostart/lifecycle` package to `lifecycle/executor` cause that name was bugging me.

## Possible improvements / "Future Work":
- [ ] Make Test_Executor_Run/AlreadyRunning not wait ten seconds somehow:
  - This requires some plumbing -- we'd need some way of hooking more directly into provisionerd, which doesn't seem easy right now.
- [ ] DRY the workspace build triggering logic as it's essentially copy-pasted from the workspaces handler:
  - Leaving this for now as we only use this in two places. Once we need to do this elsewhere, we can revisit.
- [ ] Add a unit test for racy dueling coderd instances:
  - Leaving this for now, as doing our periodic checks in a single transaction should be sufficient to ensure consistency.

Closes https://github.com/coder/coder/issues/271.

### CODE REVIEW

**Review by kylecarbs — COMMENTED** [review]
How do we intend on making this distributed? eg. if I have 5 coderd replicas, what stops them from queueing multiple workspace builds at the same time?

**Review by mafredri — COMMENTED** [review]
Some questions and minor suggestions, but overall a really clean PR!

**Review by kylecarbs — APPROVED** [review]
LGTM! Just a comment on the package naming, as I'd hate for this beautiful package to be eventually bloated due to naming conflicts! ↔️↔️↔️

**Review by mafredri — APPROVED** [review]
LGTM!

**Review by greyscaled — APPROVED** [review]
well done ✔️

**Pull request merged**
