### PR TITLE
docs: move api and cli docs routes to reference/

### PR DESCRIPTION
**Pull request by matifali**
As part of #13434, this PR moves CLI and API docs under reference.

This will help reduce the size of #14182.

we need to create redirects from docs/[cli,api] to docs/reference/[cli,api]

Docs link check is passing so it should be fine to merge.

### CODE REVIEW

**Comment by kylecarbs** [comment]
Do the routes need to be nested like that? The redirects feel unnecessary.

**Comment by matifali** [comment]
> The redirects feel unnecessary.

@kylecarbs Aren't redirects required for any old links to work? in case someone is using those links in any internal docs?

> Do the routes need to be nested like that?

I fixed the manifest. Routes are now nested under Reference.

**Comment by kylecarbs** [comment]
I can make the redirect on coder.com whenever this is good to merge!

**Review by stirby — APPROVED** [review]
Looks good, did you run the broken links action to check all the references? I haven't gone through line-by-line to check as I assume that workflow would be faster

**Comment by stirby** [comment]
Nice work 👍

**Pull request merged**
