### PR TITLE
feat: add members settings page for organizations

### PR DESCRIPTION
**Pull request by aslilac**

### CODE REVIEW

**Review by BrunoQuaresma — COMMENTED** [review]
The code looks good! Just missing tests for the feature.

**Comment by BrunoQuaresma** [comment]
**QA results:**
- I removed myself, the owner, from the organization members, which broke Coder.
- Nit: Even with added members in the org, they are showing in the "add new member" select. Maybe it would be better to hide the ones that are already added?
- Nit: The remove option does not require any extra action, so I would remove the "..."

**Comment by aslilac** [comment]
the way we've budgeted it, I'm gonna work on tests towards the end of the next sprint to make sure we don't have to slip the deadline.

**Comment by jaaydenh** [comment]
Not a high priority but it seems like it would be simpler to not show users already in the organization in the add user dropdown.

**Comment by aslilac** [comment]
that's not practically possible right now. some orgs will have thousands of members, and it would require a new backend endpoint that could return _only_ users which are not in that set. if we did the filtering on the client side, you could easily end up in a situation where the first 25 users that we query are _all_ in the org, and we'd have to send another request....and another....and another.

if we ever do this, it'll have to be later. it'd be a lot of work to get right, and low reward imo.

**Review by jaaydenh — APPROVED** [review]
aside from tests which can be added later, lgtm

**Pull request merged**
