### PR TITLE
fix: config-ssh panic when ssh config is malformed

### PR DESCRIPTION
**Pull request by aaronlehmann**
I somehow ended up with a `~/.ssh/config` file that had an `END-CODER` token before `START-CODER` (probably a bad edit on my side). This causes `coder config-ssh` to panic. Fix this panic by simplifying and combining `sshConfigGetCoderSection` and `sshConfigSplitOnCoderSection` to look for the tokens in order with `bytes.Cut`.

### CODE REVIEW

**Comment by kylecarbs** [comment]
Thanks for the fix @aaronlehmann :partying_face:

**Comment by Emyrk** [comment]
What should the behavior be :thinking:? If the headers are out of order:
```
# Content before coder block
# ------------END-CODER------------
# ------------START-CODER-----------
# Content after coder block
```

The result is this:
```
# Content before coder block
# ------------END-CODER------------
# ------------START-CODER-----------
# Content after coder block
# ------------START-CODER-----------
# This section is managed by coder. DO NOT EDIT.
#
# You should not hand-edit this section unless you are removing it, all
# changes will be lost when running "coder config-ssh".
#
# ------------END-CODER------------
```

Which if I feed back in as input, the first `START-CODER` is now the first instance, and `Content after coder block` is removed:


```
# Content before coder block
# ------------END-CODER------------
# ------------START-CODER-----------
# This section is managed by coder. DO NOT EDIT.
#
# You should not hand-edit this section unless you are removing it, all
# changes will be lost when running "coder config-ssh".
#
# ------------END-CODER------------
```

-----

I think if we detect these are out of order, we should maybe just return a message to the user that their ssh config is malformed and needs to be fixed by hand?


# Unit test

We should add this unit test case to `configssh_test.go`

https://github.com/coder/coder/blob/main/cli/configssh_test.go#L531-L531

```golang
		{
			name: "Start/End out of order",
			matches: []match{
				{match: "Continue?", write: "yes"},
			},
			writeConfig: writeConfig{
				ssh: strings.Join([]string{
					"# Content before coder block",
					headerEnd,
					headerStart,
					"# Content after coder block",
				}, "\n"),
			},
			wantConfig: wantConfig{
				ssh: strings.Join([]string{
					// TODO: What is the expected behavior here?
				}, "\n"),
			},
			wantErr: false,
		},

```

**Comment by Emyrk** [comment]
@aaronlehmann what do you think about returning an error if the headers are out of order and return an error if there is more than 1 header in the config?

**Comment by aaronlehmann** [comment]
> what do you think about returning an error if the headers are out of order and return an error if there is more than 1 header in the config?

That sounds good to me. I'm currently waiting to confirm my employer doesn't object to me agreeing to the CLA, but if you want to tackle this that's fine with me (or feel free to wait until I hear back about the CLA, then I can take a look).

**Comment by Emyrk** [comment]
@aaronlehmann I have some other things going on, so won't be able to touch this for a bit (days). Will keep and eye on this thread and will post here if I do any work on it though :+1:

**Comment by Emyrk** [comment]
Fixed here: https://github.com/coder/coder/pull/6000

**Comment by aaronlehmann** [comment]
Thanks!

**Pull request closed without merging**
