### PR TITLE
docs: add license and template insights prom metrics

### PR DESCRIPTION
**Pull request by ericpaulsen**
this PR adds documentation for the following Prometheus metrics that were recently implemented:

```
coderd_insights_applications_usage_seconds
coderd_insights_parameters
coderd_insights_templates_active_users
coderd_license_active_users
coderd_license_limit_users
coderd_license_user_limit_enabled
```

### CODE REVIEW

**Review by matifali — APPROVED** [review]
Aren't these auto generated docs?

**Review by matifali — COMMENTED** [review]
aren't these auto generated docs? they should be auto generated whenever we add any new matrics. 

@matifali reviewed this PR from Slack with [Graphite](https://app.graphite.dev/github/pr/coder/coder/11109)

**Comment by ericpaulsen** [comment]
@matifali they are auto-generated from the `scripts/metricsdocgen/metrics` file. we do not auto-append newly added metrics to this file, however. it required a manual update.

**Comment by matifali** [comment]
Is thera a reason why we do not make it automated as part of `make gen` ?

**Pull request merged**
