### PR TITLE
feat: generate typescript types from codersdk structs

### PR DESCRIPTION
**Pull request by f0ssel**
This isn't quite there yet, but I wanted to see how close I could get if I timeboxed to 30 minutes. I couldn't find any decent looking libraries in go to do this that didn't complicate things, so I reached for the go AST. 

If we like this idea we could see how much work it would take to make this usable.

Update:
I've worked on making this production ready for us to use on the frontend. This generates a new types-generated.ts file that the frontend team can migrate to.

### CODE REVIEW

**Review by greyscaled — COMMENTED** [review]
I love this concept, I was just talking to @code-asher about a really sneaky bug we ran into from having a hand-written type mismatch. There were no compiler warnings or runtime errors or logs, just a field wasn't there, and none of the calling code caused an exception because it handled `undefined` gracefully.

The one thing (which I don't think blocks anything, more of a FYI type of comment), is that we want to also add mocks for all types we add. It's OK if we still need to do that by hand, just means that you can't auto-generate and fire/forget, you'll have some manual work to do after generating.

Love this :heart:

**Review by presleyp — APPROVED** [review]
Very exciting!

**Review by kylecarbs — APPROVED** [review]
We might want to rename `coderts` to `apitypings` or something more specified. Right now it's kinda unclear what it's doing. `apitypings` isn't great either though so 🤷

Let's remove `experiment` from the title too, since this has really been upgraded to a full-on feature 🦘🦘🦘

**Review by greyscaled — COMMENTED** [review]
```ts
type WorkspaceAgentStatus = "connected" | "connecting" | "disconnected"
```

If it's easier for formatting, you can write it like this:

```ts
type Thing =
 | "a"
 | "b"
 | "c"
```

and just let **prettier** take care of the formatting (the above is valid TS)

**Pull request merged**
