### PR TITLE
chore: reduce docker examples

### LINKED ISSUE #4651: There are 4 example templates that basically do the same thing - confusing - remove one
Version: [`v0.10.1+3c40698`](https://github.com/coder/coder/commit/3c406980336303f32685915a9bd3e27ace81c91d)

Besides the coder templates init being cluttered for way too long, there are 4 Docker templates that all have code-server in them, that for all intents and purposes are the same.

This one, has code-server in the image, so the startup_script doesn't install it, and only starts it.
https://github.com/coder/coder/blob/main/examples/templates/docker-code-server/main.tf

Please trim this down. I think one, that has dotfiles, is fine.

image

### PR DESCRIPTION
**Pull request by bpmct**
fixes #4651

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
Love this!

**Comment by matifali** [comment]
the stale bot is being spammy.

**Comment by matifali** [comment]
Do you have any plans to merge this sooner? I am working on #7001 and its better if this merges before that @bpmct

**Comment by matifali** [comment]
Let's keep only these 2.
1. [docker-with-dotfiles](https://github.com/coder/coder/tree/main/examples/templates/docker-with-dotfiles)
	> This contains [docker](https://github.com/coder/coder/tree/main/examples/templates/docker)
2. [docker-image-builds](https://github.com/coder/coder/tree/main/examples/templates/docker-image-builds)
	> This demonstrates that Coder can build the images too.

**Comment by matifali** [comment]
Sounds fine.

**Comment by matifali** [comment]
Error Trace:	/home/runner/work/coder/coder/examples/examples_test.go:4
You need to remove this test as the template doesn't exist now

**Review by sharkymark — APPROVED** [review]

**Pull request merged**
