### PR TITLE
fix: use latest build version name on workspace page

### LINKED ISSUE #14763: Invalid template version path in dashboard on the workspace page.
When clicking on the active template version from the workspace page, the link goes to an invalid version.

Screenshot 2024-09-23 at 3 21 20 PM

Screenshot 2024-09-23 at 3 21 31 PM

The link should be `https://coder.example.com/templates/TEMPLATE_NAME/versions/VERSION_NAME`, but instead, its going to `https://coder.example.com/templates/TEMPLATE_NAME/versions/TEMPLATE_NAME`

### PR DESCRIPTION
**Pull request by ethanndickson**
Closes #14763

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#14771** <a href="https://app.graphite.dev/github/pr/coder/coder/14771?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ethanndickson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by matifali** [comment]
@stirby We may need to patch 2.15.0 with this. I have not tested but I believe it exists on that branch.

**Comment by ethanndickson** [comment]
Should be fine: https://github.com/coder/coder/blob/190cd1c7130bdeabbe690e8c2b8b08210873366a/site/src/pages/WorkspacePage/WorkspaceTopbar.tsx#L183

**Comment by matifali** [comment]
Yes, I just confirmed. It happened after #14596 which is not included in 2.15.0 yet.

**Pull request merged**
