### PR TITLE
chore(site): add e2e tests for groups

### LINKED ISSUE #12506: e2e: User/Group management
Implement e2e test(s) for creating, listing and deleting users. Should also test creating/deleting groups and adding and removing users from those groups. (As well as the `Everyone` group functioning as expected).

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Closes https://github.com/coder/coder/issues/12506

### CODE REVIEW

**Review by code-asher — APPROVED** [review]
Nicely done!

One note, the linked issues mentions testing the everyone group which I am not seeing in here, does that need to be added?

**Comment by code-asher** [comment]
One other note actually, since this also includes a bug fix should this be prefixed with `fix`?  Too bad we can only squash and merge otherwise you could merge two commits, a chore and a fix.

**Comment by BrunoQuaresma** [comment]
> One note, the linked issues mentions testing the everyone group which I am not seeing in here, does that need to be added?

Good catch, I will add the everyone group test.

> One other note actually, since this also includes a bug fix should this be prefixed with fix? Too bad we can only squash and merge otherwise you could merge two commits, a chore and a fix.

That is true, since most of this PR is chore related, I think we should keep it

**Comment by code-asher** [comment]
> That is true, since most of this PR is chore related, I think we should keep it

True, just worried it will be missed in the changelog for anyone tracking the bug.

**Pull request merged**
