### PR TITLE
fix: delete workspace agent stats after 180 days

### LINKED ISSUE #13430: test flake: `TestDeleteOldWorkspaceAgentStats`
Slack context: https://codercom.slack.com/archives/CJURPL8DN/p1717174598761439

Likely due to it being the last of the month.

https://github.com/coder/coder/actions/runs/9325137323/job/25671626698?pr=13429#step:5:345

```
    dbpurge_test.go:123: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/database/dbpurge/dbpurge_test.go:123
        	Error:      	Condition never satisfied
        	Test:       	TestDeleteOldWorkspaceAgentStats
        	Messages:   	it should delete old stats: []
```

### PR DESCRIPTION
**Pull request by ethanndickson**
Fixes #13430.

The test for purging old workspace agent stats from the DB was consistently failing when ran with Postgres towards the end of the month, but not with the in-memory DB. 

This was because month intervals are calculated differently for `time.Time` and the `interval` type in Postgres:

```
ethan=# SELECT
    '2024-08-30'::DATE AS original_date,
    ('2024-08-30'::DATE - INTERVAL '6 months') AS sub_date;
 original_date |      sub_date
---------------+---------------------
 2024-08-30    | 2024-02-29 00:00:00
(1 row)
```

Using `func (t Time) AddDate(years int, months int, days int) Time`, where `months` is `-6`:
```
Original: 2024-08-30 00:00:00 +0000 UTC
6 Months Earlier: 2024-03-01 00:00:00 +0000 UTC
```

Since 6 months was chosen arbitrarily, we should be able to change it to 180 days, to remove any ambiguity between the in-memory DB, and the Postgres DB. The alternative solution would involve implementing Postgres' month interval algorithm in Go.

The UI only shows stats as old as 168 days (24 weeks), so a frontend change isn't required for the extra days of stats we lose in some cases.

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#14489** <a href="https://app.graphite.dev/github/pr/coder/coder/14489?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ethanndickson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ethanndickson** [comment]
I realise now we could just skip the test with the in-memory DB... Happy to do either...

**Review by dannykopping — APPROVED** [review]
LGTM

**Comment by mafredri** [comment]
Nice find! I agree with the fix, predictability (180) is nicer than ambiguity (varying) 👍🏻

**Pull request merged**
