### PR TITLE
fix(flake.nix): add google-chrome to nix flake

### PR DESCRIPTION
**Pull request by johnstcn**
Required for scaletest tests.

### CODE REVIEW

**Comment by matifali** [comment]
Another option can be to install google-chrome in final Ubuntu stage.

**Review by mtojek — APPROVED** [review]
Atif, most likely it is used by one of the scaletests .sh scripts

**Comment by matifali** [comment]
Ok. But does it matter if the google-chrome is in Nix stage or the final Ubuntu stage of the Docker build?
It will be always on path for both cases.

**Comment by johnstcn** [comment]
> Ok. But does it matter if the google-chrome is in Nix stage or the final Ubuntu stage of the Docker build? It will be always on path for both cases.

No, it just needs to be in `$PATH`. If it's more efficient to install in the final stage, we can do that instead.

**Review by matifali — APPROVED** [review]

**Pull request merged**
