### PR TITLE
fix: make text colors legible

### LINKED ISSUE #3222: Fix color on invalid fields
## Problem
Validation error messages are hard to read because they're a dark red against a dark background

Screen Shot 2022-07-26 at 1 44 21 PM

## Definition of Done
Validation error messages are clearly legible and pass at least the AA level for normal text here https://webaim.org/resources/contrastchecker/

## Implementation notes
The color change should be done in the theme's palette to keep the code DRY.

### LINKED ISSUE #3230: Fix color in Dialog
## Problem
The color of the word Cancel in this Dialog is hard to read against the dark background
Screen Shot 2022-07-26 at 3 48 46 PM

## Definition of Done
The word is easy to read and the contrast between the text and background colors meets at least the AA level here https://webaim.org/resources/contrastchecker/

### PR DESCRIPTION
**Pull request by presleyp**
Fixes #3222 
Fixes #3230 

- [x] changed `error.main` color to a lighter one for legible color contrast in validation error messages
- [x] added `contrastText` to more parts of the palette so we use it instead of defaulting to illegible near-black
- [x] changed Dialog styles to use `error.dark` as the button background instead of `error.main`. Hover styles darken a color, and `error.dark` is VERY dark currently, so I had it start at a lightened version and darken to the standard.

The color palette will need more work - the color contrast between button background and text doesn't pass accessibility tests on other buttons (the blue ones). But this PR improves the most egregious places I had seen.

Screen Shot 2022-07-27 at 11 01 59 AM
Screen Shot 2022-07-27 at 11 01 37 AM

### Validation messages
Given I am logged out,
When I type a letter in the email field and then click on the password field,
Then I see a legible validation message 

### Dialogs
Given I have created a new user,
When I suspend that user,
Then I see a confirmation dialog with legible buttons

### CODE REVIEW

**Comment by AbhineetJain** [comment]
Did we also test the contrast for the background of the `ErrorSummary` component and the details section inside it? I remember using `error.main` with `darken` for it, so wondering if that would change as well.

**Comment by AbhineetJain** [comment]
As per Storybook, there seem to be multiple components that have updated. I am not sure if some of the color combinations are aesthetically okay e.g. [this one with the error box and the field error having different reds](https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-62df0cfd68f01acbab17534d-1200&appId=624de63c6aacee003aa84340&number=3250&view=changes).

**Comment by presleyp** [comment]
@AbhineetJain yeah, background and text colors should differ, that's ok. The contrast between the ErrorSummary background and its text is good but between the background and the More/Less link is not good, so I'll need to tweak that or note it for later. I'll keep going through Chromatic...

**Comment by presleyp** [comment]
Ok, I lightened the color in our palette that's used for links, so we'll see what changes that causes! It does fix the contrast in the Error Summary.

**Comment by presleyp** [comment]
Lightening all links made them too un-obvious, I think, so I just `lighten`ed the link in ErrorSummary.

**Review by Kira-Pilot — APPROVED** [review]

**Pull request merged**
