### PR TITLE
fix: Update cli usage template for cobra feature parity

### PR DESCRIPTION
**Pull request by mafredri**
This PR updates the custom usage template for feature parity with the default template used in Cobra.

I've restored the custom heading names and colorization.

Changes:
- We now display Usage properly for subcommands
- We now display "Global Flags" for all commands
- We now display "Aliases" for aliased commands
- Flags moved below Commands as per standard Cobra template

This is partially related to #1233 and #1403, but as suggested by @jsjoeio, split into a separate PR.

Fixes #1423

Example:
image

### CODE REVIEW

**Review by deansheather — APPROVED** [review]
syntax seems fine but if you could quickly tidy up the template that would be nice 👍

**Review by johnstcn — APPROVED** [review]
LGTM as well, just some cleanup 👍

**Review by kylecarbs — APPROVED** [review]
LGTM. My bad for missing a few of these cases!

**Review by Emyrk — APPROVED** [review]
Ohh it's the `{{-` got it

**Pull request merged**
