### PR TITLE
docs: explain --rich-parameter-file format

### LINKED ISSUE #13839: CLI Docs: explain `--rich-parameter-file` format
The CLI docs for `coder create --rich-parameter-file` do not explain the format or syntax for a parameter file. The alternative is to use `--parameter "key=value"` for every parameter in the template, which is tedious. We should briefly describe how to create a parameter file for this flag.

https://coder.com/docs/cli/create#--rich-parameter-file

cc: @mtojek

### PR DESCRIPTION
**Pull request by joobisb**
This PR closes https://github.com/coder/coder/issues/13839

### CODE REVIEW

**Comment by matifali** [comment]
Hi, @joobisb, this is an autogenerated file, so you should make this change in the go code for the `create` command.

**Comment by joobisb** [comment]
> Hi, @joobisb, this is an autogenerated file, so you should make this change in the go code for the `create` command.

oops, sorry didn't know that. Thanks for clarifying, will make those changes

**Comment by joobisb** [comment]
> > Hi, @joobisb, this is an autogenerated file, so you should make this change in the go code for the `create` command.
> 
> oops, sorry didn't know that. Thanks for clarifying, will make those changes

fixed it

**Review by matifali — APPROVED** [review]
Thanks for the contribution. When the CI passes it is good to merge.

**Comment by joobisb** [comment]
> Thanks for the contribution. When the CI passes it is good to merge.

@matifali can we merge this?

**Pull request merged**
