### PR TITLE
chore: refactor workspaces query to use window function

### PR DESCRIPTION
**Pull request by presleyp**
Use window function to get count in the same query as workspaces.

### CODE REVIEW

**Review by f0ssel — COMMENTED** [review]
Looks great, glad it's this simple. 

Could we also just go ahead and remove the route and front end usage of the count endpoint in this PR?

**Comment by presleyp** [comment]
> Looks great, glad it's this simple.
> 
> Could we also just go ahead and remove the route and front end usage of the count endpoint in this PR?

That's mostly done already but I see some count cruft left in the machine that I'll take out.

**Review by Kira-Pilot — COMMENTED** [review]
FE ✅

**Review by Kira-Pilot — APPROVED** [review]

**Review by BrunoQuaresma — APPROVED** [review]
Lgtm

**Pull request merged**
