### PR TITLE
chore: update sqlc to 1.25.0

### PR DESCRIPTION
**Pull request by code-asher**
The flake.lock was updated and now uses sqlc 1.25.0, so update the Dockerfile and CI to match and regen so nix and non-nix users are all generating the same thing.

We could also downgrade sqlc back down to 1.24.0 in the flake, but I think upgrading is easier.

### CODE REVIEW

**Comment by code-asher** [comment]
Image build failing with `Organization free trial period has ended` :confused:

**Comment by coadler** [comment]
I think you'll also have to change `.github/actions/setup-sqlc/action.yaml` to the new version

**Comment by code-asher** [comment]
> I think you'll also have to change `.github/actions/setup-sqlc/action.yaml` to the new version

Thank you!  Updated.

**Review by coadler — APPROVED** [review]

**Comment by code-asher** [comment]
@matifali any idea on the build failure?

**Comment by matifali** [comment]
cc: @ammario it's s depot.dev issue

**Comment by matifali** [comment]
I have added `docker-buildx` builder as a fallback, which will build it very slowly instead of failing if there is an issue with the depot.dev

**Comment by ammario** [comment]
At least some of the issue is that our trial expired. But I'm also getting this error as I try to fix it by adding a card:

**Pull request merged**
