### PR TITLE
fix(site): only show workspace actions if user has permission

### LINKED ISSUE #9175: Improve UX for template admin when viewing users' workspaces
## Background

The template admin can view other users' workspaces to view the build logs, but they cannot access coder_apps, the terminal, or perform actions (stop/start/etc)

## Current behavior

@matifali brought up a good point with these two issues https://github.com/coder/coder/issues/9081 https://github.com/coder/coder/issues/9082. The UX is quite confusing which makes Coder look broken. Template admins can click into workspaces but then get vague errors.

## Proposed behavior

We disable buttons for unavailable actions for template admins with a tooltip that explains they do not have permissions to do the action. Alternatively, we change the error on the terminal page, coder_apps, etc to show the user does not have permisisons

We also have [CODER_DISABLE_OWNER_WORKSPACE_ACCESS](https://coder.com/docs/v2/latest/cli/server#--disable-owner-workspace-access) so the product should also disable the button for owners on workspaces that is not theirs if that is flag is enabled.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix https://github.com/coder/coder/issues/9175

Screen Shot 2023-08-24 at 10 34 35

### CODE REVIEW

**Comment by matifali** [comment]
Where can they see the build logs?

**Comment by BrunoQuaresma** [comment]
@matifali 
Screen Shot 2023-08-24 at 10 34 35

**Comment by matifali** [comment]
> @matifali 
> Screen Shot 2023-08-24 at 10 34 35
> 

Why I couldn't see. Thanks @BrunoQuaresma

**Review by matifali — APPROVED** [review]
LGTM

**Pull request merged**
