### PR TITLE
chore(examples/templates/incus): fix metadata

### PR DESCRIPTION
**Pull request by matifali**
This will probably fix https://vercel.com/codercom/registry/6xHz3A1oBP3iyix3J1AH9vA1rchY
and https://github.com/coder/modules/issues/185

### CODE REVIEW

**Review by johnstcn — COMMENTED** [review]
Wait, so any typo in an example template can break the registry? 🤔

**Comment by matifali** [comment]
Yes thats what it looks like. I just discovered this. Someone with @coder/ts knowledge should take a look to resolve this.

**Comment by matifali** [comment]
https://vercel.com/codercom/registry/9QgZvTD5pMeDX51x8fVzei3GtD5B is still failing. How can we force a new deployment that fetches templates from latest `main`

**Comment by mafredri** [comment]
@matifali try now, there's a 10 minute cache so it should be clearing up now or shortly.

**Pull request merged**
