### PR TITLE
chore(site): Normalize colors usage

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Colors should not be used directly from the colors file since it makes it hard to create new themes and make them consistent across changes.

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
Waiting for the storybook to fix possible color issues.

**Comment by matifali** [comment]
Are we planning to add the ability to switch a light theme in future?

**Comment by BrunoQuaresma** [comment]
Not "real planning" but organizing the colors and centralizing where it is defined will be helpful for a lot of things in the future including new themes.

**Review by Kira-Pilot — APPROVED** [review]

**Comment by kylecarbs** [comment]
@BrunoQuaresma I left a review on some of the UI style changes in Storybook. Some of the buttons aren't legible and need minor tweaks.

**Comment by BrunoQuaresma** [comment]
@kylecarbs yes, after also take a look on the storybook I will probably hold this PR a bit longer until I get colors figured out.

**Pull request closed without merging**
