### PR TITLE
chore: add oidc sequence diagram image to docs

### PR DESCRIPTION
**Pull request by Emyrk**
Screenshot from 2023-08-14 10-43-34

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
I guess relative links work well. An example that I found in the scheduling docs:
```
![autostop UI](./images/autostop.png)
```

**Comment by bpmct** [comment]
hmm that is an image though, not a link?

**Comment by BrunoQuaresma** [comment]
Ahhh ok 👍 I see Steven fixed that tho. But why not include it as an image instead of an external link to an image? 🤔

**Comment by Emyrk** [comment]
> Ahhh ok +1 I see Steven fixed that tho. But why not include it as an image instead of an external link to an image? thinking

I changed it to a link because I don't think the image would work.

And @BrunoQuaresma It's an external link just because we intentionally don't want to embed it in the docs and take up a lot of space. It is a niche request that only a few people will even care about

**Review by bpmct — APPROVED** [review]

**Pull request merged**
