### PR TITLE
ci: limit test parallelism

### PR DESCRIPTION
**Pull request by johnstcn**
Sets `-parallel=4` in `test-postgres` and `test-race` to match the [hosted runner spec](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

### CODE REVIEW

**Comment by spikecurtis** [comment]
Do you think we still need this with: https://github.com/coder/coder/pull/12760 ?

**Comment by kylecarbs** [comment]
@johnstcn if we do this, then we should lower the size of our runners dramatically, otherwise we'll be paying for a lot of compute we aren't using.

**Comment by johnstcn** [comment]
@kylecarbs hopefully we won't need it 🤞

**Comment by spikecurtis** [comment]
I vote we close this one

**Pull request closed without merging**
